// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type AccountSetTutorialResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    
}

func (x *AccountSetTutorialResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountSetTutorialResponse) ProtoReflect() mx.Message {
	return x
}

func (x *AccountSetTutorialResponse) GetProtocol() int32 {
	return Protocol_Account_SetTutorial
}

func (x *AccountSetTutorialResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

