// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type AccountSetTutorialRequest struct{
	message mx.ProtoMessage
	RequestPacket

    TutorialIds []int64
}

func (x *AccountSetTutorialRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountSetTutorialRequest) ProtoReflect() mx.Message {
	return x
}

func (x *AccountSetTutorialRequest) GetProtocol() int32 {
	return Protocol_Account_SetTutorial
}

func (x *AccountSetTutorialRequest) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

