// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type AccountCurrencySyncRequest struct{
	message mx.ProtoMessage
	RequestPacket

    
}

func (x *AccountCurrencySyncRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountCurrencySyncRequest) ProtoReflect() mx.Message {
	return x
}

func (x *AccountCurrencySyncRequest) GetProtocol() int32 {
	return Protocol_Account_CurrencySync
}
func (x *AccountCurrencySyncRequest) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

