// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "time"
)

type CafeProductionDB struct{
    CafeDBId int64
    ComfortValue int64
    AppliedDate time.Time
    ProductionParcelInfos []*CafeProductionParcelInfo
}

