// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type CampaignListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    CampaignChapterClearRewardHistoryDBs []*CampaignChapterClearRewardHistoryDB
    StageHistoryDBs []*CampaignStageHistoryDB
    StrategyObjecthistoryDBs []*StrategyObjectHistoryDB
    DailyResetCountDB *DailyResetCountDB
}

func (x *CampaignListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CampaignListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *CampaignListResponse) GetProtocol() int32 {
	return Protocol_Campaign_List
}

func (x *CampaignListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

