// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "time"
)

type ClanAssistSlotDB struct{
    EchelonType EchelonType
    SlotNumber int64
    CharacterDBId int64
    DeployDate time.Time
    TotalRentCount int64
    CombatStyleIndex int32
}

