// Code generated by gucooing DO NOT EDIT.

package proto

type CurrencyTypes int32

const (
    CurrencyTypes_Invalid = 0
    CurrencyTypes_Gold = 1
    CurrencyTypes_GemPaid = 2
    CurrencyTypes_GemBonus = 3
    CurrencyTypes_Gem = 4
    CurrencyTypes_ActionPoint = 5
    CurrencyTypes_AcademyTicket = 6
    CurrencyTypes_ArenaTicket = 7
    CurrencyTypes_RaidTicket = 8
    CurrencyTypes_WeekDungeonChaserATicket = 9
    CurrencyTypes_WeekDungeonFindGiftTicket = 10
    CurrencyTypes_WeekDungeonBloodTicket = 11
    CurrencyTypes_WeekDungeonChaserBTicket = 12
    CurrencyTypes_WeekDungeonChaserCTicket = 13
    CurrencyTypes_SchoolDungeonATicket = 14
    CurrencyTypes_SchoolDungeonBTicket = 15
    CurrencyTypes_SchoolDungeonCTicket = 16
    CurrencyTypes_TimeAttackDungeonTicket = 17
    CurrencyTypes_MasterCoin = 18
    CurrencyTypes_WorldRaidTicketA = 19
    CurrencyTypes_WorldRaidTicketB = 20
    CurrencyTypes_WorldRaidTicketC = 21
    CurrencyTypes_ChaserTotalTicket = 22
    CurrencyTypes_SchoolDungeonTotalTicket = 23
    CurrencyTypes_EliminateTicketA = 24
    CurrencyTypes_EliminateTicketB = 25
    CurrencyTypes_EliminateTicketC = 26
    CurrencyTypes_EliminateTicketD = 27
    CurrencyTypes_Max = 28
)

var (
    CurrencyTypes_name = map[int32]string{
      0 : "Invalid",
      1 : "Gold",
      2 : "GemPaid",
      3 : "GemBonus",
      4 : "Gem",
      5 : "ActionPoint",
      6 : "AcademyTicket",
      7 : "ArenaTicket",
      8 : "RaidTicket",
      9 : "WeekDungeonChaserATicket",
      10 : "WeekDungeonFindGiftTicket",
      11 : "WeekDungeonBloodTicket",
      12 : "WeekDungeonChaserBTicket",
      13 : "WeekDungeonChaserCTicket",
      14 : "SchoolDungeonATicket",
      15 : "SchoolDungeonBTicket",
      16 : "SchoolDungeonCTicket",
      17 : "TimeAttackDungeonTicket",
      18 : "MasterCoin",
      19 : "WorldRaidTicketA",
      20 : "WorldRaidTicketB",
      21 : "WorldRaidTicketC",
      22 : "ChaserTotalTicket",
      23 : "SchoolDungeonTotalTicket",
      24 : "EliminateTicketA",
      25 : "EliminateTicketB",
      26 : "EliminateTicketC",
      27 : "EliminateTicketD",
      28 : "Max",
   }
    CurrencyTypes_value = map[string]int32{
      "Invalid" : 0,
      "Gold" : 1,
      "GemPaid" : 2,
      "GemBonus" : 3,
      "Gem" : 4,
      "ActionPoint" : 5,
      "AcademyTicket" : 6,
      "ArenaTicket" : 7,
      "RaidTicket" : 8,
      "WeekDungeonChaserATicket" : 9,
      "WeekDungeonFindGiftTicket" : 10,
      "WeekDungeonBloodTicket" : 11,
      "WeekDungeonChaserBTicket" : 12,
      "WeekDungeonChaserCTicket" : 13,
      "SchoolDungeonATicket" : 14,
      "SchoolDungeonBTicket" : 15,
      "SchoolDungeonCTicket" : 16,
      "TimeAttackDungeonTicket" : 17,
      "MasterCoin" : 18,
      "WorldRaidTicketA" : 19,
      "WorldRaidTicketB" : 20,
      "WorldRaidTicketC" : 21,
      "ChaserTotalTicket" : 22,
      "SchoolDungeonTotalTicket" : 23,
      "EliminateTicketA" : 24,
      "EliminateTicketB" : 25,
      "EliminateTicketC" : 26,
      "EliminateTicketD" : 27,
      "Max" : 28,
   }
)

func (x CurrencyTypes) String() string {
  return CurrencyTypes_name[int32(x)]
}

