// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type EchelonListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    EchelonDBs []*EchelonDB
    ArenaEchelonDB *EchelonDB
}

func (x *EchelonListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EchelonListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *EchelonListResponse) GetProtocol() int32 {
	return Protocol_Echelon_List
}

func (x *EchelonListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

