// Code generated by gucooing DO NOT EDIT.

package proto

type EquipmentDB struct{
    Type ParcelType
    Level int32
    Exp int64
    Tier int32
    BoundCharacterServerId int64
    IsNew bool
    IsLocked bool
}

