// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type GuideMissionSeasonListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    GuideMissionSeasonDBs []*GuideMissionSeasonDB
}

func (x *GuideMissionSeasonListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *GuideMissionSeasonListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *GuideMissionSeasonListResponse) GetProtocol() int32 {
	return Protocol_Mission_GuideMissionSeasonList
}


func (x *GuideMissionSeasonListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

