// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type ItemListRequest struct{
	message mx.ProtoMessage
	RequestPacket

    
}

func (x *ItemListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ItemListRequest) ProtoReflect() mx.Message {
	return x
}

func (x *ItemListRequest) GetProtocol() int32 {
	return Protocol_Item_List
}
func (x *ItemListRequest) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

