// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type MailCheckResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    Count int64
}

func (x *MailCheckResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MailCheckResponse) ProtoReflect() mx.Message {
	return x
}

func (x *MailCheckResponse) GetProtocol() int32 {
	return Protocol_Mail_Check
}

func (x *MailCheckResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

