// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type MissionListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    MissionHistoryUniqueIds []int64
    ProgressDBs []*MissionProgressDB
    DailySuddenMissionInfo *MissionInfo
    ClearedOrignalMissionIds []int64
}

func (x *MissionListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MissionListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *MissionListResponse) GetProtocol() int32 {
	return Protocol_Mission_List
}

func (x *MissionListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

