// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type MomoTalkOutLineRequest struct{
	message mx.ProtoMessage
	RequestPacket

    
}

func (x *MomoTalkOutLineRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MomoTalkOutLineRequest) ProtoReflect() mx.Message {
	return x
}

func (x *MomoTalkOutLineRequest) GetProtocol() int32 {
	return Protocol_MomoTalk_OutLine
}

func (x *MomoTalkOutLineRequest) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

