// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type MultiFloorRaidSyncRequest struct{
	message mx.ProtoMessage
	RequestPacket

    SeasonId int64
}

func (x *MultiFloorRaidSyncRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MultiFloorRaidSyncRequest) ProtoReflect() mx.Message {
	return x
}

func (x *MultiFloorRaidSyncRequest) GetProtocol() int32 {
	return Protocol_MultiFloorRaid_Sync
}

func (x *MultiFloorRaidSyncRequest) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

