// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type ShopGachaRecruitListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    ShopRecruits []*ShopRecruitDB
    ShopFreeRecruitHistoryDBs []*ShopFreeRecruitHistoryDB
}

func (x *ShopGachaRecruitListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopGachaRecruitListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *ShopGachaRecruitListResponse) GetProtocol() int32 {
	return Protocol_Shop_GachaRecruitList
}

func (x *ShopGachaRecruitListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

