// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type ShopBeforehandGachaGetResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    AlreadyPicked bool
    BeforehandGachaSnapshot *BeforehandGachaSnapshotDB
}

func (x *ShopBeforehandGachaGetResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBeforehandGachaGetResponse) ProtoReflect() mx.Message {
	return x
}

func (x *ShopBeforehandGachaGetResponse) GetProtocol() int32 {
	return Protocol_Shop_BeforehandGachaGet
}

func (x *ShopBeforehandGachaGetResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

