// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/mx"
)

type ToastListResponse struct{
	message mx.ProtoMessage
	ResponsePacket

    ToastDBs []*ToastDB
}

func (x *ToastListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ToastListResponse) ProtoReflect() mx.Message {
	return x
}

func (x *ToastListResponse) GetProtocol() int32 {
	return Protocol_Toast_List
}

func (x *ToastListResponse) SetSessionKey(base *mx.BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

