name: Docker Hub

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync BaPs
        uses: actions/checkout@v3
        with:
          repository: gucooing/BaPs
          ref: "main"
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            excel_url=${{ secrets.EXCEL_URL }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gucooing/baps:latest