package cmd

import (
	"github.com/gucooing/BaPs/mx/proto"
)

func (c *CmdProtoMap) registerAllMessage() {
	c.regMsg(proto.Protocol_Queuing_GetTicket, func() any { return new(proto.QueuingGetTicketRequest) }, true)
	c.regMsg(proto.Protocol_Queuing_GetTicket, func() any { return new(proto.QueuingGetTicketResponse) }, false)
	c.regMsg(proto.Protocol_Account_CheckYostar, func() any { return new(proto.AccountCheckYostarRequest) }, true)
	c.regMsg(proto.Protocol_Account_CheckYostar, func() any { return new(proto.AccountCheckYostarResponse) }, false)
	c.regMsg(proto.Protocol_Account_Auth, func() any { return new(proto.AccountAuthRequest) }, true)
	c.regMsg(proto.Protocol_Account_Auth, func() any { return new(proto.AccountAuthResponse) }, false)
	c.regMsg(proto.Protocol_Account_Nickname, func() any { return new(proto.AccountNicknameRequest) }, true)
	c.regMsg(proto.Protocol_Account_Nickname, func() any { return new(proto.AccountNicknameResponse) }, false)
	c.regMsg(proto.Protocol_ProofToken_RequestQuestion, func() any { return new(proto.ProofTokenRequestQuestionRequest) }, true)
	c.regMsg(proto.Protocol_ProofToken_RequestQuestion, func() any { return new(proto.ProofTokenRequestQuestionResponse) }, false)
	c.regMsg(proto.Protocol_NetworkTime_Sync, func() any { return new(proto.NetworkTimeSyncRequest) }, true)
	c.regMsg(proto.Protocol_NetworkTime_Sync, func() any { return new(proto.NetworkTimeSyncResponse) }, false)
	c.regMsg(proto.Protocol_Academy_GetInfo, func() any { return new(proto.AcademyGetInfoRequest) }, true)
	c.regMsg(proto.Protocol_Academy_GetInfo, func() any { return new(proto.AcademyGetInfoResponse) }, false)
	c.regMsg(proto.Protocol_Account_LoginSync, func() any { return new(proto.AccountLoginSyncRequest) }, true)
	c.regMsg(proto.Protocol_Account_LoginSync, func() any { return new(proto.AccountLoginSyncResponse) }, false)
	c.regMsg(proto.Protocol_Cafe_Get, func() any { return new(proto.CafeGetInfoRequest) }, true)
	c.regMsg(proto.Protocol_Cafe_Get, func() any { return new(proto.CafeGetInfoResponse) }, false)
	c.regMsg(proto.Protocol_Account_CurrencySync, func() any { return new(proto.AccountCurrencySyncRequest) }, true)
	c.regMsg(proto.Protocol_Account_CurrencySync, func() any { return new(proto.AccountCurrencySyncResponse) }, false)
	c.regMsg(proto.Protocol_Character_List, func() any { return new(proto.CharacterListRequest) }, true)
	c.regMsg(proto.Protocol_Character_List, func() any { return new(proto.CharacterListResponse) }, false)
	c.regMsg(proto.Protocol_Item_List, func() any { return new(proto.ItemListRequest) }, true)
	c.regMsg(proto.Protocol_Item_List, func() any { return new(proto.ItemListResponse) }, false)
	c.regMsg(proto.Protocol_ContentSave_Get, func() any { return new(proto.ContentSaveGetRequest) }, true)
	c.regMsg(proto.Protocol_ContentSave_Get, func() any { return new(proto.ContentSaveGetResponse) }, false)
	c.regMsg(proto.Protocol_Shop_BeforehandGachaGet, func() any { return new(proto.ShopBeforehandGachaGetRequest) }, true)
	c.regMsg(proto.Protocol_Shop_BeforehandGachaGet, func() any { return new(proto.ShopBeforehandGachaGetResponse) }, false)
	c.regMsg(proto.Protocol_ProofToken_Submit, func() any { return new(proto.ProofTokenSubmitRequest) }, true)
	c.regMsg(proto.Protocol_ProofToken_Submit, func() any { return new(proto.ProofTokenSubmitResponse) }, false)
	c.regMsg(proto.Protocol_Equipment_List, func() any { return new(proto.EquipmentItemListRequest) }, true)
	c.regMsg(proto.Protocol_Equipment_List, func() any { return new(proto.EquipmentItemListResponse) }, false)
	c.regMsg(proto.Protocol_CharacterGear_List, func() any { return new(proto.CharacterGearListRequest) }, true)
	c.regMsg(proto.Protocol_CharacterGear_List, func() any { return new(proto.CharacterGearListResponse) }, false)
	c.regMsg(proto.Protocol_Echelon_List, func() any { return new(proto.EchelonListRequest) }, true)
	c.regMsg(proto.Protocol_Echelon_List, func() any { return new(proto.EchelonListResponse) }, false)
	c.regMsg(proto.Protocol_MemoryLobby_List, func() any { return new(proto.MemoryLobbyListRequest) }, true)
	c.regMsg(proto.Protocol_MemoryLobby_List, func() any { return new(proto.MemoryLobbyListResponse) }, false)
	c.regMsg(proto.Protocol_Campaign_List, func() any { return new(proto.CampaignListRequest) }, true)
	c.regMsg(proto.Protocol_Campaign_List, func() any { return new(proto.CampaignListResponse) }, false)
	c.regMsg(proto.Protocol_Arena_Login, func() any { return new(proto.ArenaLoginRequest) }, true)
	c.regMsg(proto.Protocol_Arena_Login, func() any { return new(proto.ArenaLoginResponse) }, false)
	c.regMsg(proto.Protocol_Raid_Login, func() any { return new(proto.RaidLoginRequest) }, true)
	c.regMsg(proto.Protocol_Raid_Login, func() any { return new(proto.RaidLoginResponse) }, false)
	c.regMsg(proto.Protocol_EliminateRaid_Login, func() any { return new(proto.EliminateRaidLoginRequest) }, true)
	c.regMsg(proto.Protocol_EliminateRaid_Login, func() any { return new(proto.EliminateRaidLoginResponse) }, false)
	c.regMsg(proto.Protocol_Craft_List, func() any { return new(proto.CraftInfoListRequest) }, true)
	c.regMsg(proto.Protocol_Craft_List, func() any { return new(proto.CraftInfoListResponse) }, false)
	c.regMsg(proto.Protocol_Clan_Login, func() any { return new(proto.ClanLoginRequest) }, true)
	c.regMsg(proto.Protocol_Clan_Login, func() any { return new(proto.ClanLoginResponse) }, false)
	c.regMsg(proto.Protocol_MomoTalk_OutLine, func() any { return new(proto.MomoTalkOutLineRequest) }, true)
	c.regMsg(proto.Protocol_MomoTalk_OutLine, func() any { return new(proto.MomoTalkOutLineResponse) }, false)
	c.regMsg(proto.Protocol_Scenario_List, func() any { return new(proto.ScenarioListRequest) }, true)
	c.regMsg(proto.Protocol_Scenario_List, func() any { return new(proto.ScenarioListResponse) }, false)
	c.regMsg(proto.Protocol_Shop_GachaRecruitList, func() any { return new(proto.ShopGachaRecruitListRequest) }, true)
	c.regMsg(proto.Protocol_Shop_GachaRecruitList, func() any { return new(proto.ShopGachaRecruitListResponse) }, false)
	c.regMsg(proto.Protocol_TimeAttackDungeon_Login, func() any { return new(proto.TimeAttackDungeonLoginRequest) }, true)
	c.regMsg(proto.Protocol_TimeAttackDungeon_Login, func() any { return new(proto.TimeAttackDungeonLoginResponse) }, false)
	c.regMsg(proto.Protocol_Billing_PurchaseListByYostar, func() any { return new(proto.BillingPurchaseListByYostarRequest) }, true)
	c.regMsg(proto.Protocol_Billing_PurchaseListByYostar, func() any { return new(proto.BillingPurchaseListByYostarResponse) }, false)
	c.regMsg(proto.Protocol_EventContent_PermanentList, func() any { return new(proto.EventContentPermanentListRequest) }, true)
	c.regMsg(proto.Protocol_EventContent_PermanentList, func() any { return new(proto.EventContentPermanentListResponse) }, false)
	c.regMsg(proto.Protocol_Attachment_Get, func() any { return new(proto.AttachmentGetRequest) }, true)
	c.regMsg(proto.Protocol_Attachment_Get, func() any { return new(proto.AttachmentGetResponse) }, false)
	c.regMsg(proto.Protocol_Attachment_EmblemList, func() any { return new(proto.AttachmentEmblemListRequest) }, true)
	c.regMsg(proto.Protocol_Attachment_EmblemList, func() any { return new(proto.AttachmentEmblemListResponse) }, false)
	c.regMsg(proto.Protocol_Sticker_Login, func() any { return new(proto.StickerLoginRequest) }, true)
	c.regMsg(proto.Protocol_Sticker_Login, func() any { return new(proto.StickerLoginResponse) }, false)
	c.regMsg(proto.Protocol_MultiFloorRaid_Sync, func() any { return new(proto.MultiFloorRaidSyncRequest) }, true)
	c.regMsg(proto.Protocol_MultiFloorRaid_Sync, func() any { return new(proto.MultiFloorRaidSyncResponse) }, false)
	c.regMsg(proto.Protocol_ContentSweep_MultiSweepPresetList, func() any { return new(proto.ContentSweepMultiSweepPresetListRequest) }, true)
	c.regMsg(proto.Protocol_ContentSweep_MultiSweepPresetList, func() any { return new(proto.ContentSweepMultiSweepPresetListResponse) }, false)
	c.regMsg(proto.Protocol_Account_GetTutorial, func() any { return new(proto.AccountGetTutorialRequest) }, true)
	c.regMsg(proto.Protocol_Account_GetTutorial, func() any { return new(proto.AccountGetTutorialResponse) }, false)
	c.regMsg(proto.Protocol_Mission_List, func() any { return new(proto.MissionListRequest) }, true)
	c.regMsg(proto.Protocol_Mission_List, func() any { return new(proto.MissionListResponse) }, false)
	c.regMsg(proto.Protocol_Mission_GuideMissionSeasonList, func() any { return new(proto.GuideMissionSeasonListRequest) }, true)
	c.regMsg(proto.Protocol_Mission_GuideMissionSeasonList, func() any { return new(proto.GuideMissionSeasonListResponse) }, false)
	c.regMsg(proto.Protocol_Toast_List, func() any { return new(proto.ToastListRequest) }, true)
	c.regMsg(proto.Protocol_Toast_List, func() any { return new(proto.ToastListResponse) }, false)
}
