// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AcademyGetInfoResponse struct{
	message ProtoMessage
	ResponsePacket

    AcademyDB *AcademyDB
    AcademyLocationDBs []*AcademyLocationDB
}

func (x *AcademyGetInfoResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AcademyGetInfoResponse) ProtoReflect() Message {
	return x
}

func (x *AcademyGetInfoResponse) GetProtocol() int32 {
	return mx.Protocol_Academy_GetInfo
}

func (x *AcademyGetInfoResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

