// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AcademyAttendScheduleResponse struct{
	message ProtoMessage
	ResponsePacket

    ParcelResultDB *ParcelResultDB
    AcademyDB *AcademyDB
    ExtraRewards []*ParcelInfo
}

func (x *AcademyAttendScheduleResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AcademyAttendScheduleResponse) ProtoReflect() Message {
	return x
}

func (x *AcademyAttendScheduleResponse) GetProtocol() int32 {
	return mx.Protocol_Academy_AttendSchedule
}

func (x *AcademyAttendScheduleResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

