// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AccountCurrencySyncResponse struct{
	message ProtoMessage
	ResponsePacket

    AccountCurrencyDB *AccountCurrencyDB
	ExpiredCurrency map[CurrencyTypes]int64
}

func (x *AccountCurrencySyncResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountCurrencySyncResponse) ProtoReflect() Message {
	return x
}

func (x *AccountCurrencySyncResponse) GetProtocol() int32 {
	return mx.Protocol_Account_CurrencySync
}

func (x *AccountCurrencySyncResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

