// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AccountAuthRequest struct{
	message ProtoMessage
	RequestPacket

    Version int64
    DevId string
    IMEI int64
    AccessIP string
    MarketId string
    UserType string
    AdvertisementId string
    OSType string
    OSVersion string
    DeviceUniqueId string
    DeviceModel string
    DeviceSystemMemorySize int32
}

func (x *AccountAuthRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountAuthRequest) ProtoReflect() Message {
	return x
}

func (x *AccountAuthRequest) GetProtocol() int32 {
	return mx.Protocol_Account_Auth
}

func (x *AccountAuthRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

