// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "time"

    "github.com/gucooing/BaPs/pkg/mx"
)

type AccountDB struct{
    ServerId int64
    Nickname string
    CallName string
    CallNameKatakana string
    CallNameKorean string
    DevId string
    State AccountState
    Level int32
    Exp int64
    Comment string
    LobbyMode int32
    RepresentCharacterServerId int64
    MemoryLobbyUniqueId int64
    LastConnectTime mx.MxTime
    BirthDay time.Time
    CallNameUpdateTime time.Time
    PublisherAccountId int64
    RetentionDays int32
    VIPLevel int32
    CreateDate time.Time
    UnReadMailCount int32
    LinkRewardDate time.Time
}

