// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AccountCurrencyDB struct {
	AccountLevel           int64
	AcademyLocationRankSum int64
	CurrencyDict           map[string]int64
	UpdateTimeDict         map[string]mx.MxTime
}

func (x *AccountCurrencyDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
