// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AccountLoginSyncRequest struct {
	*RequestPacket

	SyncProtocols    []Protocol
	SkillCutInOption string
}

func (x *AccountLoginSyncRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *AccountLoginSyncRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
