// Code generated by gucooing DO NOT EDIT.

package proto

import (


    "github.com/gucooing/BaPs/pkg/mx"
)

type AccountCurrencyDB struct{
    AccountLevel int64
    AcademyLocationRankSum int64
    CurrencyDict map[CurrencyTypes]int64
    UpdateTimeDict map[CurrencyTypes]mx.MxTime
}

