// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AccountSetRepresentCharacterAndCommentRequest struct{
	message ProtoMessage
	RequestPacket

    RepresentCharacterServerId int64
    Comment string
}

func (x *AccountSetRepresentCharacterAndCommentRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountSetRepresentCharacterAndCommentRequest) ProtoReflect() Message {
	return x
}

func (x *AccountSetRepresentCharacterAndCommentRequest) GetProtocol() int32 {
	return mx.Protocol_Account_SetRepresentCharacterAndComment
}

func (x *AccountSetRepresentCharacterAndCommentRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

