// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AccountLoginSyncRequest struct{
	message ProtoMessage
	RequestPacket

    SyncProtocols []mx.Protocol
	SkillCutInOption string
}

func (x *AccountLoginSyncRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountLoginSyncRequest) ProtoReflect() Message {
	return x
}

func (x *AccountLoginSyncRequest) GetProtocol() int32 {
	return mx.Protocol_Account_LoginSync
}

func (x *AccountLoginSyncRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

