// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AccountAuthRequest struct {
	*RequestPacket

	Version                int64
	DevId                  string
	IMEI                   int64
	AccessIP               string
	MarketId               string
	UserType               string
	AdvertisementId        string
	OSType                 string
	OSVersion              string
	DeviceUniqueId         string
	DeviceModel            string
	DeviceSystemMemorySize int32
}

func (x *AccountAuthRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *AccountAuthRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
