// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AccountAuthResponse struct{
	message ProtoMessage
	ResponsePacket

    CurrentVersion int64
    MinimumVersion int64
    IsDevelopment bool
    BattleValidation bool
    UpdateRequired bool
    TTSCdnUri string
    AccountDB *AccountDB
    AttendanceBookRewards []*AttendanceBookReward
    AttendanceHistoryDBs []*AttendanceHistoryDB
    OpenConditions []*OpenConditionDB
    RepurchasableMonthlyProductCountDBs []*PurchaseCountDB
    MonthlyProductParcel []*ParcelInfo
    MonthlyProductMail []*ParcelInfo
    BiweeklyProductParcel []*ParcelInfo
    BiweeklyProductMail []*ParcelInfo
    WeeklyProductParcel []*ParcelInfo
    WeeklyProductMail []*ParcelInfo
    EncryptedUID string
	AccountRestrictionsDB *AccountRestrictionsDB
	IssueAlertInfos []*IssueAlertInfoDB
}

func (x *AccountAuthResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AccountAuthResponse) ProtoReflect() Message {
	return x
}

func (x *AccountAuthResponse) GetProtocol() int32 {
	return mx.Protocol_Account_Auth
}

func (x *AccountAuthResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

