// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AccountLoginSyncResponse struct {
	*ResponsePacket

	Responses                                *ResponsePacket
	CafeGetInfoResponse                      *CafeGetInfoResponse
	AccountCurrencySyncResponse              *AccountCurrencySyncResponse
	CharacterListResponse                    *CharacterListResponse
	EquipmentItemListResponse                *EquipmentItemListResponse
	CharacterGearListResponse                *CharacterGearListResponse
	ItemListResponse                         *ItemListResponse
	EchelonListResponse                      *EchelonListResponse
	MemoryLobbyListResponse                  *MemoryLobbyListResponse
	CampaignListResponse                     *CampaignListResponse
	ArenaLoginResponse                       *ArenaLoginResponse
	RaidLoginResponse                        *RaidLoginResponse
	EliminateRaidLoginResponse               *EliminateRaidLoginResponse
	CraftInfoListResponse                    *CraftInfoListResponse
	ClanLoginResponse                        *ClanLoginResponse
	MomotalkOutlineResponse                  *MomoTalkOutLineResponse
	ScenarioListResponse                     *ScenarioListResponse
	ShopGachaRecruitListResponse             *ShopGachaRecruitListResponse
	TimeAttackDungeonLoginResponse           *TimeAttackDungeonLoginResponse
	BillingPurchaseListByYostarResponse      *BillingPurchaseListByYostarResponse
	EventContentPermanentListResponse        *EventContentPermanentListResponse
	AttachmentGetResponse                    *AttachmentGetResponse
	AttachmentEmblemListResponse             *AttachmentEmblemListResponse
	ContentSweepMultiSweepPresetListResponse *ContentSweepMultiSweepPresetListResponse
	StickerListResponse                      *StickerLoginResponse
	MultiFloorRaidSyncResponse               *MultiFloorRaidSyncResponse
	FriendCount                              int64
	FriendCode                               string
}

func (x *AccountLoginSyncResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *AccountLoginSyncResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
