// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ArenaEnterLobbyResponse struct{
	message ProtoMessage
	ResponsePacket

    ArenaPlayerInfoDB *ArenaPlayerInfoDB
    OpponentUserDBs []*ArenaUserDB
    MapId int64
    AutoRefreshTime mx.MxTime
}

func (x *ArenaEnterLobbyResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ArenaEnterLobbyResponse) ProtoReflect() Message {
	return x
}

func (x *ArenaEnterLobbyResponse) GetProtocol() int32 {
	return mx.Protocol_Arena_EnterLobby
}

func (x *ArenaEnterLobbyResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

