// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaEnterLobbyResponse struct {
	*ResponsePacket

	ArenaPlayerInfoDB *ArenaPlayerInfoDB
	OpponentUserDBs   []*ArenaUserDB
	MapId             int64
	AutoRefreshTime   mx.MxTime
}

func (x *ArenaEnterLobbyResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaEnterLobbyResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
