// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaHistoryDB struct {
	ArenaBattleDB         *ArenaBattleDB
	BattleEndTime         mx.MxTime
	BattleSummary         *BattleSummary
	AttackingUserDB       *ArenaUserDB
	DefendingUserDB       *ArenaUserDB
	WinnerAccountServerId int64
}

func (x *ArenaHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
