// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ArenaUserDB struct {
	AccountServerId             int64
	RepresentCharacterUniqueId  int64
	RepresentCharacterCostumeId int64
	NickName                    string
	Rank                        int64
	Level                       int64
	Exp                         int64
	TeamSettingDB               *ArenaTeamSettingDB
	AccountAttachmentDB         *AccountAttachmentDB
	UserName                    string
}

func (x *ArenaUserDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
