// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaEnterBattlePart1Request struct {
	*RequestPacket

	OpponentAccountServerId int64
	OpponentRank            int64
	OpponentIndex           int32
}

func (x *ArenaEnterBattlePart1Request) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaEnterBattlePart1Request) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
