// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ArenaSyncEchelonSettingTimeResponse struct{
	message ProtoMessage
	ResponsePacket

    EchelonSettingTime mx.MxTime
}

func (x *ArenaSyncEchelonSettingTimeResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ArenaSyncEchelonSettingTimeResponse) ProtoReflect() Message {
	return x
}

func (x *ArenaSyncEchelonSettingTimeResponse) GetProtocol() int32 {
	return mx.Protocol_Arena_SyncEchelonSettingTime
}

func (x *ArenaSyncEchelonSettingTimeResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

