// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaEnterBattlePart2Response struct {
	*ResponsePacket

	ArenaBattleDB     *ArenaBattleDB
	ArenaPlayerInfoDB *ArenaPlayerInfoDB
	AccountCurrencyDB *AccountCurrencyDB
	VictoryRewards    *ParcelResultDB
	SeasonRewards     *ParcelResultDB
	AllTimeRewards    *ParcelResultDB
}

func (x *ArenaEnterBattlePart2Response) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaEnterBattlePart2Response) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
