// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaRankListRequest struct {
	*RequestPacket

	StartIndex int32
	Count      int32
}

func (x *ArenaRankListRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaRankListRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
