// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaHistoryRequest struct {
	*RequestPacket

	SearchStartDate mx.MxTime
	Count           int32
}

func (x *ArenaHistoryRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaHistoryRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
