// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaCumulativeTimeRewardResponse struct {
	*ResponsePacket

	TimeRewardAmount         int64
	TimeRewardLastUpdateTime mx.MxTime
	ParcelResult             *ParcelResultDB
}

func (x *ArenaCumulativeTimeRewardResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ArenaCumulativeTimeRewardResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
