// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ArenaBattleDB struct {
	ArenaBattleServerId int64
	Season              int64
	Group               int64
	BattleStartTime     mx.MxTime
	BattleEndTime       mx.MxTime
	Seed                int64
	AttackingUserDB     *ArenaUserDB
	DefendingUserDB     *ArenaUserDB
	BattleSummary       *BattleSummary
}

func (x *ArenaBattleDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
