// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ArenaEnterLobbyRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ArenaEnterLobbyRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ArenaEnterLobbyRequest) ProtoReflect() Message {
	return x
}

func (x *ArenaEnterLobbyRequest) GetProtocol() int32 {
	return mx.Protocol_Arena_EnterLobby
}

func (x *ArenaEnterLobbyRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

