// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ArenaEnterBattlePart1Request struct{
	message ProtoMessage
	RequestPacket

    OpponentAccountServerId int64
    OpponentRank int64
    OpponentIndex int32
}

func (x *ArenaEnterBattlePart1Request) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ArenaEnterBattlePart1Request) ProtoReflect() Message {
	return x
}

func (x *ArenaEnterBattlePart1Request) GetProtocol() int32 {
	return mx.Protocol_Arena_EnterBattlePart1
}

func (x *ArenaEnterBattlePart1Request) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

