// Code generated by gucooing DO NOT EDIT.

package proto

type AssistCharacterDB struct{
    *CharacterDB
    EchelonType EchelonType
    SlotNumber int32
    AccountId int64
    AssistRelation AssistRelation
    AssistCharacterServerId int64
    NickName string
    EquipmentDBs []*EquipmentDB
    WeaponDB *WeaponDB
    GearDB *GearDB
    CostumeId int64
    CostumeDB *CostumeDB
    IsMulligan bool
    IsTSAInteraction bool
    CombatStyleIndex int32
}

