// Code generated by gucooing DO NOT EDIT.

package proto

type AssistRelation int32

const (
	AssistRelation_None     = 0
	AssistRelation_Clan     = 1
	AssistRelation_Friend   = 2
	AssistRelation_Cheat    = 4
	AssistRelation_Stranger = 8
)

var (
	AssistRelation_name = map[int32]string{
		0: "None",
		1: "Clan",
		2: "Friend",
		4: "Cheat",
		8: "Stranger",
	}
	AssistRelation_value = map[string]int32{
		"None":     0,
		"Clan":     1,
		"Friend":   2,
		"Cheat":    4,
		"Stranger": 8,
	}
)

func (x AssistRelation) String() string {
	return AssistRelation_name[int32(x)]
}
