// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type AssistRelation int32

const (
	AssistRelation_None     AssistRelation = 0
	AssistRelation_Clan     AssistRelation = 1
	AssistRelation_Friend   AssistRelation = 2
	AssistRelation_Cheat    AssistRelation = 4
	AssistRelation_Stranger AssistRelation = 8
)

var (
	AssistRelation_name = map[int32]string{
		0: "None",
		1: "Clan",
		2: "Friend",
		4: "Cheat",
		8: "Stranger",
	}
	AssistRelation_value = map[string]int32{
		"None":     0,
		"Clan":     1,
		"Friend":   2,
		"Cheat":    4,
		"Stranger": 8,
	}
)

func (x AssistRelation) String() string {
	return AssistRelation_name[int32(x)]
}

func (x AssistRelation) Value(sr string) AssistRelation {
	return AssistRelation(AssistRelation_value[sr])
}
