// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AssistCharacterDB struct {
	*CharacterDB

	EchelonType             EchelonType
	SlotNumber              int32
	AccountId               int64
	AssistRelation          AssistRelation
	AssistCharacterServerId int64
	NickName                string
	EquipmentDBs            []*EquipmentDB
	WeaponDB                *WeaponDB
	GearDB                  *GearDB
	CostumeId               int64
	CostumeDB               *CostumeDB
	IsMulligan              bool
	IsTSAInteraction        bool
	CombatStyleIndex        int32
	HasWeapon               bool
	HasGear                 bool
}

func (x *AssistCharacterDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *AssistCharacterDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.CharacterDB = packet.(*CharacterDB)
}
