// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AttachmentEmblemAcquireRequest struct{
	message ProtoMessage
	RequestPacket

    UniqueIds []int64
}

func (x *AttachmentEmblemAcquireRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AttachmentEmblemAcquireRequest) ProtoReflect() Message {
	return x
}

func (x *AttachmentEmblemAcquireRequest) GetProtocol() int32 {
	return mx.Protocol_Attachment_EmblemAcquire
}

func (x *AttachmentEmblemAcquireRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

