// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type AttendanceType int32

const (
	AttendanceType_Basic          AttendanceType = 0
	AttendanceType_Event          AttendanceType = 1
	AttendanceType_Newbie         AttendanceType = 2
	AttendanceType_EventCountDown AttendanceType = 3
	AttendanceType_Event20Days    AttendanceType = 4
)

var (
	AttendanceType_name = map[int32]string{
		0: "Basic",
		1: "Event",
		2: "Newbie",
		3: "EventCountDown",
		4: "Event20Days",
	}
	AttendanceType_value = map[string]int32{
		"Basic":          0,
		"Event":          1,
		"Newbie":         2,
		"EventCountDown": 3,
		"Event20Days":    4,
	}
)

func (x AttendanceType) String() string {
	return AttendanceType_name[int32(x)]
}

func (x AttendanceType) Value(sr string) AttendanceType {
	return AttendanceType(AttendanceType_value[sr])
}
