// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type AttendanceBookReward struct{
    UniqueId int64
    Type AttendanceType
    AccountType AccountState
    DisplayOrder int64
    AccountLevelLimit int64
    Title string
    TitleImagePath string
    CountRule AttendanceCountRule
    CountReset AttendanceResetType
    BookSize int64
    StartDate mx.MxTime
    StartableEndDate mx.MxTime
    EndDate mx.MxTime
    ExpiryDate int64
    MailType MailType
    DailyRewardIcons map[int64]string
    DailyRewards map[int64][]*ParcelInfo
}

