// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AttendanceBookReward struct {
	UniqueId          int64
	Type              AttendanceType
	AccountType       AccountState
	DisplayOrder      int64
	AccountLevelLimit int64
	Title             string
	TitleImagePath    string
	CountRule         AttendanceCountRule
	CountReset        AttendanceResetType
	BookSize          int64
	StartDate         mx.MxTime
	StartableEndDate  mx.MxTime
	EndDate           mx.MxTime
	ExpiryDate        int64
	MailType          MailType
	DailyRewardIcons  map[int64]string
	DailyRewards      map[int64][]*ParcelInfo
}

func (x *AttendanceBookReward) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
