// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type AttendanceRewardResponse struct{
	message ProtoMessage
	ResponsePacket

    AttendanceBookRewards []*AttendanceBookReward
    AttendanceHistoryDBs []*AttendanceHistoryDB
    ParcelResultDB *ParcelResultDB
}

func (x *AttendanceRewardResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *AttendanceRewardResponse) ProtoReflect() Message {
	return x
}

func (x *AttendanceRewardResponse) GetProtocol() int32 {
	return mx.Protocol_Attendance_Reward
}

func (x *AttendanceRewardResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

