// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type AttendanceHistoryDB struct {
	ServerId               int64
	AttendanceBookUniqueId int64
	AttendedDay            map[int64]mx.MxTime
	Expired                bool
	LastAttendedDay        int64
	LastAttendedDate       mx.MxTime
	AttendedDayNullable    map[int64]mx.MxTime
}

func (x *AttendanceHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
