// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type Attribute struct {
	TypeId *Object
}

func (x *Attribute) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *Attribute) SetPacket(packet mx.Message) {

}
