// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type BasePacket struct {
	SessionKey *SessionKey
	Protocol   Protocol
	AccountId  int64
}

func (x *BasePacket) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *BasePacket) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	base := packet.(*BasePacket)
	x.Protocol = base.Protocol
	x.SessionKey = base.SessionKey
	x.AccountId = base.AccountId
}
