// Code generated by gucooing DO NOT EDIT.

package proto

type BattleEntityType string

const (
    BattleEntityType_None = 0
    BattleEntityType_Character = 16777216
    BattleEntityType_SkillActor = 33554432
    BattleEntityType_Obstacle = 67108864
    BattleEntityType_Point = 134217728
    BattleEntityType_Projectile = 268435456
    BattleEntityType_EffectArea = 536870912
    BattleEntityType_Supporter = 1073741824
)

var (
    BattleEntityType_name = map[int32]string{
      0 : "None",
      16777216 : "Character",
      33554432 : "SkillActor",
      67108864 : "Obstacle",
      134217728 : "Point",
      268435456 : "Projectile",
      536870912 : "EffectArea",
      1073741824 : "Supporter",
   }
    BattleEntityType_value = map[string]int32{
      "None" : 0,
      "Character" : 16777216,
      "SkillActor" : 33554432,
      "Obstacle" : 67108864,
      "Point" : 134217728,
      "Projectile" : 268435456,
      "EffectArea" : 536870912,
      "Supporter" : 1073741824,
   }
)

func (x BattleEntityType) String() string {
  return string(x)
}

