// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type BattleNumericLog struct {
	EntityType            string
	Category              BattleLogCategory
	Source                BattleLogSourceType
	CalculatedSum         int64
	AppliedSum            int64
	Count                 int64
	CriticalMultiplierMax int64
	CriticalCount         int64
	CalculatedMin         int64
	CalculatedMax         int64
	AppliedMin            int64
	AppliedMax            int64
}

func (x *BattleNumericLog) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
