// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type BattleSummary struct {
	HashKey            int64
	IsBossBattle       bool
	BattleType         BattleTypes
	StageId            int64
	GroundId           int64
	Winner             string
	IsPlayerWin        bool
	EndType            BattleEndType
	EndFrame           int32
	Group01Summary     *GroupSummary
	Group02Summary     *GroupSummary
	WeekDungeonSummary *WeekDungeonSummary
	RaidSummary        *RaidSummary
	TouchCountSummary  *ExcessiveTouch
	ArenaSummary       *ArenaSummary
	EndTime            *TimeSpan
	ContinueCount      int32
	ElapsedRealtime    float32
	FindGiftClearText  string
	EventContentId     int64
	FixedEchelonId     int64
	IsAbort            bool
	IsDefeatBattle     bool
	IsDefeatFailure    bool
}

func (x *BattleSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
