// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type BattleLogSourceType int32

const (
	BattleLogSourceType_None         BattleLogSourceType = 0
	BattleLogSourceType_Normal       BattleLogSourceType = 1
	BattleLogSourceType_Ex           BattleLogSourceType = 2
	BattleLogSourceType_Public       BattleLogSourceType = 3
	BattleLogSourceType_Passive      BattleLogSourceType = 4
	BattleLogSourceType_ExtraPassive BattleLogSourceType = 5
	BattleLogSourceType_Etc          BattleLogSourceType = 6
)

var (
	BattleLogSourceType_name = map[int32]string{
		0: "None",
		1: "Normal",
		2: "Ex",
		3: "Public",
		4: "Passive",
		5: "ExtraPassive",
		6: "Etc",
	}
	BattleLogSourceType_value = map[string]int32{
		"None":         0,
		"Normal":       1,
		"Ex":           2,
		"Public":       3,
		"Passive":      4,
		"ExtraPassive": 5,
		"Etc":          6,
	}
)

func (x BattleLogSourceType) String() string {
	return BattleLogSourceType_name[int32(x)]
}

func (x BattleLogSourceType) Value(sr string) BattleLogSourceType {
	return BattleLogSourceType(BattleLogSourceType_value[sr])
}
