// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type BillingTransactionStartByYostarResponse struct {
	*ResponsePacket

	PurchaseCount             int64
	PurchaseResetDate         mx.MxTime
	PurchaseOrderId           int64
	MXSeedKey                 string
	PurchaseServerTag         PurchaseServerTag
	PurchaseServerCallbackUrl string
}

func (x *BillingTransactionStartByYostarResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *BillingTransactionStartByYostarResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
