// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"time"
)

type BlockedProductDB struct {
	CashProductId   int64
	MarketBlockType ShopCashBlockType
	BeginDate       time.Time
	EndDate         time.Time
}
