// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeProductionDB struct {
	CafeDBId              int64
	ComfortValue          int64
	AppliedDate           mx.MxTime
	ProductionParcelInfos []*CafeProductionParcelInfo
}

func (x *CafeProductionDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
