// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type CafePresetDB struct {
	ServerId   int64
	SlotId     int32
	PresetName string
	IsEmpty    bool
}

func (x *CafePresetDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
