// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeOpenRequest struct{
	message ProtoMessage
	RequestPacket

    CafeId int64
}

func (x *CafeOpenRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeOpenRequest) ProtoReflect() Message {
	return x
}

func (x *CafeOpenRequest) GetProtocol() int32 {
	return mx.Protocol_Cafe_Open
}

func (x *CafeOpenRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

