// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeReceiveCurrencyResponse struct{
	message ProtoMessage
	ResponsePacket

    CafeDB *CafeDB
    CafeDBs []*CafeDB
    ParcelResultDB *ParcelResultDB
}

func (x *CafeReceiveCurrencyResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeReceiveCurrencyResponse) ProtoReflect() Message {
	return x
}

func (x *CafeReceiveCurrencyResponse) GetProtocol() int32 {
	return mx.Protocol_Cafe_ReceiveCurrency
}

func (x *CafeReceiveCurrencyResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

