// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeGiveGiftRequest struct {
	*RequestPacket

	CafeDBId          int64
	CharacterUniqueId int64
	ConsumeRequestDB  *ConsumeRequestDB
}

func (x *CafeGiveGiftRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeGiveGiftRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
