// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeAckResponse struct{
	message ProtoMessage
	ResponsePacket

    CafeDB *CafeDB
}

func (x *CafeAckResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeAckResponse) ProtoReflect() Message {
	return x
}

func (x *CafeAckResponse) GetProtocol() int32 {
	return mx.Protocol_Cafe_Ack
}

func (x *CafeAckResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

