// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeInteractWithCharacterRequest struct {
	*RequestPacket

	CafeDBId    int64
	CharacterId int64
}

func (x *CafeInteractWithCharacterRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeInteractWithCharacterRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
