// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeUpdatePresetFurnitureRequest struct {
	*RequestPacket

	CafeDBId int64
	SlotId   int32
}

func (x *CafeUpdatePresetFurnitureRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeUpdatePresetFurnitureRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
