// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeInteractWithCharacterResponse struct{
	message ProtoMessage
	ResponsePacket

    CafeDB *CafeDB
    CharacterDB *CharacterDB
    ParcelResultDB *ParcelResultDB
}

func (x *CafeInteractWithCharacterResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeInteractWithCharacterResponse) ProtoReflect() Message {
	return x
}

func (x *CafeInteractWithCharacterResponse) GetProtocol() int32 {
	return mx.Protocol_Cafe_Interact
}

func (x *CafeInteractWithCharacterResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

