// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeTrophyHistoryResponse struct {
	*ResponsePacket

	RaidSeasonRankingHistoryDBs []*RaidSeasonRankingHistoryDB
}

func (x *CafeTrophyHistoryResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeTrophyHistoryResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
