// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeGiveGiftResponse struct{
	message ProtoMessage
	ResponsePacket

    ParcelResultDB *ParcelResultDB
    ConsumeResultDB *ConsumeResultDB
}

func (x *CafeGiveGiftResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeGiveGiftResponse) ProtoReflect() Message {
	return x
}

func (x *CafeGiveGiftResponse) GetProtocol() int32 {
	return mx.Protocol_Cafe_GiveGift
}

func (x *CafeGiveGiftResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

