// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeOpenResponse struct{
	message ProtoMessage
	ResponsePacket

    OpenedCafeDB *CafeDB
    FurnitureDBs []*FurnitureDB
}

func (x *CafeOpenResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeOpenResponse) ProtoReflect() Message {
	return x
}

func (x *CafeOpenResponse) GetProtocol() int32 {
	return mx.Protocol_Cafe_Open
}

func (x *CafeOpenResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

