// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeGetInfoResponse struct {
	*ResponsePacket

	CafeDB       *CafeDB
	CafeDBs      []*CafeDB
	FurnitureDBs []*FurnitureDB
}

func (x *CafeGetInfoResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeGetInfoResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
