// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeSummonCharacterRequest struct{
	message ProtoMessage
	RequestPacket

    CafeDBId int64
    CharacterServerId int64
}

func (x *CafeSummonCharacterRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeSummonCharacterRequest) ProtoReflect() Message {
	return x
}

func (x *CafeSummonCharacterRequest) GetProtocol() int32 {
	return mx.Protocol_Cafe_SummonCharacter
}

func (x *CafeSummonCharacterRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

