// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeSummonCharacterResponse struct {
	*ResponsePacket

	CafeDB  *CafeDB
	CafeDBs []*CafeDB
}

func (x *CafeSummonCharacterResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeSummonCharacterResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
