// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CafeListPresetRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *CafeListPresetRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CafeListPresetRequest) ProtoReflect() Message {
	return x
}

func (x *CafeListPresetRequest) GetProtocol() int32 {
	return mx.Protocol_Cafe_ListPreset
}

func (x *CafeListPresetRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

