// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type CafeProductionParcelInfo struct {
	Key    *ParcelKeyPair
	Amount int64
}

func (x *CafeProductionParcelInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
