// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CafeCharacterDB struct {
	*VisitingCharacterDB

	IsSummon         bool
	LastInteractTime mx.MxTime
}

func (x *CafeCharacterDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CafeCharacterDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.VisitingCharacterDB = packet.(*VisitingCharacterDB)
}
