// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type CallingConventions int32

const (
	CallingConventions_Standard     CallingConventions = 1
	CallingConventions_VarArgs      CallingConventions = 2
	CallingConventions_Any          CallingConventions = 3
	CallingConventions_HasThis      CallingConventions = 32
	CallingConventions_ExplicitThis CallingConventions = 64
)

var (
	CallingConventions_name = map[int32]string{
		1:  "Standard",
		2:  "VarArgs",
		3:  "Any",
		32: "HasThis",
		64: "ExplicitThis",
	}
	CallingConventions_value = map[string]int32{
		"Standard":     1,
		"VarArgs":      2,
		"Any":          3,
		"HasThis":      32,
		"ExplicitThis": 64,
	}
)

func (x CallingConventions) String() string {
	return CallingConventions_name[int32(x)]
}

func (x CallingConventions) Value(sr string) CallingConventions {
	return CallingConventions(CallingConventions_value[sr])
}
