// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignTutorialStageResultResponse struct {
	*ResponsePacket

	CampaignStageHistoryDB *CampaignStageHistoryDB
	ParcelResultDB         *ParcelResultDB
	ClearReward            []*ParcelInfo
	FirstClearReward       []*ParcelInfo
}

func (x *CampaignTutorialStageResultResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignTutorialStageResultResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
