// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignTacticResultResponse struct {
	*ResponsePacket

	TacticRank             int64
	CampaignStageHistoryDB *CampaignStageHistoryDB
	LevelUpCharacterDBs    []*CharacterDB
	FirstClearReward       []*ParcelInfo
	ThreeStarReward        []*ParcelInfo
	StrategyObject         *Strategy
	StrategyObjectRewards  map[int64][]*ParcelInfo
	ParcelResultDB         *ParcelResultDB
	SaveDataDB             *CampaignMainStageSaveDB
}

func (x *CampaignTacticResultResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignTacticResultResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
