// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type CampaignEndBattle int32

const (
	CampaignEndBattle_None CampaignEndBattle = 0
	CampaignEndBattle_Win  CampaignEndBattle = 1
	CampaignEndBattle_Lose CampaignEndBattle = 2
)

var (
	CampaignEndBattle_name = map[int32]string{
		0: "None",
		1: "Win",
		2: "Lose",
	}
	CampaignEndBattle_value = map[string]int32{
		"None": 0,
		"Win":  1,
		"Lose": 2,
	}
)

func (x CampaignEndBattle) String() string {
	return CampaignEndBattle_name[int32(x)]
}

func (x CampaignEndBattle) Value(sr string) CampaignEndBattle {
	return CampaignEndBattle(CampaignEndBattle_value[sr])
}
