// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CampaignChapterClearRewardRequest struct{
	message ProtoMessage
	RequestPacket

    CampaignChapterUniqueId int64
    StageDifficulty *StageDifficulty
}

func (x *CampaignChapterClearRewardRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CampaignChapterClearRewardRequest) ProtoReflect() Message {
	return x
}

func (x *CampaignChapterClearRewardRequest) GetProtocol() int32 {
	return mx.Protocol_Campaign_ChapterClearReward
}

func (x *CampaignChapterClearRewardRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

