// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignChapterClearRewardRequest struct {
	*RequestPacket

	CampaignChapterUniqueId int64
	StageDifficulty         StageDifficulty
}

func (x *CampaignChapterClearRewardRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignChapterClearRewardRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
