// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignWithdrawEchelonResponse struct {
	*ResponsePacket

	SaveDataDB         *CampaignMainStageSaveDB
	WithdrawEchelonDBs []*EchelonDB
}

func (x *CampaignWithdrawEchelonResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignWithdrawEchelonResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
