// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignMainStageSaveDB struct {
	*ContentSaveDB

	ContentType                      ContentType
	CampaignState                    CampaignState
	CurrentTurn                      int32
	EnemyClearCount                  int32
	LastEnemyEntityId                int32
	TacticRankSCount                 int32
	EnemyInfos                       map[int64]*HexaUnit
	EchelonInfos                     map[int64]*HexaUnit
	WithdrawInfos                    map[int64][]int64
	StrategyObjects                  map[int64]*Strategy
	StrategyObjectRewards            map[int64][]*ParcelInfo
	StrategyObjectHistory            []int64
	ActivatedHexaEventsAndConditions map[int64][]int64
	HexaEventDelayedExecutions       map[int64][]int64
	TileMapStates                    map[int32]*HexaTileState
	DisplayInfos                     []*HexaDisplayInfo
	DeployedEchelonInfos             []*HexaUnit
}

func (x *CampaignMainStageSaveDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignMainStageSaveDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ContentSaveDB = packet.(*ContentSaveDB)
}
