// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type CampaignMainStageSaveDB struct{
    ContentType ContentType
    CampaignState CampaignState
    CurrentTurn int32
    EnemyClearCount int32
    LastEnemyEntityId int32
    TacticRankSCount int32
    EnemyInfos map[int64]*HexaUnit
    EchelonInfos map[int64]*HexaUnit
    WithdrawInfos map[int64][]int64
    StrategyObjects map[int64]*Strategy
    StrategyObjectRewards map[int64][]*ParcelInfo
    StrategyObjectHistory []int64
    ActivatedHexaEventsAndConditions map[int64][]int64
    HexaEventDelayedExecutions map[int64][]int64
    TileMapStates map[int32]*HexaTileState
    DisplayInfos []*HexaDisplayInfo
    DeployedEchelonInfos []*HexaUnit
    StageEntranceFee []*ParcelInfo
    CreateTime mx.MxTime
    StageUniqueId int64
    AccountServerId int64
    EnemyKillCountByUniqueId map[int64]int64
}

