// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignConfirmMainStageResponse struct {
	*ResponsePacket

	ParcelResultDB *ParcelResultDB
	SaveDataDB     *CampaignMainStageSaveDB
}

func (x *CampaignConfirmMainStageResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignConfirmMainStageResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
