// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignHealRequest struct {
	*RequestPacket

	CampaignStageUniqueId int64
	EchelonIndex          int64
	CharacterServerId     int64
}

func (x *CampaignHealRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignHealRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
