// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CampaignChapterClearRewardResponse struct {
	*ResponsePacket

	CampaignChapterClearRewardHistoryDB *CampaignChapterClearRewardHistoryDB
	ParcelResultDB                      *ParcelResultDB
}

func (x *CampaignChapterClearRewardResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignChapterClearRewardResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
