// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterBatchSkillLevelUpdateResponse struct{
	message ProtoMessage
	ResponsePacket

    CharacterDB *CharacterDB
    ParcelResultDB *ParcelResultDB
}

func (x *CharacterBatchSkillLevelUpdateResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterBatchSkillLevelUpdateResponse) ProtoReflect() Message {
	return x
}

func (x *CharacterBatchSkillLevelUpdateResponse) GetProtocol() int32 {
	return mx.Protocol_Character_BatchSkillLevelUpdate
}

func (x *CharacterBatchSkillLevelUpdateResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

