// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterWeaponExpGrowthRequest struct{
	message ProtoMessage
	RequestPacket

    TargetCharacterServerId int64
    ConsumeUniqueIdAndCounts map[int64]int64
}

func (x *CharacterWeaponExpGrowthRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterWeaponExpGrowthRequest) ProtoReflect() Message {
	return x
}

func (x *CharacterWeaponExpGrowthRequest) GetProtocol() int32 {
	return mx.Protocol_Character_WeaponExpGrowth
}

func (x *CharacterWeaponExpGrowthRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

