// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterBatchSkillLevelUpdateRequest struct{
	message ProtoMessage
	RequestPacket

    TargetCharacterDBId int64
    SkillLevelUpdateRequestDBs []*SkillLevelBatchGrowthRequestDB
}

func (x *CharacterBatchSkillLevelUpdateRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterBatchSkillLevelUpdateRequest) ProtoReflect() Message {
	return x
}

func (x *CharacterBatchSkillLevelUpdateRequest) GetProtocol() int32 {
	return mx.Protocol_Character_BatchSkillLevelUpdate
}

func (x *CharacterBatchSkillLevelUpdateRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

