// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterSetFavoritesRequest struct{
	message ProtoMessage
	RequestPacket

    ActivateByServerIds map[int64]bool
}

func (x *CharacterSetFavoritesRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterSetFavoritesRequest) ProtoReflect() Message {
	return x
}

func (x *CharacterSetFavoritesRequest) GetProtocol() int32 {
	return mx.Protocol_Character_SetFavorites
}

func (x *CharacterSetFavoritesRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

