// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterBatchSkillLevelUpdateResponse struct {
	*ResponsePacket

	CharacterDB    *CharacterDB
	ParcelResultDB *ParcelResultDB
}

func (x *CharacterBatchSkillLevelUpdateResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterBatchSkillLevelUpdateResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
