// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterGearUnlockResponse struct {
	*ResponsePacket

	GearDB      *GearDB
	CharacterDB *CharacterDB
}

func (x *CharacterGearUnlockResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterGearUnlockResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
