// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterListResponse struct {
	*ResponsePacket

	CharacterDBs    []*CharacterDB
	TSSCharacterDBs []*CharacterDB
	WeaponDBs       []*WeaponDB
	CostumeDBs      []*CostumeDB
}

func (x *CharacterListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
