// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterGearUnlockResponse struct{
	message ProtoMessage
	ResponsePacket

    GearDB *GearDB
    CharacterDB *CharacterDB
}

func (x *CharacterGearUnlockResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterGearUnlockResponse) ProtoReflect() Message {
	return x
}

func (x *CharacterGearUnlockResponse) GetProtocol() int32 {
	return mx.Protocol_CharacterGear_Unlock
}

func (x *CharacterGearUnlockResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

