// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterGearTierUpRequest struct {
	*RequestPacket

	GearServerId int64
	ReplaceInfos []*SelectTicketReplaceInfo
}

func (x *CharacterGearTierUpRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterGearTierUpRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
