// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterGearUnlockRequest struct {
	*RequestPacket

	CharacterServerId int64
	SlotIndex         int32
}

func (x *CharacterGearUnlockRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterGearUnlockRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
