// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterWeaponExpGrowthResponse struct{
	message ProtoMessage
	ResponsePacket

    ParcelResultDB *ParcelResultDB
}

func (x *CharacterWeaponExpGrowthResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterWeaponExpGrowthResponse) ProtoReflect() Message {
	return x
}

func (x *CharacterWeaponExpGrowthResponse) GetProtocol() int32 {
	return mx.Protocol_Character_WeaponExpGrowth
}

func (x *CharacterWeaponExpGrowthResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

