// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterSetCostumeResponse struct {
	*ResponsePacket

	SetCostumeDB   *CostumeDB
	UnsetCostumeDB *CostumeDB
}

func (x *CharacterSetCostumeResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterSetCostumeResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
