// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterFavorGrowthRequest struct {
	*RequestPacket

	TargetCharacterDBId       int64
	ConsumeItemDBIdsAndCounts map[int64]int32
}

func (x *CharacterFavorGrowthRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterFavorGrowthRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
