// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterWeaponExpGrowthRequest struct {
	*RequestPacket

	TargetCharacterServerId  int64
	ConsumeUniqueIdAndCounts map[int64]int64
}

func (x *CharacterWeaponExpGrowthRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterWeaponExpGrowthRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
