// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CharacterBatchSkillLevelUpdateRequest struct {
	*RequestPacket

	TargetCharacterDBId        int64
	SkillLevelUpdateRequestDBs []*SkillLevelBatchGrowthRequestDB
}

func (x *CharacterBatchSkillLevelUpdateRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CharacterBatchSkillLevelUpdateRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
