// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterSkillLevelUpdateRequest struct{
	message ProtoMessage
	RequestPacket

    TargetCharacterDBId int64
    SkillSlot string
    Level int32
    ReplaceInfos []*SelectTicketReplaceInfo
}

func (x *CharacterSkillLevelUpdateRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterSkillLevelUpdateRequest) ProtoReflect() Message {
	return x
}

func (x *CharacterSkillLevelUpdateRequest) GetProtocol() int32 {
	return mx.Protocol_Character_UpdateSkillLevel
}

func (x *CharacterSkillLevelUpdateRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

