// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterSetFavoritesResponse struct{
	message ProtoMessage
	ResponsePacket

    CharacterDBs []*CharacterDB
}

func (x *CharacterSetFavoritesResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterSetFavoritesResponse) ProtoReflect() Message {
	return x
}

func (x *CharacterSetFavoritesResponse) GetProtocol() int32 {
	return mx.Protocol_Character_SetFavorites
}

func (x *CharacterSetFavoritesResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

