// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterWeaponTranscendenceRequest struct{
	message ProtoMessage
	RequestPacket

    TargetCharacterServerId int64
}

func (x *CharacterWeaponTranscendenceRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterWeaponTranscendenceRequest) ProtoReflect() Message {
	return x
}

func (x *CharacterWeaponTranscendenceRequest) GetProtocol() int32 {
	return mx.Protocol_Character_WeaponTranscendence
}

func (x *CharacterWeaponTranscendenceRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

