// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type CharacterListResponse struct{
	message ProtoMessage
	ResponsePacket

    CharacterDBs []*CharacterDB
    TSSCharacterDBs []*CharacterDB
    WeaponDBs []*WeaponDB
    CostumeDBs []*CostumeDB
}

func (x *CharacterListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *CharacterListResponse) ProtoReflect() Message {
	return x
}

func (x *CharacterListResponse) GetProtocol() int32 {
	return mx.Protocol_Character_List
}

func (x *CharacterListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

