// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ClanConferResponse struct {
	*ResponsePacket

	ClanMemberDB            *ClanMemberDB
	AccountClanMemberDB     *ClanMemberDB
	ClanDB                  *ClanDB
	ClanMemberDescriptionDB *ClanMemberDescriptionDB
}

func (x *ClanConferResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ClanConferResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
