// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanMyAssistListResponse struct{
	message ProtoMessage
	ResponsePacket

    ClanAssistSlotDBs []*ClanAssistSlotDB
}

func (x *ClanMyAssistListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanMyAssistListResponse) ProtoReflect() Message {
	return x
}

func (x *ClanMyAssistListResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_MyAssistList
}

func (x *ClanMyAssistListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

