// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ClanAssistSlotDB struct {
	EchelonType      EchelonType
	SlotNumber       int64
	CharacterDBId    int64
	DeployDate       mx.MxTime
	TotalRentCount   int64
	CombatStyleIndex int32
}

func (x *ClanAssistSlotDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
