// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ClanSocialGrade int32

const (
	ClanSocialGrade_None            ClanSocialGrade = 0
	ClanSocialGrade_President       ClanSocialGrade = 1
	ClanSocialGrade_Manager         ClanSocialGrade = 2
	ClanSocialGrade_Member          ClanSocialGrade = 3
	ClanSocialGrade_Applicant       ClanSocialGrade = 4
	ClanSocialGrade_Refused         ClanSocialGrade = 5
	ClanSocialGrade_Kicked          ClanSocialGrade = 6
	ClanSocialGrade_Quit            ClanSocialGrade = 7
	ClanSocialGrade_VicePredisident ClanSocialGrade = 8
)

var (
	ClanSocialGrade_name = map[int32]string{
		0: "None",
		1: "President",
		2: "Manager",
		3: "Member",
		4: "Applicant",
		5: "Refused",
		6: "Kicked",
		7: "Quit",
		8: "VicePredisident",
	}
	ClanSocialGrade_value = map[string]int32{
		"None":            0,
		"President":       1,
		"Manager":         2,
		"Member":          3,
		"Applicant":       4,
		"Refused":         5,
		"Kicked":          6,
		"Quit":            7,
		"VicePredisident": 8,
	}
)

func (x ClanSocialGrade) String() string {
	return ClanSocialGrade_name[int32(x)]
}

func (x ClanSocialGrade) Value(sr string) ClanSocialGrade {
	return ClanSocialGrade(ClanSocialGrade_value[sr])
}
