// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanApplicantRequest struct{
	message ProtoMessage
	RequestPacket

    OffSet int64
}

func (x *ClanApplicantRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanApplicantRequest) ProtoReflect() Message {
	return x
}

func (x *ClanApplicantRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_Applicant
}

func (x *ClanApplicantRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

