// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanQuitResponse struct{
	message ProtoMessage
	ResponsePacket

    
}

func (x *ClanQuitResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanQuitResponse) ProtoReflect() Message {
	return x
}

func (x *ClanQuitResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_Quit
}

func (x *ClanQuitResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

