// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanCheckRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ClanCheckRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanCheckRequest) ProtoReflect() Message {
	return x
}

func (x *ClanCheckRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_Check
}

func (x *ClanCheckRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

