// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanPermitResponse struct{
	message ProtoMessage
	ResponsePacket

    ClanDB *ClanDB
    ClanMemberDB *ClanMemberDB
}

func (x *ClanPermitResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanPermitResponse) ProtoReflect() Message {
	return x
}

func (x *ClanPermitResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_Permit
}

func (x *ClanPermitResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

