// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanSetAssistRequest struct{
	message ProtoMessage
	RequestPacket

    EchelonType EchelonType
    SlotNumber int32
    CharacterDBId int64
    CombatStyleIndex int32
}

func (x *ClanSetAssistRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanSetAssistRequest) ProtoReflect() Message {
	return x
}

func (x *ClanSetAssistRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_SetAssist
}

func (x *ClanSetAssistRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

