// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ClanAssistUseInfo struct {
	CharacterAccountId   int64
	CharacterDBId        int64
	EchelonType          EchelonType
	SlotNumber           int32
	AssistRelation       AssistRelation
	EchelonSlotType      int32
	EchelonSlotIndex     int32
	CombatStyleIndex     int32
	DecodedShardId       int64
	DecodedCharacterDBId int64
	IsMulligan           bool
	IsTSAInteraction     bool
}

func (x *ClanAssistUseInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
