// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanConferResponse struct{
	message ProtoMessage
	ResponsePacket

    ClanMemberDB *ClanMemberDB
    AccountClanMemberDB *ClanMemberDB
    ClanDB *ClanDB
    ClanMemberDescriptionDB *ClanMemberDescriptionDB
}

func (x *ClanConferResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanConferResponse) ProtoReflect() Message {
	return x
}

func (x *ClanConferResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_Confer
}

func (x *ClanConferResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

