// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanAutoJoinRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ClanAutoJoinRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanAutoJoinRequest) ProtoReflect() Message {
	return x
}

func (x *ClanAutoJoinRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_AutoJoin
}

func (x *ClanAutoJoinRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

