// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type ClanAssistRewardInfo struct{
    CharacterDBId int64
    DeployDate mx.MxTime
    RentCount int64
    CumultativeRewardParcels []*ParcelInfo
    RentRewardParcels []*ParcelInfo
}

