// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanKickResponse struct{
	message ProtoMessage
	ResponsePacket

    
}

func (x *ClanKickResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanKickResponse) ProtoReflect() Message {
	return x
}

func (x *ClanKickResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_Kick
}

func (x *ClanKickResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

