// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanMemberListResponse struct{
	message ProtoMessage
	ResponsePacket

    ClanDB *ClanDB
    ClanMemberDBs []*ClanMemberDB
}

func (x *ClanMemberListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanMemberListResponse) ProtoReflect() Message {
	return x
}

func (x *ClanMemberListResponse) GetProtocol() int32 {
	return mx.Protocol_Clan_MemberList
}

func (x *ClanMemberListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

