// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ClanMemberDescriptionDB struct {
	Exp                       int64
	Comment                   string
	CollectedCharactersCount  int32
	ArenaSeasonBestRanking    int64
	ArenaSeasonCurrentRanking int64
}

func (x *ClanMemberDescriptionDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
