// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanKickRequest struct{
	message ProtoMessage
	RequestPacket

    MemberAccountId int64
}

func (x *ClanKickRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanKickRequest) ProtoReflect() Message {
	return x
}

func (x *ClanKickRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_Kick
}

func (x *ClanKickRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

