// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ClanConferRequest struct {
	*RequestPacket

	MemberAccountId int64
	ConferingGrade  ClanSocialGrade
}

func (x *ClanConferRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ClanConferRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
