// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type ClanAssistRentHistoryDB struct{
    AssistCharacterAccountId int64
    AssistCharacterDBId int64
    RentDate mx.MxTime
    AssistCharacterId int64
}

