// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ClanChatLogRequest struct {
	*RequestPacket

	Channel  string
	FromDate mx.MxTime
}

func (x *ClanChatLogRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ClanChatLogRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
