// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ClanMemberRequest struct{
	message ProtoMessage
	RequestPacket

    ClanDBId int64
    MemberAccountId int64
}

func (x *ClanMemberRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ClanMemberRequest) ProtoReflect() Message {
	return x
}

func (x *ClanMemberRequest) GetProtocol() int32 {
	return mx.Protocol_Clan_Member
}

func (x *ClanMemberRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

