// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CommonCheatRequest struct {
	*RequestPacket

	Cheat                 string
	CharacterCustomPreset []*CheatCharacterCustomPreset
}

func (x *CommonCheatRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CommonCheatRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
