// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CommonCheatResponse struct {
	*ResponsePacket

	Account                 *AccountDB
	AccountCurrency         *AccountCurrencyDB
	CharacterDBs            []*CharacterDB
	EquipmentDBs            []*EquipmentDB
	WeaponDBs               []*WeaponDB
	GearDBs                 []*GearDB
	CostumeDBs              []*CostumeDB
	ItemDBs                 []*ItemDB
	ScenarioHistoryDBs      []*ScenarioHistoryDB
	ScenarioGroupHistoryDBs []*ScenarioGroupHistoryDB
	EmblemDBs               []*EmblemDB
	AttendanceBookRewards   []*AttendanceBookReward
	AttendanceHistoryDBs    []*AttendanceHistoryDB
	StickerDBs              []*StickerDB
	MemoryLobbyDBs          []*MemoryLobbyDB
	ScenarioCollectionDBs   []*ScenarioCollectionDB
	CheatFlags              CheatFlags
}

func (x *CommonCheatResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CommonCheatResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
