// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ConquestTakeEventObjectResponse struct {
	*ResponsePacket

	ParcelResultDB               *ParcelResultDB
	ConquestEventObjectDBWrapper *ConquestEventObjectDB
}

func (x *ConquestTakeEventObjectResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ConquestTakeEventObjectResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
