// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ConquestReceiveRewardsRequest struct {
	*RequestPacket

	EventContentId int64
	Difficulty     StageDifficulty
	Step           int32
}

func (x *ConquestReceiveRewardsRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ConquestReceiveRewardsRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
