// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ConquestMainStoryGetInfoResponse struct {
	*ResponsePacket

	ConquestInfoDB       *ConquestInfoDB
	ConquestedTileDBs    []*ConquestTileDB
	DifficultyToStepDict map[StageDifficulty]int32
	IsFirstEnter         bool
}

func (x *ConquestMainStoryGetInfoResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ConquestMainStoryGetInfoResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
