// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ConquestDisplayInfo struct {
	TriggerType  ConquestTriggerType
	Type         ConquestDisplayType
	EntityId     int64
	TileUniqueId int64
	Parameter    string
	DisplayOrder int32
	DisplayOnce  bool
}

func (x *ConquestDisplayInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
