// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ConquestStepSummary struct {
	ConqueredTileCount    int64
	AllTileCount          int64
	ErosionRemainingCount int64
	HasPhaseComplete      bool
	IsErosionPhaseStart   bool
	IsStepOpen            bool
}

func (x *ConquestStepSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
