// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ConquestReceiveRewardsResponse struct {
	*ResponsePacket

	ParcelResultDB  *ParcelResultDB
	ConquestInfoDB  *ConquestInfoDB
	ConquestTileDBs []*ConquestTileDB
}

func (x *ConquestReceiveRewardsResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ConquestReceiveRewardsResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
