// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ConquestInfoDB struct {
	EventContentId                         int64
	EventGauge                             int32
	EventSpawnCount                        int32
	EchelonChangeCount                     int32
	TodayConquestRentCount                 int32
	TodayOperationRentCount                int32
	CumulatedConditionValue                int64
	ReceivedCalculateRewardConditionAmount int64
	CalculateRewardConditionValue          int64
	AlertMassErosionId                     int64
}

func (x *ConquestInfoDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
