// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ConquestMainStoryConquerRequest struct {
	*RequestPacket

	EventContentId int64
	Difficulty     StageDifficulty
	TileUniqueId   int64
	TileRewardId   int64
}

func (x *ConquestMainStoryConquerRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ConquestMainStoryConquerRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
