// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ContentSweepMultiSweepPresetListRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ContentSweepMultiSweepPresetListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ContentSweepMultiSweepPresetListRequest) ProtoReflect() Message {
	return x
}

func (x *ContentSweepMultiSweepPresetListRequest) GetProtocol() int32 {
	return mx.Protocol_ContentSweep_MultiSweepPresetList
}

func (x *ContentSweepMultiSweepPresetListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

