// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ContentSweepMultiSweepPresetListResponse struct{
	message ProtoMessage
	ResponsePacket

    MultiSweepPresetDBs []*MultiSweepPresetDB
}

func (x *ContentSweepMultiSweepPresetListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ContentSweepMultiSweepPresetListResponse) ProtoReflect() Message {
	return x
}

func (x *ContentSweepMultiSweepPresetListResponse) GetProtocol() int32 {
	return mx.Protocol_ContentSweep_MultiSweepPresetList
}

func (x *ContentSweepMultiSweepPresetListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

