// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ContentsChangeType int32

const (
	ContentsChangeType_None                     ContentsChangeType = 0
	ContentsChangeType_WorldRaidBossDamageRatio ContentsChangeType = 1
	ContentsChangeType_WorldRaidBossGroupDate   ContentsChangeType = 2
)

var (
	ContentsChangeType_name = map[int32]string{
		0: "None",
		1: "WorldRaidBossDamageRatio",
		2: "WorldRaidBossGroupDate",
	}
	ContentsChangeType_value = map[string]int32{
		"None":                     0,
		"WorldRaidBossDamageRatio": 1,
		"WorldRaidBossGroupDate":   2,
	}
)

func (x ContentsChangeType) String() string {
	return ContentsChangeType_name[int32(x)]
}

func (x ContentsChangeType) Value(sr string) ContentsChangeType {
	return ContentsChangeType(ContentsChangeType_value[sr])
}
