// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ContentSweepSetMultiSweepPresetRequest struct {
	*RequestPacket

	PresetId   int64
	PresetName string
	StageIds   []int64
	ParcelIds  []*ParcelKeyPair
}

func (x *ContentSweepSetMultiSweepPresetRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ContentSweepSetMultiSweepPresetRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
