// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ContentSweepRequest struct {
	*RequestPacket

	Content        ContentType
	StageId        int64
	EventContentId int64
	Count          int64
}

func (x *ContentSweepRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ContentSweepRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
