// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ContentLogUIOpenStatisticsResponse struct{
	message ProtoMessage
	ResponsePacket

    
}

func (x *ContentLogUIOpenStatisticsResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ContentLogUIOpenStatisticsResponse) ProtoReflect() Message {
	return x
}

func (x *ContentLogUIOpenStatisticsResponse) GetProtocol() int32 {
	return mx.Protocol_ContentLog_UIOpenStatistics
}

func (x *ContentLogUIOpenStatisticsResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

