// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ContentSaveDB struct {
	ContentType                 ContentType
	AccountServerId             int64
	CreateTime                  mx.MxTime
	StageUniqueId               int64
	LastEnterStageEchelonNumber int64
	StageEntranceFee            []*ParcelInfo
	EnemyKillCountByUniqueId    map[int64]int64
	TacticClearTimeMscSum       int64
	AccountLevelWhenCreateDB    int64
	BIEchelon                   string
	BIEchelon1                  string
	BIEchelon2                  string
	BIEchelon3                  string
	BIEchelon4                  string
}

func (x *ContentSaveDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ContentSaveDB) SetPacket(packet mx.Message) {

}
