// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CostRegenSnapshotCollection struct {
	Frame int64
	Regen float32
}

func (x *CostRegenSnapshotCollection) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CostRegenSnapshotCollection) SetPacket(packet mx.Message) {

}
