// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CostumeDB struct {
	*ParcelBase

	Type                   ParcelType
	ParcelInfos            []*ParcelInfo
	UniqueId               int64
	BoundCharacterServerId int64
}

func (x *CostumeDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CostumeDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ParcelBase = packet.(*ParcelBase)
}
