// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CraftShiftingCompleteProcessResponse struct {
	*ResponsePacket

	CraftInfoDB    *ShiftingCraftInfoDB
	ParcelResultDB *ParcelResultDB
}

func (x *CraftShiftingCompleteProcessResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CraftShiftingCompleteProcessResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
