// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type CraftPresetNodeDB struct {
	NodeTier         CraftNodeTier
	IsActivated      bool
	PriortyNodeId    int64
	ConsumeRequestDB *ConsumeRequestDB
}

func (x *CraftPresetNodeDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
