// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type CraftNodeResult struct {
	NodeTier   CraftNodeTier
	ParcelInfo *ParcelInfo
}

func (x *CraftNodeResult) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
