// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CraftShiftingCompleteProcessRequest struct {
	*RequestPacket

	SlotId int64
}

func (x *CraftShiftingCompleteProcessRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CraftShiftingCompleteProcessRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
