// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CraftCompleteProcessResponse struct {
	*ResponsePacket

	AccountCurrencyDB *AccountCurrencyDB
	CraftInfoDB       *CraftInfoDB
	TicketItemDB      *ItemDB
}

func (x *CraftCompleteProcessResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CraftCompleteProcessResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
