// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CraftShiftingBeginProcessRequest struct {
	*RequestPacket

	SlotId           int64
	RecipeId         int64
	ConsumeRequestDB *ConsumeRequestDB
}

func (x *CraftShiftingBeginProcessRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CraftShiftingBeginProcessRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
