// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CraftUpdateNodeLevelRequest struct {
	*RequestPacket

	ConsumeRequestDB  *ConsumeRequestDB
	ConsumeGoldAmount int64
	SlotId            int64
	CraftNodeType     CraftNodeTier
}

func (x *CraftUpdateNodeLevelRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CraftUpdateNodeLevelRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
