// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type CurrencyTypes int32

const (
	CurrencyTypes_Invalid                   CurrencyTypes = 0
	CurrencyTypes_Gold                      CurrencyTypes = 1
	CurrencyTypes_GemPaid                   CurrencyTypes = 2
	CurrencyTypes_GemBonus                  CurrencyTypes = 3
	CurrencyTypes_Gem                       CurrencyTypes = 4
	CurrencyTypes_ActionPoint               CurrencyTypes = 5
	CurrencyTypes_AcademyTicket             CurrencyTypes = 6
	CurrencyTypes_ArenaTicket               CurrencyTypes = 7
	CurrencyTypes_RaidTicket                CurrencyTypes = 8
	CurrencyTypes_WeekDungeonChaserATicket  CurrencyTypes = 9
	CurrencyTypes_WeekDungeonFindGiftTicket CurrencyTypes = 10
	CurrencyTypes_WeekDungeonBloodTicket    CurrencyTypes = 11
	CurrencyTypes_WeekDungeonChaserBTicket  CurrencyTypes = 12
	CurrencyTypes_WeekDungeonChaserCTicket  CurrencyTypes = 13
	CurrencyTypes_SchoolDungeonATicket      CurrencyTypes = 14
	CurrencyTypes_SchoolDungeonBTicket      CurrencyTypes = 15
	CurrencyTypes_SchoolDungeonCTicket      CurrencyTypes = 16
	CurrencyTypes_TimeAttackDungeonTicket   CurrencyTypes = 17
	CurrencyTypes_MasterCoin                CurrencyTypes = 18
	CurrencyTypes_WorldRaidTicketA          CurrencyTypes = 19
	CurrencyTypes_WorldRaidTicketB          CurrencyTypes = 20
	CurrencyTypes_WorldRaidTicketC          CurrencyTypes = 21
	CurrencyTypes_ChaserTotalTicket         CurrencyTypes = 22
	CurrencyTypes_SchoolDungeonTotalTicket  CurrencyTypes = 23
	CurrencyTypes_EliminateTicketA          CurrencyTypes = 24
	CurrencyTypes_EliminateTicketB          CurrencyTypes = 25
	CurrencyTypes_EliminateTicketC          CurrencyTypes = 26
	CurrencyTypes_EliminateTicketD          CurrencyTypes = 27
	CurrencyTypes_Max                       CurrencyTypes = 28
)

var (
	CurrencyTypes_name = map[int32]string{
		0:  "Invalid",
		1:  "Gold",
		2:  "GemPaid",
		3:  "GemBonus",
		4:  "Gem",
		5:  "ActionPoint",
		6:  "AcademyTicket",
		7:  "ArenaTicket",
		8:  "RaidTicket",
		9:  "WeekDungeonChaserATicket",
		10: "WeekDungeonFindGiftTicket",
		11: "WeekDungeonBloodTicket",
		12: "WeekDungeonChaserBTicket",
		13: "WeekDungeonChaserCTicket",
		14: "SchoolDungeonATicket",
		15: "SchoolDungeonBTicket",
		16: "SchoolDungeonCTicket",
		17: "TimeAttackDungeonTicket",
		18: "MasterCoin",
		19: "WorldRaidTicketA",
		20: "WorldRaidTicketB",
		21: "WorldRaidTicketC",
		22: "ChaserTotalTicket",
		23: "SchoolDungeonTotalTicket",
		24: "EliminateTicketA",
		25: "EliminateTicketB",
		26: "EliminateTicketC",
		27: "EliminateTicketD",
		28: "Max",
	}
	CurrencyTypes_value = map[string]int32{
		"Invalid":                   0,
		"Gold":                      1,
		"GemPaid":                   2,
		"GemBonus":                  3,
		"Gem":                       4,
		"ActionPoint":               5,
		"AcademyTicket":             6,
		"ArenaTicket":               7,
		"RaidTicket":                8,
		"WeekDungeonChaserATicket":  9,
		"WeekDungeonFindGiftTicket": 10,
		"WeekDungeonBloodTicket":    11,
		"WeekDungeonChaserBTicket":  12,
		"WeekDungeonChaserCTicket":  13,
		"SchoolDungeonATicket":      14,
		"SchoolDungeonBTicket":      15,
		"SchoolDungeonCTicket":      16,
		"TimeAttackDungeonTicket":   17,
		"MasterCoin":                18,
		"WorldRaidTicketA":          19,
		"WorldRaidTicketB":          20,
		"WorldRaidTicketC":          21,
		"ChaserTotalTicket":         22,
		"SchoolDungeonTotalTicket":  23,
		"EliminateTicketA":          24,
		"EliminateTicketB":          25,
		"EliminateTicketC":          26,
		"EliminateTicketD":          27,
		"Max":                       28,
	}
)

func (x CurrencyTypes) String() string {
	return CurrencyTypes_name[int32(x)]
}

func (x CurrencyTypes) Value(sr string) CurrencyTypes {
	return CurrencyTypes(CurrencyTypes_value[sr])
}
