// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type CurrencyTransaction struct {
	*ParcelBase

	currencyValue             *CurrencyValue
	Type                      ParcelType
	ParcelInfos               []*ParcelInfo
	CurrencyValues            CurrencyTypes
	Inverse                   *CurrencyTransaction
	IsEmpty                   bool
	Gold                      int64
	Gem                       int64
	GemBonus                  int64
	GemPaid                   int64
	ActionPoint               int64
	ArenaTicket               int64
	RaidTicket                int64
	WeekDungeonChaserATicket  int64
	WeekDungeonChaserBTicket  int64
	WeekDungeonChaserCTicket  int64
	WeekDungeonFindGiftTicket int64
	WeekDungeonBloodTicket    int64
	AcademyTicket             int64
	SchoolDungeonATicket      int64
	SchoolDungeonBTicket      int64
	SchoolDungeonCTicket      int64
	TimeAttackDungeonTicket   int64
	MasterCoin                int64
	WorldRaidTicketA          int64
	WorldRaidTicketB          int64
	WorldRaidTicketC          int64
	ChaserTotalTicket         int64
	SchoolDungeonTotalTicket  int64
	EliminateTicketA          int64
	EliminateTicketB          int64
	EliminateTicketC          int64
	EliminateTicketD          int64
}

func (x *CurrencyTransaction) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CurrencyTransaction) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ParcelBase = packet.(*ParcelBase)
}
