// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type CustomAttributeData struct {
	AttributeType        *Type
	Constructor          *ConstructorInfo
	ConstructorArguments []*CustomAttributeTypedArgument
	NamedArguments       []*CustomAttributeNamedArgument
}

func (x *CustomAttributeData) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
