// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type DreamMakerParameterType int32

const (
	DreamMakerParameterType_None    DreamMakerParameterType = 0
	DreamMakerParameterType_Param01 DreamMakerParameterType = 1
	DreamMakerParameterType_Param02 DreamMakerParameterType = 2
	DreamMakerParameterType_Param03 DreamMakerParameterType = 3
	DreamMakerParameterType_Param04 DreamMakerParameterType = 4
)

var (
	DreamMakerParameterType_name = map[int32]string{
		0: "None",
		1: "Param01",
		2: "Param02",
		3: "Param03",
		4: "Param04",
	}
	DreamMakerParameterType_value = map[string]int32{
		"None":    0,
		"Param01": 1,
		"Param02": 2,
		"Param03": 3,
		"Param04": 4,
	}
)

func (x DreamMakerParameterType) String() string {
	return DreamMakerParameterType_name[int32(x)]
}

func (x DreamMakerParameterType) Value(sr string) DreamMakerParameterType {
	return DreamMakerParameterType(DreamMakerParameterType_value[sr])
}
