// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EchelonSaveRequest struct {
	*RequestPacket

	EchelonDB      *EchelonDB
	AssistUseInfos []*ClanAssistUseInfo
	IsPractice     bool
}

func (x *EchelonSaveRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EchelonSaveRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
