// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type EchelonPresetDB struct {
	GroupIndex             int32
	Index                  int32
	Label                  string
	LeaderUniqueId         int64
	TSSInteractionUniqueId int64
	StrikerUniqueIds       []int64
	SpecialUniqueIds       []int64
	CombatStyleIndex       []int32
	MulliganUniqueIds      []int64
	ExtensionType          EchelonExtensionType
	StrikerSlotCount       int32
	SpecialSlotCount       int32
}

func (x *EchelonPresetDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
