// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type EchelonStatusFlag int32

const (
	EchelonStatusFlag_None         EchelonStatusFlag = 0
	EchelonStatusFlag_BeforeDeploy EchelonStatusFlag = 1
	EchelonStatusFlag_OnDuty       EchelonStatusFlag = 2
)

var (
	EchelonStatusFlag_name = map[int32]string{
		0: "None",
		1: "BeforeDeploy",
		2: "OnDuty",
	}
	EchelonStatusFlag_value = map[string]int32{
		"None":         0,
		"BeforeDeploy": 1,
		"OnDuty":       2,
	}
)

func (x EchelonStatusFlag) String() string {
	return EchelonStatusFlag_name[int32(x)]
}

func (x EchelonStatusFlag) Value(sr string) EchelonStatusFlag {
	return EchelonStatusFlag(EchelonStatusFlag_value[sr])
}
