// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EchelonPresetListRequest struct{
	message ProtoMessage
	RequestPacket

    EchelonExtensionType EchelonExtensionType
}

func (x *EchelonPresetListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EchelonPresetListRequest) ProtoReflect() Message {
	return x
}

func (x *EchelonPresetListRequest) GetProtocol() int32 {
	return mx.Protocol_Echelon_PresetList
}

func (x *EchelonPresetListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

