// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EchelonPresetGroupRenameResponse struct{
	message ProtoMessage
	ResponsePacket

    PresetGroupDB *EchelonPresetGroupDB
}

func (x *EchelonPresetGroupRenameResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EchelonPresetGroupRenameResponse) ProtoReflect() Message {
	return x
}

func (x *EchelonPresetGroupRenameResponse) GetProtocol() int32 {
	return mx.Protocol_Echelon_PresetGroupRename
}

func (x *EchelonPresetGroupRenameResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

