// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EliminateRaidUserDB struct {
	*RaidUserDB

	BossGroupToRankingPoint map[string]int64
}

func (x *EliminateRaidUserDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EliminateRaidUserDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RaidUserDB = packet.(*RaidUserDB)
}
