// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EliminateRaidLoginResponse struct{
	message ProtoMessage
	ResponsePacket

    SeasonType RaidSeasonType
    CanReceiveRankingReward bool
    ReceiveLimitedRewardIds []int64
    SweepPointByRaidUniqueId map[int64]int64
    LastSettledRanking int64
    LastSettledTier int32
}

func (x *EliminateRaidLoginResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EliminateRaidLoginResponse) ProtoReflect() Message {
	return x
}

func (x *EliminateRaidLoginResponse) GetProtocol() int32 {
	return mx.Protocol_EliminateRaid_Login
}

func (x *EliminateRaidLoginResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

