// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EliminateRaidGetBestTeamRequest struct{
	message ProtoMessage
	RequestPacket

    SearchAccountId int64
}

func (x *EliminateRaidGetBestTeamRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EliminateRaidGetBestTeamRequest) ProtoReflect() Message {
	return x
}

func (x *EliminateRaidGetBestTeamRequest) GetProtocol() int32 {
	return mx.Protocol_EliminateRaid_GetBestTeam
}

func (x *EliminateRaidGetBestTeamRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

