// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EliminateRaidLobbyRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *EliminateRaidLobbyRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EliminateRaidLobbyRequest) ProtoReflect() Message {
	return x
}

func (x *EliminateRaidLobbyRequest) GetProtocol() int32 {
	return mx.Protocol_EliminateRaid_Lobby
}

func (x *EliminateRaidLobbyRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

