// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EquipmentBatchGrowthResponse struct{
	message ProtoMessage
	ResponsePacket

    EquipmentDBs []*EquipmentDB
    GearDB *GearDB
    ParcelResultDB *ParcelResultDB
    ConsumeResultDB *ConsumeResultDB
}

func (x *EquipmentBatchGrowthResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EquipmentBatchGrowthResponse) ProtoReflect() Message {
	return x
}

func (x *EquipmentBatchGrowthResponse) GetProtocol() int32 {
	return mx.Protocol_Equipment_BatchGrowth
}

func (x *EquipmentBatchGrowthResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

