// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EquipmentItemEquipRequest struct {
	*RequestPacket

	CharacterServerId  int64
	EquipmentServerIds []int64
	EquipmentServerId  int64
	SlotIndex          int32
}

func (x *EquipmentItemEquipRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EquipmentItemEquipRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
