// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EquipmentItemLevelUpResponse struct{
	message ProtoMessage
	ResponsePacket

    EquipmentDB *EquipmentDB
    AccountCurrencyDB *AccountCurrencyDB
    ConsumeResultDB *ConsumeResultDB
}

func (x *EquipmentItemLevelUpResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EquipmentItemLevelUpResponse) ProtoReflect() Message {
	return x
}

func (x *EquipmentItemLevelUpResponse) GetProtocol() int32 {
	return mx.Protocol_Equipment_LevelUp
}

func (x *EquipmentItemLevelUpResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

