// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EquipmentItemEquipRequest struct{
	message ProtoMessage
	RequestPacket

    CharacterServerId int64
    EquipmentServerIds []int64
    EquipmentServerId int64
    SlotIndex int32
}

func (x *EquipmentItemEquipRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EquipmentItemEquipRequest) ProtoReflect() Message {
	return x
}

func (x *EquipmentItemEquipRequest) GetProtocol() int32 {
	return mx.Protocol_Equipment_Equip
}

func (x *EquipmentItemEquipRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

