// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EquipmentItemEquipResponse struct{
	message ProtoMessage
	ResponsePacket

	CharacterDB *CharacterDB
	EquipmentDBs []*EquipmentDB
}

func (x *EquipmentItemEquipResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EquipmentItemEquipResponse) ProtoReflect() Message {
	return x
}

func (x *EquipmentItemEquipResponse) GetProtocol() int32 {
	return mx.Protocol_Equipment_Equip
}

func (x *EquipmentItemEquipResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

