// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EquipmentBatchGrowthResponse struct {
	*ResponsePacket

	EquipmentDBs    []*EquipmentDB
	GearDB          *GearDB
	ParcelResultDB  *ParcelResultDB
	ConsumeResultDB *ConsumeResultDB
}

func (x *EquipmentBatchGrowthResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EquipmentBatchGrowthResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
