// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EquipmentItemLevelUpRequest struct{
	message ProtoMessage
	RequestPacket

    TargetServerId int64
    ConsumeServerIds []int64
    ConsumeRequestDB *ConsumeRequestDB
}

func (x *EquipmentItemLevelUpRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EquipmentItemLevelUpRequest) ProtoReflect() Message {
	return x
}

func (x *EquipmentItemLevelUpRequest) GetProtocol() int32 {
	return mx.Protocol_Equipment_LevelUp
}

func (x *EquipmentItemLevelUpRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

