// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ErrorPacket struct {
	*ResponsePacket

	Reason    string
	ErrorCode WebAPIErrorCode
}

func (x *ErrorPacket) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ErrorPacket) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
