// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentTreasureLobbyResponse struct {
	*ResponsePacket

	BoardHistoryDB *EventContentTreasureHistoryDB
	HiddenImage    *EventContentTreasureCell
	VariationId    int64
}

func (x *EventContentTreasureLobbyResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentTreasureLobbyResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
