// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentPermanentListResponse struct{
	message ProtoMessage
	ResponsePacket

    PermanentDBs []*EventContentPermanentDB
}

func (x *EventContentPermanentListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentPermanentListResponse) ProtoReflect() Message {
	return x
}

func (x *EventContentPermanentListResponse) GetProtocol() int32 {
	return mx.Protocol_EventContent_PermanentList
}

func (x *EventContentPermanentListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

