// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentStoryStageSaveDB struct {
	*CampaignSubStageSaveDB

	ContentType ContentType
}

func (x *EventContentStoryStageSaveDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentStoryStageSaveDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.CampaignSubStageSaveDB = packet.(*CampaignSubStageSaveDB)
}
