// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentShopBuyRefreshMerchandiseResponse struct {
	*ResponsePacket

	AccountCurrencyDB         *AccountCurrencyDB
	ConsumeResultDB           *ConsumeResultDB
	ParcelResultDB            *ParcelResultDB
	MailDB                    *MailDB
	ShopProductDB             []*ShopProductDB
	EventContentCollectionDBs []*EventContentCollectionDB
}

func (x *EventContentShopBuyRefreshMerchandiseResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentShopBuyRefreshMerchandiseResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
