// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentScenarioGroupHistoryUpdateResponse struct{
	message ProtoMessage
	ResponsePacket

    ScenarioGroupHistoryDBs []*ScenarioGroupHistoryDB
    EventContentCollectionDBs []*EventContentCollectionDB
    ParcelResultDB *ParcelResultDB
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) ProtoReflect() Message {
	return x
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) GetProtocol() int32 {
	return mx.Protocol_EventContent_ScenarioGroupHistoryUpdate
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

