// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentAdventureListRequest struct{
	message ProtoMessage
	RequestPacket

    EventContentId int64
}

func (x *EventContentAdventureListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentAdventureListRequest) ProtoReflect() Message {
	return x
}

func (x *EventContentAdventureListRequest) GetProtocol() int32 {
	return mx.Protocol_EventContent_AdventureList
}

func (x *EventContentAdventureListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

