// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentSubEventLobbyResponse struct {
	*ResponsePacket

	EventContentChangeDB *EventContentChangeDB
	IsOnSubEvent         bool
}

func (x *EventContentSubEventLobbyResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentSubEventLobbyResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
