// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type EventContentBonusRewardDB struct {
	EventContentId     int64
	EventStageUniqueId int64
	BonusPercentage    int64
	BonusParcelInfo    *ParcelInfo
}

func (x *EventContentBonusRewardDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
