// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentAdventureListResponse struct{
	message ProtoMessage
	ResponsePacket

    StageHistoryDBs []*CampaignStageHistoryDB
    StrategyObjecthistoryDBs []*StrategyObjectHistoryDB
    EventContentBonusRewardDBs []*EventContentBonusRewardDB
    AlreadyReceiveRewardId []int64
    StagePoint int64
}

func (x *EventContentAdventureListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentAdventureListResponse) ProtoReflect() Message {
	return x
}

func (x *EventContentAdventureListResponse) GetProtocol() int32 {
	return mx.Protocol_EventContent_AdventureList
}

func (x *EventContentAdventureListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

