// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type EventContentDiceRaceDB struct {
	EventContentId        int64
	Node                  int64
	LapCount              int64
	DiceRollCount         int64
	ReceiveRewardLapCount int64
}

func (x *EventContentDiceRaceDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
