// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type EventTargetType int32

const (
	EventTargetType_WeekDungeon             EventTargetType = 0
	EventTargetType_Chaser                  EventTargetType = 1
	EventTargetType_Campaign_Normal         EventTargetType = 2
	EventTargetType_Campaign_Hard           EventTargetType = 3
	EventTargetType_SchoolDungeon           EventTargetType = 4
	EventTargetType_AcademySchedule         EventTargetType = 5
	EventTargetType_TimeAttackDungeon       EventTargetType = 6
	EventTargetType_AccountLevelExpIncrease EventTargetType = 7
	EventTargetType_Raid                    EventTargetType = 8
	EventTargetType_EliminateRaid           EventTargetType = 9
	EventTargetType_MultiFloorRaid          EventTargetType = 10
)

var (
	EventTargetType_name = map[int32]string{
		0:  "WeekDungeon",
		1:  "Chaser",
		2:  "Campaign_Normal",
		3:  "Campaign_Hard",
		4:  "SchoolDungeon",
		5:  "AcademySchedule",
		6:  "TimeAttackDungeon",
		7:  "AccountLevelExpIncrease",
		8:  "Raid",
		9:  "EliminateRaid",
		10: "MultiFloorRaid",
	}
	EventTargetType_value = map[string]int32{
		"WeekDungeon":             0,
		"Chaser":                  1,
		"Campaign_Normal":         2,
		"Campaign_Hard":           3,
		"SchoolDungeon":           4,
		"AcademySchedule":         5,
		"TimeAttackDungeon":       6,
		"AccountLevelExpIncrease": 7,
		"Raid":                    8,
		"EliminateRaid":           9,
		"MultiFloorRaid":          10,
	}
)

func (x EventTargetType) String() string {
	return EventTargetType_name[int32(x)]
}

func (x EventTargetType) Value(sr string) EventTargetType {
	return EventTargetType(EventTargetType_value[sr])
}
