// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentCardShopPurchaseAllResponse struct {
	*ResponsePacket

	ParcelResultDB             *ParcelResultDB
	CardShopElementDBs         []*CardShopElementDB
	CardShopPurchaseHistoryDBs []*CardShopPurchaseHistoryDB
	RewardHistory              map[int64][]*ParcelInfo
}

func (x *EventContentCardShopPurchaseAllResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentCardShopPurchaseAllResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
