// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type EventContentDiceRaceResultType int32

const (
	EventContentDiceRaceResultType_DiceResult1      EventContentDiceRaceResultType = 0
	EventContentDiceRaceResultType_DiceResult2      EventContentDiceRaceResultType = 1
	EventContentDiceRaceResultType_DiceResult3      EventContentDiceRaceResultType = 2
	EventContentDiceRaceResultType_DiceResult4      EventContentDiceRaceResultType = 3
	EventContentDiceRaceResultType_DiceResult5      EventContentDiceRaceResultType = 4
	EventContentDiceRaceResultType_DiceResult6      EventContentDiceRaceResultType = 5
	EventContentDiceRaceResultType_MoveForward      EventContentDiceRaceResultType = 6
	EventContentDiceRaceResultType_LapFinish        EventContentDiceRaceResultType = 7
	EventContentDiceRaceResultType_EventOccur       EventContentDiceRaceResultType = 8
	EventContentDiceRaceResultType_DiceResultFixed1 EventContentDiceRaceResultType = 9
	EventContentDiceRaceResultType_DiceResultFixed2 EventContentDiceRaceResultType = 10
	EventContentDiceRaceResultType_DiceResultFixed3 EventContentDiceRaceResultType = 11
	EventContentDiceRaceResultType_DiceResultFixed4 EventContentDiceRaceResultType = 12
	EventContentDiceRaceResultType_DiceResultFixed5 EventContentDiceRaceResultType = 13
	EventContentDiceRaceResultType_DiceResultFixed6 EventContentDiceRaceResultType = 14
	EventContentDiceRaceResultType_SpecialReward    EventContentDiceRaceResultType = 15
)

var (
	EventContentDiceRaceResultType_name = map[int32]string{
		0:  "DiceResult1",
		1:  "DiceResult2",
		2:  "DiceResult3",
		3:  "DiceResult4",
		4:  "DiceResult5",
		5:  "DiceResult6",
		6:  "MoveForward",
		7:  "LapFinish",
		8:  "EventOccur",
		9:  "DiceResultFixed1",
		10: "DiceResultFixed2",
		11: "DiceResultFixed3",
		12: "DiceResultFixed4",
		13: "DiceResultFixed5",
		14: "DiceResultFixed6",
		15: "SpecialReward",
	}
	EventContentDiceRaceResultType_value = map[string]int32{
		"DiceResult1":      0,
		"DiceResult2":      1,
		"DiceResult3":      2,
		"DiceResult4":      3,
		"DiceResult5":      4,
		"DiceResult6":      5,
		"MoveForward":      6,
		"LapFinish":        7,
		"EventOccur":       8,
		"DiceResultFixed1": 9,
		"DiceResultFixed2": 10,
		"DiceResultFixed3": 11,
		"DiceResultFixed4": 12,
		"DiceResultFixed5": 13,
		"DiceResultFixed6": 14,
		"SpecialReward":    15,
	}
)

func (x EventContentDiceRaceResultType) String() string {
	return EventContentDiceRaceResultType_name[int32(x)]
}

func (x EventContentDiceRaceResultType) Value(sr string) EventContentDiceRaceResultType {
	return EventContentDiceRaceResultType(EventContentDiceRaceResultType_value[sr])
}
