// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentDiceRaceUseItemRequest struct {
	*RequestPacket

	EventContentId     int64
	DiceRaceResultType EventContentDiceRaceResultType
}

func (x *EventContentDiceRaceUseItemRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentDiceRaceUseItemRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
