// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentRestartMainStageResponse struct {
	*ResponsePacket

	ParcelResultDB *ParcelResultDB
	SaveDataDB     *EventContentMainStageSaveDB
}

func (x *EventContentRestartMainStageResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentRestartMainStageResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
