// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentStoryStageResultResponse struct {
	*ResponsePacket

	CampaignStageHistoryDB    *CampaignStageHistoryDB
	ParcelResultDB            *ParcelResultDB
	FirstClearReward          []*ParcelInfo
	EventContentCollectionDBs []*EventContentCollectionDB
}

func (x *EventContentStoryStageResultResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentStoryStageResultResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
