// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentAdventureListResponse struct {
	*ResponsePacket

	StageHistoryDBs            []*CampaignStageHistoryDB
	StrategyObjecthistoryDBs   []*StrategyObjectHistoryDB
	EventContentBonusRewardDBs []*EventContentBonusRewardDB
	AlreadyReceiveRewardId     []int64
	StagePoint                 int64
}

func (x *EventContentAdventureListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentAdventureListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
