// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type EventContentPermanentDB struct {
	EventContentId            int64
	IsStageAllClear           bool
	IsReceivedCharacterReward bool
}

func (x *EventContentPermanentDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
