// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentScenarioGroupHistoryUpdateResponse struct {
	*ResponsePacket

	ScenarioGroupHistoryDBs   []*ScenarioGroupHistoryDB
	EventContentCollectionDBs []*EventContentCollectionDB
	ParcelResultDB            *ParcelResultDB
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentScenarioGroupHistoryUpdateResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
