// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type EventAttributes int32

const (
	EventAttributes_None          EventAttributes = 0
	EventAttributes_SpecialName   EventAttributes = 512
	EventAttributes_RTSpecialName EventAttributes = 1024
	EventAttributes_ReservedMask  EventAttributes = 1024
)

var (
	EventAttributes_name = map[int32]string{
		0:    "None",
		512:  "SpecialName",
		1024: "RTSpecialName",
	}
	EventAttributes_value = map[string]int32{
		"None":          0,
		"SpecialName":   512,
		"RTSpecialName": 1024,
		"ReservedMask":  1024,
	}
)

func (x EventAttributes) String() string {
	return EventAttributes_name[int32(x)]
}

func (x EventAttributes) Value(sr string) EventAttributes {
	return EventAttributes(EventAttributes_value[sr])
}
