// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentShopListResponse struct {
	*ResponsePacket

	ShopInfos            []*ShopInfoDB
	ShopEligmaHistoryDBs []*ShopEligmaHistoryDB
}

func (x *EventContentShopListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentShopListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
