// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentPermanentListRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *EventContentPermanentListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentPermanentListRequest) ProtoReflect() Message {
	return x
}

func (x *EventContentPermanentListRequest) GetProtocol() int32 {
	return mx.Protocol_EventContent_PermanentList
}

func (x *EventContentPermanentListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

