// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type EventContentTreasureItem struct {
	RewardId      int64
	Amount        int32
	Width         int32
	Weight        int32
	IsHiddenImage bool
	IsSquare      bool
}

func (x *EventContentTreasureItem) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
