// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type EventContentWithdrawEchelonRequest struct {
	*RequestPacket

	EventContentId          int64
	StageUniqueId           int64
	WithdrawEchelonEntityId []int64
}

func (x *EventContentWithdrawEchelonRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentWithdrawEchelonRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
