// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type EventContentBoxGachaShopListResponse struct{
	message ProtoMessage
	ResponsePacket

    BoxGachaDB *EventContentBoxGachaDB
    BoxGachaGroupIdByCount map[int64]int64
}

func (x *EventContentBoxGachaShopListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *EventContentBoxGachaShopListResponse) ProtoReflect() Message {
	return x
}

func (x *EventContentBoxGachaShopListResponse) GetProtocol() int32 {
	return mx.Protocol_EventContent_BoxGachaShopList
}

func (x *EventContentBoxGachaShopListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

