// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ExcessiveTouch struct {
	*ValueType

	ExcessiveTouchFrameList  []int32
	ExcessiveTouchCount      int32
	TotalExcessiveTouchFound int32
}

func (x *ExcessiveTouch) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ExcessiveTouch) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
