// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type FieldAttributes int32

const (
	FieldAttributes_FieldAccessMask FieldAttributes = 7
	FieldAttributes_PrivateScope    FieldAttributes = 0
	FieldAttributes_Private         FieldAttributes = 1
	FieldAttributes_FamANDAssem     FieldAttributes = 2
	FieldAttributes_Assembly        FieldAttributes = 3
	FieldAttributes_Family          FieldAttributes = 4
	FieldAttributes_FamORAssem      FieldAttributes = 5
	FieldAttributes_Public          FieldAttributes = 6
	FieldAttributes_Static          FieldAttributes = 16
	FieldAttributes_InitOnly        FieldAttributes = 32
	FieldAttributes_Literal         FieldAttributes = 64
	FieldAttributes_NotSerialized   FieldAttributes = 128
	FieldAttributes_SpecialName     FieldAttributes = 512
	FieldAttributes_PinvokeImpl     FieldAttributes = 8192
	FieldAttributes_RTSpecialName   FieldAttributes = 1024
	FieldAttributes_HasFieldMarshal FieldAttributes = 4096
	FieldAttributes_HasDefault      FieldAttributes = 32768
	FieldAttributes_HasFieldRVA     FieldAttributes = 256
	FieldAttributes_ReservedMask    FieldAttributes = 38144
)

var (
	FieldAttributes_name = map[int32]string{
		7:     "FieldAccessMask",
		0:     "PrivateScope",
		1:     "Private",
		2:     "FamANDAssem",
		3:     "Assembly",
		4:     "Family",
		5:     "FamORAssem",
		6:     "Public",
		16:    "Static",
		32:    "InitOnly",
		64:    "Literal",
		128:   "NotSerialized",
		512:   "SpecialName",
		8192:  "PinvokeImpl",
		1024:  "RTSpecialName",
		4096:  "HasFieldMarshal",
		32768: "HasDefault",
		256:   "HasFieldRVA",
		38144: "ReservedMask",
	}
	FieldAttributes_value = map[string]int32{
		"FieldAccessMask": 7,
		"PrivateScope":    0,
		"Private":         1,
		"FamANDAssem":     2,
		"Assembly":        3,
		"Family":          4,
		"FamORAssem":      5,
		"Public":          6,
		"Static":          16,
		"InitOnly":        32,
		"Literal":         64,
		"NotSerialized":   128,
		"SpecialName":     512,
		"PinvokeImpl":     8192,
		"RTSpecialName":   1024,
		"HasFieldMarshal": 4096,
		"HasDefault":      32768,
		"HasFieldRVA":     256,
		"ReservedMask":    38144,
	}
)

func (x FieldAttributes) String() string {
	return FieldAttributes_name[int32(x)]
}

func (x FieldAttributes) Value(sr string) FieldAttributes {
	return FieldAttributes(FieldAttributes_value[sr])
}
