// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type FindGiftSummary struct {
	UniqueName string
	ClearCount int32
}

func (x *FindGiftSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
