// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type FriendRemoveResponse struct{
	message ProtoMessage
	ResponsePacket

    FriendDBs []*FriendDB
    SentRequestFriendDBs []*FriendDB
    ReceivedRequestFriendDBs []*FriendDB
    BlockedUserDBs []*FriendDB
}

func (x *FriendRemoveResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *FriendRemoveResponse) ProtoReflect() Message {
	return x
}

func (x *FriendRemoveResponse) GetProtocol() int32 {
	return mx.Protocol_Friend_Remove
}

func (x *FriendRemoveResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

