// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type FriendListResponse struct {
	*ResponsePacket

	IdCardBackgroundDBs      []*IdCardBackgroundDB
	FriendDBs                []*FriendDB
	SentRequestFriendDBs     []*FriendDB
	ReceivedRequestFriendDBs []*FriendDB
	BlockedUserDBs           []*FriendDB
	FriendIdCardDB           *FriendIdCardDB
}

func (x *FriendListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *FriendListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
