// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type FriendListRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *FriendListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *FriendListRequest) ProtoReflect() Message {
	return x
}

func (x *FriendListRequest) GetProtocol() int32 {
	return mx.Protocol_Friend_List
}

func (x *FriendListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

