// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type FriendDB struct {
	AccountId                   int64
	Level                       int32
	Nickname                    string
	LastConnectTime             mx.MxTime
	RepresentCharacterUniqueId  int64
	RepresentCharacterCostumeId int64
	ComfortValue                int64
	FriendCount                 int64
	AttachmentDB                *AccountAttachmentDB
}

func (x *FriendDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
