// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type FriendGetFriendDetailedInfoRequest struct{
	message ProtoMessage
	RequestPacket

    FriendAccountId int64
}

func (x *FriendGetFriendDetailedInfoRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *FriendGetFriendDetailedInfoRequest) ProtoReflect() Message {
	return x
}

func (x *FriendGetFriendDetailedInfoRequest) GetProtocol() int32 {
	return mx.Protocol_Friend_GetFriendDetailedInfo
}

func (x *FriendGetFriendDetailedInfoRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

