// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type FriendGetFriendDetailedInfoResponse struct {
	*ResponsePacket

	Nickname                       string
	Level                          int64
	ClanName                       string
	Comment                        string
	FriendCount                    int64
	FriendCode                     string
	RepresentCharacterUniqueId     int64
	RepresentCharacterCostumeId    int64
	CharacterCount                 int64
	LastNormalCampaignClearStageId int64
	LastHardCampaignClearStageId   int64
	ArenaRanking                   int64
	RaidRanking                    int64
	RaidTier                       int32
	DetailedAccountInfoDB          *DetailedAccountInfoDB
	AttachmentDB                   *AccountAttachmentDB
	AssistCharacterDBs             []*AssistCharacterDB
}

func (x *FriendGetFriendDetailedInfoResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *FriendGetFriendDetailedInfoResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
