// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type FriendGetIdCardResponse struct{
	message ProtoMessage
	ResponsePacket

    FriendIdCardDB *FriendIdCardDB
}

func (x *FriendGetIdCardResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *FriendGetIdCardResponse) ProtoReflect() Message {
	return x
}

func (x *FriendGetIdCardResponse) GetProtocol() int32 {
	return mx.Protocol_Friend_GetIdCard
}

func (x *FriendGetIdCardResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

