// Code generated by gucooing DO NOT EDIT.

package proto

type FriendSearchLevelOption int32

const (
    FriendSearchLevelOption_Recommend = 0
    FriendSearchLevelOption_All = 1
    FriendSearchLevelOption_Level1To30 = 2
    FriendSearchLevelOption_Level31To40 = 3
    FriendSearchLevelOption_Level41To50 = 4
    FriendSearchLevelOption_Level51To60 = 5
    FriendSearchLevelOption_Level61To70 = 6
    FriendSearchLevelOption_Level71To80 = 7
    FriendSearchLevelOption_Level81To90 = 8
    FriendSearchLevelOption_Level91To100 = 9
)

var (
    FriendSearchLevelOption_name = map[int32]string{
      0 : "Recommend",
      1 : "All",
      2 : "Level1To30",
      3 : "Level31To40",
      4 : "Level41To50",
      5 : "Level51To60",
      6 : "Level61To70",
      7 : "Level71To80",
      8 : "Level81To90",
      9 : "Level91To100",
   }
    FriendSearchLevelOption_value = map[string]int32{
      "Recommend" : 0,
      "All" : 1,
      "Level1To30" : 2,
      "Level31To40" : 3,
      "Level41To50" : 4,
      "Level51To60" : 5,
      "Level61To70" : 6,
      "Level71To80" : 7,
      "Level81To90" : 8,
      "Level91To100" : 9,
   }
)

func (x FriendSearchLevelOption) String() string {
  return FriendSearchLevelOption_name[int32(x)]
}

