// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type FriendSendFriendRequestRequest struct{
	message ProtoMessage
	RequestPacket

    TargetAccountId int64
}

func (x *FriendSendFriendRequestRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *FriendSendFriendRequestRequest) ProtoReflect() Message {
	return x
}

func (x *FriendSendFriendRequestRequest) GetProtocol() int32 {
	return mx.Protocol_Friend_SendFriendRequest
}

func (x *FriendSendFriendRequestRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

