// Code generated by gucooing DO NOT EDIT.

package proto

type FurnitureLocation int32

const (
    FurnitureLocation_None = 0
    FurnitureLocation_Inventory = 1
    FurnitureLocation_Floor = 2
    FurnitureLocation_WallLeft = 3
    FurnitureLocation_WallRight = 4
)

var (
    FurnitureLocation_name = map[int32]string{
      0 : "None",
      1 : "Inventory",
      2 : "Floor",
      3 : "WallLeft",
      4 : "WallRight",
   }
    FurnitureLocation_value = map[string]int32{
      "None" : 0,
      "Inventory" : 1,
      "Floor" : 2,
      "WallLeft" : 3,
      "WallRight" : 4,
   }
)

func (x FurnitureLocation) String() string {
  return FurnitureLocation_name[int32(x)]
}

