// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type GachaResult struct {
	CharacterId int64
	Character   *CharacterDB
	Stone       *ItemDB
}

func (x *GachaResult) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
