// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type GearSetting struct {
	*ValueType

	IsValid  bool
	UniqueId int64
	Tier     int32
	Level    int32
}

func (x *GearSetting) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *GearSetting) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
