// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type GroupTag int32

const (
	GroupTag_None    GroupTag = 0
	GroupTag_Group01 GroupTag = 1
	GroupTag_Group02 GroupTag = 2
	GroupTag_Group03 GroupTag = 4
	GroupTag_Group04 GroupTag = 8
	GroupTag_Group05 GroupTag = 16
	GroupTag_Group06 GroupTag = 32
	GroupTag_Group07 GroupTag = 64
	GroupTag_Group08 GroupTag = 128
	GroupTag_Group09 GroupTag = 256
	GroupTag_Group10 GroupTag = 512
	GroupTag_Group11 GroupTag = 1024
	GroupTag_Group12 GroupTag = 2048
	GroupTag_Group13 GroupTag = 4096
	GroupTag_Group14 GroupTag = 8192
	GroupTag_Group15 GroupTag = 16384
	GroupTag_Group16 GroupTag = 32768
)

var (
	GroupTag_name = map[int32]string{
		0:     "None",
		1:     "Group01",
		2:     "Group02",
		4:     "Group03",
		8:     "Group04",
		16:    "Group05",
		32:    "Group06",
		64:    "Group07",
		128:   "Group08",
		256:   "Group09",
		512:   "Group10",
		1024:  "Group11",
		2048:  "Group12",
		4096:  "Group13",
		8192:  "Group14",
		16384: "Group15",
		32768: "Group16",
	}
	GroupTag_value = map[string]int32{
		"None":    0,
		"Group01": 1,
		"Group02": 2,
		"Group03": 4,
		"Group04": 8,
		"Group05": 16,
		"Group06": 32,
		"Group07": 64,
		"Group08": 128,
		"Group09": 256,
		"Group10": 512,
		"Group11": 1024,
		"Group12": 2048,
		"Group13": 4096,
		"Group14": 8192,
		"Group15": 16384,
		"Group16": 32768,
	}
)

func (x GroupTag) String() string {
	return GroupTag_name[int32(x)]
}

func (x GroupTag) Value(sr string) GroupTag {
	return GroupTag(GroupTag_value[sr])
}
