// Code generated by gucooing DO NOT EDIT.

package proto

type GroupSummary struct{
    TeamId int64
    LeaderEntityId *EntityId
    LeaderCharacterId int64
    Heroes []*HeroSummary
    Supporters []*HeroSummary
    AliveCount int32
    UseAutoSkill bool
    TSSInteractionServerId int64
    TSSInteractionUniqueId int64
    AssistRelations map[int64]AssistRelation
    StrikerMaxLevel int32
    SupporterMaxLevel int32
    StrikerMinLevel int32
    SupporterMinLevel int32
    MaxCharacterLevel int32
    MinCharacterLevel int32
    TotalDamageGivenApplied int64
    SkillCostSummary *SkillCostSummary
}

type EntityId struct {
    UniqueId int64 `json:"uniqueId"`
}