// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type HeroSummaryDetailFlag int32

const (
	HeroSummaryDetailFlag_None             HeroSummaryDetailFlag = 0
	HeroSummaryDetailFlag_BattleProperty   HeroSummaryDetailFlag = 2
	HeroSummaryDetailFlag_BattleStatistics HeroSummaryDetailFlag = 4
	HeroSummaryDetailFlag_NumericLogs      HeroSummaryDetailFlag = 8
	HeroSummaryDetailFlag_StatSnapshot     HeroSummaryDetailFlag = 16
	HeroSummaryDetailFlag_Default          HeroSummaryDetailFlag = 14
	HeroSummaryDetailFlag_All              HeroSummaryDetailFlag = 30
)

var (
	HeroSummaryDetailFlag_name = map[int32]string{
		0:  "None",
		2:  "BattleProperty",
		4:  "BattleStatistics",
		8:  "NumericLogs",
		16: "StatSnapshot",
		14: "Default",
		30: "All",
	}
	HeroSummaryDetailFlag_value = map[string]int32{
		"None":             0,
		"BattleProperty":   2,
		"BattleStatistics": 4,
		"NumericLogs":      8,
		"StatSnapshot":     16,
		"Default":          14,
		"All":              30,
	}
)

func (x HeroSummaryDetailFlag) String() string {
	return HeroSummaryDetailFlag_name[int32(x)]
}

func (x HeroSummaryDetailFlag) Value(sr string) HeroSummaryDetailFlag {
	return HeroSummaryDetailFlag(HeroSummaryDetailFlag_value[sr])
}
