// Code generated by gucooing DO NOT EDIT.

package proto

type HexaDisplayType int32

const (
	HexaDisplayType_None                  = 0
	HexaDisplayType_EndBattle             = 1
	HexaDisplayType_PlayScenario          = 2
	HexaDisplayType_SpawnUnitFromUniqueId = 3
	HexaDisplayType_StatBuff              = 4
	HexaDisplayType_DieUnit               = 5
	HexaDisplayType_HideStrategy          = 6
	HexaDisplayType_SpawnUnit             = 7
	HexaDisplayType_SpawnStrategy         = 8
	HexaDisplayType_SpawnTile             = 9
	HexaDisplayType_HideTile              = 10
	HexaDisplayType_ClearFogOfWar         = 11
	HexaDisplayType_MoveUnit              = 12
	HexaDisplayType_WarpUnit              = 13
	HexaDisplayType_SetTileMovablity      = 14
	HexaDisplayType_WarpUnitFromHideTile  = 15
	HexaDisplayType_BossExile             = 16
)

var (
	HexaDisplayType_name = map[int32]string{
		0:  "None",
		1:  "EndBattle",
		2:  "PlayScenario",
		3:  "SpawnUnitFromUniqueId",
		4:  "StatBuff",
		5:  "DieUnit",
		6:  "HideStrategy",
		7:  "SpawnUnit",
		8:  "SpawnStrategy",
		9:  "SpawnTile",
		10: "HideTile",
		11: "ClearFogOfWar",
		12: "MoveUnit",
		13: "WarpUnit",
		14: "SetTileMovablity",
		15: "WarpUnitFromHideTile",
		16: "BossExile",
	}
	HexaDisplayType_value = map[string]int32{
		"None":                  0,
		"EndBattle":             1,
		"PlayScenario":          2,
		"SpawnUnitFromUniqueId": 3,
		"StatBuff":              4,
		"DieUnit":               5,
		"HideStrategy":          6,
		"SpawnUnit":             7,
		"SpawnStrategy":         8,
		"SpawnTile":             9,
		"HideTile":              10,
		"ClearFogOfWar":         11,
		"MoveUnit":              12,
		"WarpUnit":              13,
		"SetTileMovablity":      14,
		"WarpUnitFromHideTile":  15,
		"BossExile":             16,
	}
)

func (x HexaDisplayType) String() string {
	return HexaDisplayType_name[int32(x)]
}
