// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ITBGSeasonInfo struct {
	EventContentId          int64
	ItemSlotCount           int32
	DefaultItemDiceId       int64
	DefaultEchelonHP        int32
	HitPointUpperLimit      int32
	MaxDicePlus             int32
	EchelonSlotCharacterIds []int64
	EchelonSlotPortraits    []string
	EchelonRevivalCost      *ParcelInfo
	EnemyBossHitPoint       int32
	EnemyMinionHitPoint     int32
	AttackDamage            int32
	CriticalAttackDamage    int32
	RoundItemSelectLimit    int32
	InstantClearRound       int32
	EventUseCostId          int64
	EventUseCostType        ParcelType
	StartThemaIndex         int32
	LoopThemaIndex          int32
	MapImagePath            string
	MapNameLocalize         string
}

func (x *ITBGSeasonInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
