// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ITBGDiceInfo struct {
	EventContentId int64
	UniqueId       int64
	DiceGroup      int32
	DiceResult     int32
	Prob           int32
	ProbModifies   TBGProbModifyCondition
}

func (x *ITBGDiceInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
