// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ItemListResponse struct{
	message ProtoMessage
	ResponsePacket

    ItemDBs []*ItemDB
    ExpiryItemDBs []*ItemDB
}

func (x *ItemListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ItemListResponse) ProtoReflect() Message {
	return x
}

func (x *ItemListResponse) GetProtocol() int32 {
	return mx.Protocol_Item_List
}

func (x *ItemListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

