// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ItemListResponse struct {
	*ResponsePacket

	ItemDBs       []*ItemDB
	ExpiryItemDBs []*ItemDB
}

func (x *ItemListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ItemListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
