// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type KillLog struct {
	*ValueType

	Frame    int32
	EntityId *EntityId
}

func (x *KillLog) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *KillLog) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
