// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MailListRequest struct {
	*RequestPacket

	IsReadMail   bool
	PivotTime    mx.MxTime
	PivotIndex   int64
	IsDescending bool
}

func (x *MailListRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MailListRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
