// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MailReceiveResponse struct{
	message ProtoMessage
	ResponsePacket

    MailServerIds []int64
    ParcelResultDB *ParcelResultDB
}

func (x *MailReceiveResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MailReceiveResponse) ProtoReflect() Message {
	return x
}

func (x *MailReceiveResponse) GetProtocol() int32 {
	return mx.Protocol_Mail_Receive
}

func (x *MailReceiveResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

