// Code generated by gucooing DO NOT EDIT.

package proto

type MailType int32

const (
    MailType_System = 0
    MailType_Attendance = 1
    MailType_Event = 2
    MailType_MassTrade = 3
    MailType_InventoryFull = 4
    MailType_ArenaDefenseVictory = 5
    MailType_CouponUsageReward = 6
    MailType_ArenaSeasonClose = 7
    MailType_ProductReward = 8
    MailType_MonthlyProductReward = 9
    MailType_ExpiryChangeItem = 10
    MailType_ClanAttendance = 11
    MailType_AccountLink = 12
    MailType_NewUserBonus = 13
    MailType_LeftClanAssistReward = 14
    MailType_CashShopBuy = 15
    MailType_MonthlyProductPackage = 16
    MailType_WebEventReward = 17
    MailType_AttendanceImmediately = 18
    MailType_WeeklyProductReward = 19
    MailType_BiweeklyProductReward = 20
    MailType_Temp_1 = 21
    MailType_Temp_2 = 22
    MailType_Temp_3 = 23
    MailType_CouponCompleteReward = 24
    MailType_BirthdayMail = 25
    MailType_FromCS = 26
)

var (
    MailType_name = map[int32]string{
      0 : "System",
      1 : "Attendance",
      2 : "Event",
      3 : "MassTrade",
      4 : "InventoryFull",
      5 : "ArenaDefenseVictory",
      6 : "CouponUsageReward",
      7 : "ArenaSeasonClose",
      8 : "ProductReward",
      9 : "MonthlyProductReward",
      10 : "ExpiryChangeItem",
      11 : "ClanAttendance",
      12 : "AccountLink",
      13 : "NewUserBonus",
      14 : "LeftClanAssistReward",
      15 : "CashShopBuy",
      16 : "MonthlyProductPackage",
      17 : "WebEventReward",
      18 : "AttendanceImmediately",
      19 : "WeeklyProductReward",
      20 : "BiweeklyProductReward",
      21 : "Temp_1",
      22 : "Temp_2",
      23 : "Temp_3",
      24 : "CouponCompleteReward",
      25 : "BirthdayMail",
      26 : "FromCS",
   }
    MailType_value = map[string]int32{
      "System" : 0,
      "Attendance" : 1,
      "Event" : 2,
      "MassTrade" : 3,
      "InventoryFull" : 4,
      "ArenaDefenseVictory" : 5,
      "CouponUsageReward" : 6,
      "ArenaSeasonClose" : 7,
      "ProductReward" : 8,
      "MonthlyProductReward" : 9,
      "ExpiryChangeItem" : 10,
      "ClanAttendance" : 11,
      "AccountLink" : 12,
      "NewUserBonus" : 13,
      "LeftClanAssistReward" : 14,
      "CashShopBuy" : 15,
      "MonthlyProductPackage" : 16,
      "WebEventReward" : 17,
      "AttendanceImmediately" : 18,
      "WeeklyProductReward" : 19,
      "BiweeklyProductReward" : 20,
      "Temp_1" : 21,
      "Temp_2" : 22,
      "Temp_3" : 23,
      "CouponCompleteReward" : 24,
      "BirthdayMail" : 25,
      "FromCS" : 26,
   }
)

func (x MailType) String() string {
  return MailType_name[int32(x)]
}

func GetMailType(s string) MailType  {
    return MailType(MailType_value[s])
}