// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type MailType int32

const (
	MailType_System                MailType = 0
	MailType_Attendance            MailType = 1
	MailType_Event                 MailType = 2
	MailType_MassTrade             MailType = 3
	MailType_InventoryFull         MailType = 4
	MailType_ArenaDefenseVictory   MailType = 5
	MailType_CouponUsageReward     MailType = 6
	MailType_ArenaSeasonClose      MailType = 7
	MailType_ProductReward         MailType = 8
	MailType_MonthlyProductReward  MailType = 9
	MailType_ExpiryChangeItem      MailType = 10
	MailType_ClanAttendance        MailType = 11
	MailType_AccountLink           MailType = 12
	MailType_NewUserBonus          MailType = 13
	MailType_LeftClanAssistReward  MailType = 14
	MailType_AttendanceImmediately MailType = 15
	MailType_WeeklyProductReward   MailType = 16
	MailType_BiweeklyProductReward MailType = 17
	MailType_Temp_1                MailType = 18
	MailType_Temp_2                MailType = 19
	MailType_Temp_3                MailType = 20
	MailType_CouponCompleteReward  MailType = 21
	MailType_BirthdayMail          MailType = 22
	MailType_FromCS                MailType = 23
	MailType_ExpiryChangeCurrency  MailType = 24
)

var (
	MailType_name = map[int32]string{
		0:  "System",
		1:  "Attendance",
		2:  "Event",
		3:  "MassTrade",
		4:  "InventoryFull",
		5:  "ArenaDefenseVictory",
		6:  "CouponUsageReward",
		7:  "ArenaSeasonClose",
		8:  "ProductReward",
		9:  "MonthlyProductReward",
		10: "ExpiryChangeItem",
		11: "ClanAttendance",
		12: "AccountLink",
		13: "NewUserBonus",
		14: "LeftClanAssistReward",
		15: "AttendanceImmediately",
		16: "WeeklyProductReward",
		17: "BiweeklyProductReward",
		18: "Temp_1",
		19: "Temp_2",
		20: "Temp_3",
		21: "CouponCompleteReward",
		22: "BirthdayMail",
		23: "FromCS",
		24: "ExpiryChangeCurrency",
	}
	MailType_value = map[string]int32{
		"System":                0,
		"Attendance":            1,
		"Event":                 2,
		"MassTrade":             3,
		"InventoryFull":         4,
		"ArenaDefenseVictory":   5,
		"CouponUsageReward":     6,
		"ArenaSeasonClose":      7,
		"ProductReward":         8,
		"MonthlyProductReward":  9,
		"ExpiryChangeItem":      10,
		"ClanAttendance":        11,
		"AccountLink":           12,
		"NewUserBonus":          13,
		"LeftClanAssistReward":  14,
		"AttendanceImmediately": 15,
		"WeeklyProductReward":   16,
		"BiweeklyProductReward": 17,
		"Temp_1":                18,
		"Temp_2":                19,
		"Temp_3":                20,
		"CouponCompleteReward":  21,
		"BirthdayMail":          22,
		"FromCS":                23,
		"ExpiryChangeCurrency":  24,
	}
)

func (x MailType) String() string {
	return MailType_name[int32(x)]
}

func (x MailType) Value(sr string) MailType {
	return MailType(MailType_value[sr])
}
