// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MailDB struct {
	ServerId          int64
	AccountServerId   int64
	Type              MailType
	UniqueId          int64
	Sender            string
	Comment           string
	SendDate          mx.MxTime
	ReceiptDate       mx.MxTime
	ExpireDate        mx.MxTime
	ParcelInfos       []*ParcelInfo
	RemainParcelInfos []*ParcelInfo
}

func (x *MailDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
