// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type MethodAttributes int32

const (
	MethodAttributes_MemberAccessMask      MethodAttributes = 7
	MethodAttributes_PrivateScope          MethodAttributes = 0
	MethodAttributes_Private               MethodAttributes = 1
	MethodAttributes_FamANDAssem           MethodAttributes = 2
	MethodAttributes_Assembly              MethodAttributes = 3
	MethodAttributes_Family                MethodAttributes = 4
	MethodAttributes_FamORAssem            MethodAttributes = 5
	MethodAttributes_Public                MethodAttributes = 6
	MethodAttributes_Static                MethodAttributes = 16
	MethodAttributes_Final                 MethodAttributes = 32
	MethodAttributes_Virtual               MethodAttributes = 64
	MethodAttributes_HideBySig             MethodAttributes = 128
	MethodAttributes_CheckAccessOnOverride MethodAttributes = 512
	MethodAttributes_VtableLayoutMask      MethodAttributes = 256
	MethodAttributes_ReuseSlot             MethodAttributes = 0
	MethodAttributes_NewSlot               MethodAttributes = 256
	MethodAttributes_Abstract              MethodAttributes = 1024
	MethodAttributes_SpecialName           MethodAttributes = 2048
	MethodAttributes_PinvokeImpl           MethodAttributes = 8192
	MethodAttributes_UnmanagedExport       MethodAttributes = 8
	MethodAttributes_RTSpecialName         MethodAttributes = 4096
	MethodAttributes_HasSecurity           MethodAttributes = 16384
	MethodAttributes_RequireSecObject      MethodAttributes = 32768
	MethodAttributes_ReservedMask          MethodAttributes = 53248
)

var (
	MethodAttributes_name = map[int32]string{
		7:     "MemberAccessMask",
		0:     "PrivateScope",
		1:     "Private",
		2:     "FamANDAssem",
		3:     "Assembly",
		4:     "Family",
		5:     "FamORAssem",
		6:     "Public",
		16:    "Static",
		32:    "Final",
		64:    "Virtual",
		128:   "HideBySig",
		512:   "CheckAccessOnOverride",
		256:   "VtableLayoutMask",
		1024:  "Abstract",
		2048:  "SpecialName",
		8192:  "PinvokeImpl",
		8:     "UnmanagedExport",
		4096:  "RTSpecialName",
		16384: "HasSecurity",
		32768: "RequireSecObject",
		53248: "ReservedMask",
	}
	MethodAttributes_value = map[string]int32{
		"MemberAccessMask":      7,
		"PrivateScope":          0,
		"Private":               1,
		"FamANDAssem":           2,
		"Assembly":              3,
		"Family":                4,
		"FamORAssem":            5,
		"Public":                6,
		"Static":                16,
		"Final":                 32,
		"Virtual":               64,
		"HideBySig":             128,
		"CheckAccessOnOverride": 512,
		"VtableLayoutMask":      256,
		"ReuseSlot":             0,
		"NewSlot":               256,
		"Abstract":              1024,
		"SpecialName":           2048,
		"PinvokeImpl":           8192,
		"UnmanagedExport":       8,
		"RTSpecialName":         4096,
		"HasSecurity":           16384,
		"RequireSecObject":      32768,
		"ReservedMask":          53248,
	}
)

func (x MethodAttributes) String() string {
	return MethodAttributes_name[int32(x)]
}

func (x MethodAttributes) Value(sr string) MethodAttributes {
	return MethodAttributes(MethodAttributes_value[sr])
}
