// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameShootingSweepResponse struct {
	*ResponsePacket

	Rewards        [][]*ParcelInfo
	ParcelResultDB *ParcelResultDB
}

func (x *MiniGameShootingSweepResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameShootingSweepResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
