// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type MiniGameShootingSummary struct {
	EventContentId    int64
	StageId           int64
	PlayerCharacterId int64
	GeasIds           []int64
	SectionCount      int64
	ArriveSection     int64
	LeftTimeSec       float32
	ProgressedTimeSec float32
	KillEnemies       map[int64]int32
	IsWin             bool
}

func (x *MiniGameShootingSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
