// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameDreamMakerEndingDB struct {
	EventContentId int64
	EndingId       int64
	ClearCount     int64
	ClearDate      mx.MxTime
}

func (x *MiniGameDreamMakerEndingDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
