// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameDefenseBattleResultRequest struct {
	*RequestPacket

	EventContentId int64
	StageId        int64
	Multiplier     int32
	IsPlayerWin    bool
	BaseDamage     int32
	HeroCount      int32
	AliveCount     int32
	ClearSecond    int32
	Summary        *BattleSummary
}

func (x *MiniGameDefenseBattleResultRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameDefenseBattleResultRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
