// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameDefenseGetInfoResponse struct {
	*ResponsePacket

	EventPointAmount       int64
	DefenseStageHistoryDBs []*MiniGameDefenseStageHistoryDB
}

func (x *MiniGameDefenseGetInfoResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameDefenseGetInfoResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
