// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameShootingSweepRequest struct {
	*RequestPacket

	EventContentId int64
	UniqueId       int64
	SweepCount     int64
}

func (x *MiniGameShootingSweepRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameShootingSweepRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
