// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type MiniGameDefenseStageHistoryDB struct {
	StageId                 int64
	Star1Flag               bool
	Star2Flag               bool
	Star3Flag               bool
	FirstClearRewardReceive bool
	StarRewardReceive       bool
	IsThreeStar             bool
	IsFirstClear            bool
}

func (x *MiniGameDefenseStageHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
