// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type MinigameJudgeRecord struct {
	NoteIndex            int32
	TimingError          float32
	CurrentCombo         int32
	JudgeGradeOfThisNote JudgeGrade
	IsFeverOn            bool
}

func (x *MinigameJudgeRecord) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
