// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameRoadPuzzleTilePlaceRequest struct {
	*RequestPacket

	EventContentId  int64
	UniqueId        int64
	Round           int64
	RailTileToPlace *RoadPuzzleRailTileData
}

func (x *MiniGameRoadPuzzleTilePlaceRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameRoadPuzzleTilePlaceRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
