// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MinigameRhythmSummary struct {
	MusicTitle           string
	PatternDifficulty    int32
	IsSpecial            bool
	TotalNoteCount       int32
	CriticalCount        int32
	AttackCount          int32
	MissCount            int32
	IsFullCombo          bool
	MaxCombo             int32
	FinalScore           int64
	HPBonusScore         int64
	GameStartTime        mx.MxTime
	GameEndTime          mx.MxTime
	RhythmGamePlayTime   float32
	StdDev               float32
	MinigameJudgeRecords []*MinigameJudgeRecord
	IsAutoPlay           bool
}

func (x *MinigameRhythmSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
