// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameHistoryDB struct {
	EventContentId   int64
	UniqueId         int64
	HighScore        int64
	AccumulatedScore int64
	ClearDate        mx.MxTime
	IsFullCombo      bool
}

func (x *MiniGameHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
