// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameMissionListResponse struct {
	*ResponsePacket

	MissionHistoryUniqueIds []int64
	ProgressDBs             []*MissionProgressDB
}

func (x *MiniGameMissionListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameMissionListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
