// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type MiniGameDreamMakerInfoDB struct {
	EventContentId         int64
	Round                  int64
	Multiplier             int64
	DayOfNumber            int64
	ActionCount            int64
	CurrentRoundEndingId   int64
	EndingRewardReceived   bool
	CanStartNewGame        bool
	CanReceiveEndingReward bool
}

func (x *MiniGameDreamMakerInfoDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
