// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameDreamMakerGetInfoResponse struct {
	*ResponsePacket

	InfoDB                       *MiniGameDreamMakerInfoDB
	ParameterDBs                 []*MiniGameDreamMakerParameterDB
	EndingDBs                    []*MiniGameDreamMakerEndingDB
	EventContentCollectionDBs    []*EventContentCollectionDB
	EventPointAmount             int64
	AlreadyReceivePointRewardIds []int64
}

func (x *MiniGameDreamMakerGetInfoResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameDreamMakerGetInfoResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
