// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MiniGameDreamMakerAttendScheduleResponse struct {
	*ResponsePacket

	InfoDB                    *MiniGameDreamMakerInfoDB
	ParameterDBs              []*MiniGameDreamMakerParameterDB
	ParcelResultDB            *ParcelResultDB
	ScheduleResultId          int64
	EventContentCollectionDBs []*EventContentCollectionDB
}

func (x *MiniGameDreamMakerAttendScheduleResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MiniGameDreamMakerAttendScheduleResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
