// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type MissionResetType int32

const (
	MissionResetType_None   MissionResetType = 0
	MissionResetType_Daily  MissionResetType = 1
	MissionResetType_Weekly MissionResetType = 2
	MissionResetType_Limit  MissionResetType = 3
)

var (
	MissionResetType_name = map[int32]string{
		0: "None",
		1: "Daily",
		2: "Weekly",
		3: "Limit",
	}
	MissionResetType_value = map[string]int32{
		"None":   0,
		"Daily":  1,
		"Weekly": 2,
		"Limit":  3,
	}
)

func (x MissionResetType) String() string {
	return MissionResetType_name[int32(x)]
}

func (x MissionResetType) Value(sr string) MissionResetType {
	return MissionResetType(MissionResetType_value[sr])
}
