// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MissionHistoryDB struct {
	ServerId        int64
	AccountServerId int64
	MissionUniqueId int64
	CompleteTime    mx.MxTime
	Expired         bool
}

func (x *MissionHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
