// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MissionListRequest struct{
	message ProtoMessage
	RequestPacket

    EventContentId int64
}

func (x *MissionListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MissionListRequest) ProtoReflect() Message {
	return x
}

func (x *MissionListRequest) GetProtocol() int32 {
	return mx.Protocol_Mission_List
}

func (x *MissionListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

