// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MissionProgressDB struct {
	ServerId           int64
	AccountServerId    int64
	MissionUniqueId    int64
	Complete           bool
	StartTime          mx.MxTime
	ProgressParameters map[int64]int64
}

func (x *MissionProgressDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
