// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type MissionHistoryDB struct{
    MissionUniqueId int64
    CompleteTime mx.MxTime
    Expired bool
}

