// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MissionRewardResponse struct{
	message ProtoMessage
	ResponsePacket

    AddedHistoryDB *MissionHistoryDB
    ParcelResultDB *ParcelResultDB
}

func (x *MissionRewardResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MissionRewardResponse) ProtoReflect() Message {
	return x
}

func (x *MissionRewardResponse) GetProtocol() int32 {
	return mx.Protocol_Mission_Reward
}

func (x *MissionRewardResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

