// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type MissionCategory int32

const (
	MissionCategory_Challenge        MissionCategory = 0
	MissionCategory_Daily            MissionCategory = 1
	MissionCategory_Weekly           MissionCategory = 2
	MissionCategory_Achievement      MissionCategory = 3
	MissionCategory_GuideMission     MissionCategory = 4
	MissionCategory_All              MissionCategory = 5
	MissionCategory_MiniGameScore    MissionCategory = 6
	MissionCategory_MiniGameEvent    MissionCategory = 7
	MissionCategory_EventAchievement MissionCategory = 8
	MissionCategory_DailySudden      MissionCategory = 9
	MissionCategory_DailyFixed       MissionCategory = 10
	MissionCategory_EventFixed       MissionCategory = 11
)

var (
	MissionCategory_name = map[int32]string{
		0:  "Challenge",
		1:  "Daily",
		2:  "Weekly",
		3:  "Achievement",
		4:  "GuideMission",
		5:  "All",
		6:  "MiniGameScore",
		7:  "MiniGameEvent",
		8:  "EventAchievement",
		9:  "DailySudden",
		10: "DailyFixed",
		11: "EventFixed",
	}
	MissionCategory_value = map[string]int32{
		"Challenge":        0,
		"Daily":            1,
		"Weekly":           2,
		"Achievement":      3,
		"GuideMission":     4,
		"All":              5,
		"MiniGameScore":    6,
		"MiniGameEvent":    7,
		"EventAchievement": 8,
		"DailySudden":      9,
		"DailyFixed":       10,
		"EventFixed":       11,
	}
)

func (x MissionCategory) String() string {
	return MissionCategory_name[int32(x)]
}

func (x MissionCategory) Value(sr string) MissionCategory {
	return MissionCategory(MissionCategory_value[sr])
}
