// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type Module struct {
	Assembly           *Assembly
	FullyQualifiedName string
	Name               string
	MDStreamVersion    int32
	ModuleVersionId    *Guid
	ScopeName          string
	ModuleHandle       *ModuleHandle
	CustomAttributes   []*CustomAttributeData
	MetadataToken      int32
}

func (x *Module) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
