// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MomoTalkFavorScheduleRequest struct{
	message ProtoMessage
	RequestPacket

    ScheduleId int64
}

func (x *MomoTalkFavorScheduleRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MomoTalkFavorScheduleRequest) ProtoReflect() Message {
	return x
}

func (x *MomoTalkFavorScheduleRequest) GetProtocol() int32 {
	return mx.Protocol_MomoTalk_FavorSchedule
}

func (x *MomoTalkFavorScheduleRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

