// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MomoTalkReadRequest struct{
	message ProtoMessage
	RequestPacket

    CharacterDBId int64
    LastReadMessageGroupId int64
    ChosenMessageId int64
}

func (x *MomoTalkReadRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MomoTalkReadRequest) ProtoReflect() Message {
	return x
}

func (x *MomoTalkReadRequest) GetProtocol() int32 {
	return mx.Protocol_MomoTalk_Read
}

func (x *MomoTalkReadRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

