// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MomoTalkReadResponse struct{
	message ProtoMessage
	ResponsePacket

    MomoTalkOutLineDB *MomoTalkOutLineDB
    MomoTalkChoiceDBs []*MomoTalkChoiceDB
}

func (x *MomoTalkReadResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MomoTalkReadResponse) ProtoReflect() Message {
	return x
}

func (x *MomoTalkReadResponse) GetProtocol() int32 {
	return mx.Protocol_MomoTalk_Read
}

func (x *MomoTalkReadResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

