// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "time"
)

type MonthlyProductPurchaseDB struct{
    ProductId int64
    PurchaseDate time.Time
    LastDailyRewardDate time.Time
    RewardEndDate time.Time
    ProductTagType ProductTagType
}

