// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MonthlyProductPurchaseDB struct {
	ProductId           int64
	PurchaseDate        mx.MxTime
	LastDailyRewardDate mx.MxTime
	RewardEndDate       mx.MxTime
	ProductTagType      ProductTagType
}

func (x *MonthlyProductPurchaseDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
