// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MultiFloorRaidSyncRequest struct{
	message ProtoMessage
	RequestPacket

    SeasonId int64
}

func (x *MultiFloorRaidSyncRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MultiFloorRaidSyncRequest) ProtoReflect() Message {
	return x
}

func (x *MultiFloorRaidSyncRequest) GetProtocol() int32 {
	return mx.Protocol_MultiFloorRaid_Sync
}

func (x *MultiFloorRaidSyncRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

