// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MultiFloorRaidEnterBattleRequest struct {
	*RequestPacket

	SeasonId       int64
	Difficulty     int32
	EchelonId      int32
	AssistUseInfos []*ClanAssistUseInfo
}

func (x *MultiFloorRaidEnterBattleRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MultiFloorRaidEnterBattleRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
