// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MultiFloorRaidEnterBattleRequest struct{
	message ProtoMessage
	RequestPacket

    SeasonId int64
    Difficulty int32
    EchelonId int32
    AssistUseInfos []*ClanAssistUseInfo
}

func (x *MultiFloorRaidEnterBattleRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MultiFloorRaidEnterBattleRequest) ProtoReflect() Message {
	return x
}

func (x *MultiFloorRaidEnterBattleRequest) GetProtocol() int32 {
	return mx.Protocol_MultiFloorRaid_EnterBattle
}

func (x *MultiFloorRaidEnterBattleRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

