// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type MultiSweepPresetDB struct {
	PresetId   int64
	PresetName string
	StageIds   []int64
	ParcelIds  []*ParcelKeyPair
}

func (x *MultiSweepPresetDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
