// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MultiFloorRaidReceiveRewardResponse struct {
	*ResponsePacket

	MultiFloorRaidDB *MultiFloorRaidDB
	ParcelResultDB   *ParcelResultDB
}

func (x *MultiFloorRaidReceiveRewardResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MultiFloorRaidReceiveRewardResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
