// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MulticastDelegate struct {
	*Delegate
}

func (x *MulticastDelegate) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *MulticastDelegate) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.Delegate = packet.(*Delegate)
}
