// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MultiFloorRaidReceiveRewardResponse struct{
	message ProtoMessage
	ResponsePacket

    MultiFloorRaidDB *MultiFloorRaidDB
    ParcelResultDB *ParcelResultDB
}

func (x *MultiFloorRaidReceiveRewardResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MultiFloorRaidReceiveRewardResponse) ProtoReflect() Message {
	return x
}

func (x *MultiFloorRaidReceiveRewardResponse) GetProtocol() int32 {
	return mx.Protocol_MultiFloorRaid_ReceiveReward
}

func (x *MultiFloorRaidReceiveRewardResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

