// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type MultiFloorRaidReceiveRewardRequest struct{
	message ProtoMessage
	RequestPacket

    SeasonId int64
    RewardDifficulty int32
}

func (x *MultiFloorRaidReceiveRewardRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *MultiFloorRaidReceiveRewardRequest) ProtoReflect() Message {
	return x
}

func (x *MultiFloorRaidReceiveRewardRequest) GetProtocol() int32 {
	return mx.Protocol_MultiFloorRaid_ReceiveReward
}

func (x *MultiFloorRaidReceiveRewardRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

