// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type MultiFloorRaidDB struct {
	SeasonId               int64
	ClearedDifficulty      int32
	LastClearDate          mx.MxTime
	RewardDifficulty       int32
	LastRewardDate         mx.MxTime
	ClearBattleFrame       int32
	AllCleared             bool
	HasReceivableRewards   bool
	TotalReceivableRewards []*ParcelInfo
	TotalReceivedRewards   []*ParcelInfo
}

func (x *MultiFloorRaidDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
