// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type NetworkTimeSyncResponse struct{
	message ProtoMessage
	ResponsePacket

    ReceiveTick int64
    EchoSendTick int64
}

func (x *NetworkTimeSyncResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *NetworkTimeSyncResponse) ProtoReflect() Message {
	return x
}

func (x *NetworkTimeSyncResponse) GetProtocol() int32 {
	return mx.Protocol_NetworkTime_Sync
}

func (x *NetworkTimeSyncResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

