// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type NotificationEventContentReddotResponse struct {
	*ResponsePacket

	Reddots                 map[int64][]NotificationEventReddot
	EventContentUnlockCGDBs map[int64][]*EventContentCollectionDB
}

func (x *NotificationEventContentReddotResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *NotificationEventContentReddotResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
