// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type OpenConditionEventListResponse struct {
	*ResponsePacket

	ConquestTiles         map[int64][]*ConquestTileDB
	WorldRaidLocalBossDBs map[int64][]*WorldRaidLocalBossDB
}

func (x *OpenConditionEventListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *OpenConditionEventListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
