// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type OpenConditionLockReason int32

const (
	OpenConditionLockReason_None              OpenConditionLockReason = 0
	OpenConditionLockReason_Level             OpenConditionLockReason = 1
	OpenConditionLockReason_StageClear        OpenConditionLockReason = 2
	OpenConditionLockReason_Time              OpenConditionLockReason = 4
	OpenConditionLockReason_Day               OpenConditionLockReason = 8
	OpenConditionLockReason_CafeRank          OpenConditionLockReason = 16
	OpenConditionLockReason_ScenarioModeClear OpenConditionLockReason = 32
	OpenConditionLockReason_CafeOpen          OpenConditionLockReason = 64
)

var (
	OpenConditionLockReason_name = map[int32]string{
		0:  "None",
		1:  "Level",
		2:  "StageClear",
		4:  "Time",
		8:  "Day",
		16: "CafeRank",
		32: "ScenarioModeClear",
		64: "CafeOpen",
	}
	OpenConditionLockReason_value = map[string]int32{
		"None":              0,
		"Level":             1,
		"StageClear":        2,
		"Time":              4,
		"Day":               8,
		"CafeRank":          16,
		"ScenarioModeClear": 32,
		"CafeOpen":          64,
	}
)

func (x OpenConditionLockReason) String() string {
	return OpenConditionLockReason_name[int32(x)]
}

func (x OpenConditionLockReason) Value(sr string) OpenConditionLockReason {
	return OpenConditionLockReason(OpenConditionLockReason_value[sr])
}
