// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type OpenConditionEventListResponse struct{
	message ProtoMessage
	ResponsePacket

    ConquestTiles map[int64][]*ConquestTileDB
    WorldRaidLocalBossDBs map[int64][]*WorldRaidLocalBossDB
}

func (x *OpenConditionEventListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *OpenConditionEventListResponse) ProtoReflect() Message {
	return x
}

func (x *OpenConditionEventListResponse) GetProtocol() int32 {
	return mx.Protocol_OpenCondition_EventList
}

func (x *OpenConditionEventListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

