// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type OpenConditionContent int32

const (
	OpenConditionContent_Shop                              OpenConditionContent = 0
	OpenConditionContent_Gacha                             OpenConditionContent = 1
	OpenConditionContent_LobbyIllust                       OpenConditionContent = 2
	OpenConditionContent_Raid                              OpenConditionContent = 3
	OpenConditionContent_Cafe                              OpenConditionContent = 4
	OpenConditionContent_Unit_Growth_Skill                 OpenConditionContent = 5
	OpenConditionContent_Unit_Growth_LevelUp               OpenConditionContent = 6
	OpenConditionContent_Unit_Growth_Transcendence         OpenConditionContent = 7
	OpenConditionContent_Arena                             OpenConditionContent = 8
	OpenConditionContent_Academy                           OpenConditionContent = 9
	OpenConditionContent_Equip                             OpenConditionContent = 10
	OpenConditionContent_Item                              OpenConditionContent = 11
	OpenConditionContent_Favor                             OpenConditionContent = 12
	OpenConditionContent_Prologue                          OpenConditionContent = 13
	OpenConditionContent_Mission                           OpenConditionContent = 14
	OpenConditionContent_WeekDungeon_Chase                 OpenConditionContent = 15
	OpenConditionContent___Deprecated_WeekDungeon_FindGift OpenConditionContent = 16
	OpenConditionContent___Deprecated_WeekDungeon_Blood    OpenConditionContent = 17
	OpenConditionContent_Story_Sub                         OpenConditionContent = 18
	OpenConditionContent_Story_Replay                      OpenConditionContent = 19
	OpenConditionContent_WeekDungeon                       OpenConditionContent = 20
	OpenConditionContent_None                              OpenConditionContent = 21
	OpenConditionContent_Shop_Gem                          OpenConditionContent = 22
	OpenConditionContent_Craft                             OpenConditionContent = 23
	OpenConditionContent_Student                           OpenConditionContent = 24
	OpenConditionContent_GuideMission                      OpenConditionContent = 25
	OpenConditionContent_Clan                              OpenConditionContent = 26
	OpenConditionContent_Echelon                           OpenConditionContent = 27
	OpenConditionContent_Campaign                          OpenConditionContent = 28
	OpenConditionContent_EventContent                      OpenConditionContent = 29
	OpenConditionContent_Guild                             OpenConditionContent = 30
	OpenConditionContent_EventStage_1                      OpenConditionContent = 31
	OpenConditionContent_EventStage_2                      OpenConditionContent = 32
	OpenConditionContent_Talk                              OpenConditionContent = 33
	OpenConditionContent_Billing                           OpenConditionContent = 34
	OpenConditionContent_Schedule                          OpenConditionContent = 35
	OpenConditionContent_Story                             OpenConditionContent = 36
	OpenConditionContent_Tactic_Speed                      OpenConditionContent = 37
	OpenConditionContent_Cafe_Invite                       OpenConditionContent = 38
	OpenConditionContent_EventMiniGame_1                   OpenConditionContent = 39
	OpenConditionContent_SchoolDungeon                     OpenConditionContent = 40
	OpenConditionContent_TimeAttackDungeon                 OpenConditionContent = 41
	OpenConditionContent_ShiftingCraft                     OpenConditionContent = 42
	OpenConditionContent_WorldRaid                         OpenConditionContent = 43
	OpenConditionContent_Tactic_Skip                       OpenConditionContent = 44
	OpenConditionContent_Mulligan                          OpenConditionContent = 45
	OpenConditionContent_EventPermanent                    OpenConditionContent = 46
	OpenConditionContent_Main_L_1_2                        OpenConditionContent = 47
	OpenConditionContent_Main_L_1_3                        OpenConditionContent = 48
	OpenConditionContent_Main_L_1_4                        OpenConditionContent = 49
	OpenConditionContent_EliminateRaid                     OpenConditionContent = 50
	OpenConditionContent_Cafe_2                            OpenConditionContent = 51
	OpenConditionContent_Cafe_Invite_2                     OpenConditionContent = 52
	OpenConditionContent_MultiFloorRaid                    OpenConditionContent = 53
	OpenConditionContent_StrategySkip                      OpenConditionContent = 54
	OpenConditionContent_MinigameDreamMaker                OpenConditionContent = 55
	OpenConditionContent_MiniGameDefense                   OpenConditionContent = 56
)

var (
	OpenConditionContent_name = map[int32]string{
		0:  "Shop",
		1:  "Gacha",
		2:  "LobbyIllust",
		3:  "Raid",
		4:  "Cafe",
		5:  "Unit_Growth_Skill",
		6:  "Unit_Growth_LevelUp",
		7:  "Unit_Growth_Transcendence",
		8:  "Arena",
		9:  "Academy",
		10: "Equip",
		11: "Item",
		12: "Favor",
		13: "Prologue",
		14: "Mission",
		15: "WeekDungeon_Chase",
		16: "__Deprecated_WeekDungeon_FindGift",
		17: "__Deprecated_WeekDungeon_Blood",
		18: "Story_Sub",
		19: "Story_Replay",
		20: "WeekDungeon",
		21: "None",
		22: "Shop_Gem",
		23: "Craft",
		24: "Student",
		25: "GuideMission",
		26: "Clan",
		27: "Echelon",
		28: "Campaign",
		29: "EventContent",
		30: "Guild",
		31: "EventStage_1",
		32: "EventStage_2",
		33: "Talk",
		34: "Billing",
		35: "Schedule",
		36: "Story",
		37: "Tactic_Speed",
		38: "Cafe_Invite",
		39: "EventMiniGame_1",
		40: "SchoolDungeon",
		41: "TimeAttackDungeon",
		42: "ShiftingCraft",
		43: "WorldRaid",
		44: "Tactic_Skip",
		45: "Mulligan",
		46: "EventPermanent",
		47: "Main_L_1_2",
		48: "Main_L_1_3",
		49: "Main_L_1_4",
		50: "EliminateRaid",
		51: "Cafe_2",
		52: "Cafe_Invite_2",
		53: "MultiFloorRaid",
		54: "StrategySkip",
		55: "MinigameDreamMaker",
		56: "MiniGameDefense",
	}
	OpenConditionContent_value = map[string]int32{
		"Shop":                              0,
		"Gacha":                             1,
		"LobbyIllust":                       2,
		"Raid":                              3,
		"Cafe":                              4,
		"Unit_Growth_Skill":                 5,
		"Unit_Growth_LevelUp":               6,
		"Unit_Growth_Transcendence":         7,
		"Arena":                             8,
		"Academy":                           9,
		"Equip":                             10,
		"Item":                              11,
		"Favor":                             12,
		"Prologue":                          13,
		"Mission":                           14,
		"WeekDungeon_Chase":                 15,
		"__Deprecated_WeekDungeon_FindGift": 16,
		"__Deprecated_WeekDungeon_Blood":    17,
		"Story_Sub":                         18,
		"Story_Replay":                      19,
		"WeekDungeon":                       20,
		"None":                              21,
		"Shop_Gem":                          22,
		"Craft":                             23,
		"Student":                           24,
		"GuideMission":                      25,
		"Clan":                              26,
		"Echelon":                           27,
		"Campaign":                          28,
		"EventContent":                      29,
		"Guild":                             30,
		"EventStage_1":                      31,
		"EventStage_2":                      32,
		"Talk":                              33,
		"Billing":                           34,
		"Schedule":                          35,
		"Story":                             36,
		"Tactic_Speed":                      37,
		"Cafe_Invite":                       38,
		"EventMiniGame_1":                   39,
		"SchoolDungeon":                     40,
		"TimeAttackDungeon":                 41,
		"ShiftingCraft":                     42,
		"WorldRaid":                         43,
		"Tactic_Skip":                       44,
		"Mulligan":                          45,
		"EventPermanent":                    46,
		"Main_L_1_2":                        47,
		"Main_L_1_3":                        48,
		"Main_L_1_4":                        49,
		"EliminateRaid":                     50,
		"Cafe_2":                            51,
		"Cafe_Invite_2":                     52,
		"MultiFloorRaid":                    53,
		"StrategySkip":                      54,
		"MinigameDreamMaker":                55,
		"MiniGameDefense":                   56,
	}
)

func (x OpenConditionContent) String() string {
	return OpenConditionContent_name[int32(x)]
}

func (x OpenConditionContent) Value(sr string) OpenConditionContent {
	return OpenConditionContent(OpenConditionContent_value[sr])
}
