// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ParameterAttributes int32

const (
	ParameterAttributes_None            ParameterAttributes = 0
	ParameterAttributes_In              ParameterAttributes = 1
	ParameterAttributes_Out             ParameterAttributes = 2
	ParameterAttributes_Lcid            ParameterAttributes = 4
	ParameterAttributes_Retval          ParameterAttributes = 8
	ParameterAttributes_Optional        ParameterAttributes = 16
	ParameterAttributes_HasDefault      ParameterAttributes = 4096
	ParameterAttributes_HasFieldMarshal ParameterAttributes = 8192
	ParameterAttributes_Reserved3       ParameterAttributes = 16384
	ParameterAttributes_Reserved4       ParameterAttributes = 32768
	ParameterAttributes_ReservedMask    ParameterAttributes = 61440
)

var (
	ParameterAttributes_name = map[int32]string{
		0:     "None",
		1:     "In",
		2:     "Out",
		4:     "Lcid",
		8:     "Retval",
		16:    "Optional",
		4096:  "HasDefault",
		8192:  "HasFieldMarshal",
		16384: "Reserved3",
		32768: "Reserved4",
		61440: "ReservedMask",
	}
	ParameterAttributes_value = map[string]int32{
		"None":            0,
		"In":              1,
		"Out":             2,
		"Lcid":            4,
		"Retval":          8,
		"Optional":        16,
		"HasDefault":      4096,
		"HasFieldMarshal": 8192,
		"Reserved3":       16384,
		"Reserved4":       32768,
		"ReservedMask":    61440,
	}
)

func (x ParameterAttributes) String() string {
	return ParameterAttributes_name[int32(x)]
}

func (x ParameterAttributes) Value(sr string) ParameterAttributes {
	return ParameterAttributes(ParameterAttributes_value[sr])
}
