// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ParcelType int32

const (
	ParcelType_None             ParcelType = 0
	ParcelType_Character        ParcelType = 1
	ParcelType_Currency         ParcelType = 2
	ParcelType_Equipment        ParcelType = 3
	ParcelType_Item             ParcelType = 4
	ParcelType_GachaGroup       ParcelType = 5
	ParcelType_Product          ParcelType = 6
	ParcelType_Shop             ParcelType = 7
	ParcelType_MemoryLobby      ParcelType = 8
	ParcelType_AccountExp       ParcelType = 9
	ParcelType_CharacterExp     ParcelType = 10
	ParcelType_FavorExp         ParcelType = 11
	ParcelType_TSS              ParcelType = 12
	ParcelType_Furniture        ParcelType = 13
	ParcelType_ShopRefresh      ParcelType = 14
	ParcelType_LocationExp      ParcelType = 15
	ParcelType_Recipe           ParcelType = 16
	ParcelType_CharacterWeapon  ParcelType = 17
	ParcelType_CharacterGear    ParcelType = 18
	ParcelType_IdCardBackground ParcelType = 19
	ParcelType_Emblem           ParcelType = 20
	ParcelType_Sticker          ParcelType = 21
	ParcelType_Costume          ParcelType = 22
)

var (
	ParcelType_name = map[int32]string{
		0:  "None",
		1:  "Character",
		2:  "Currency",
		3:  "Equipment",
		4:  "Item",
		5:  "GachaGroup",
		6:  "Product",
		7:  "Shop",
		8:  "MemoryLobby",
		9:  "AccountExp",
		10: "CharacterExp",
		11: "FavorExp",
		12: "TSS",
		13: "Furniture",
		14: "ShopRefresh",
		15: "LocationExp",
		16: "Recipe",
		17: "CharacterWeapon",
		18: "CharacterGear",
		19: "IdCardBackground",
		20: "Emblem",
		21: "Sticker",
		22: "Costume",
	}
	ParcelType_value = map[string]int32{
		"None":             0,
		"Character":        1,
		"Currency":         2,
		"Equipment":        3,
		"Item":             4,
		"GachaGroup":       5,
		"Product":          6,
		"Shop":             7,
		"MemoryLobby":      8,
		"AccountExp":       9,
		"CharacterExp":     10,
		"FavorExp":         11,
		"TSS":              12,
		"Furniture":        13,
		"ShopRefresh":      14,
		"LocationExp":      15,
		"Recipe":           16,
		"CharacterWeapon":  17,
		"CharacterGear":    18,
		"IdCardBackground": 19,
		"Emblem":           20,
		"Sticker":          21,
		"Costume":          22,
	}
)

func (x ParcelType) String() string {
	return ParcelType_name[int32(x)]
}

func (x ParcelType) Value(sr string) ParcelType {
	return ParcelType(ParcelType_value[sr])
}
