// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ParcelKeyPair struct {
	*ValueType

	Type ParcelType
	Id   int64
}

func (x *ParcelKeyPair) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ParcelKeyPair) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
