// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ParcelCost struct {
	ParcelInfos           []*ParcelInfo
	Currency              *CurrencyTransaction
	EquipmentDBs          []*EquipmentDB
	ItemDBs               []*ItemDB
	FurnitureDBs          []*FurnitureDB
	HasCurrency           bool
	HasItem               bool
	IsEmpty               bool
	ConsumableItemBaseDBs []*ConsumableItemBaseDB
	ConsumeCondition      ConsumeCondition
}

func (x *ParcelCost) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
