// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ParcelProcessActionType int32

const (
	ParcelProcessActionType_None   ParcelProcessActionType = 0
	ParcelProcessActionType_Cost   ParcelProcessActionType = 1
	ParcelProcessActionType_Reward ParcelProcessActionType = 2
)

var (
	ParcelProcessActionType_name = map[int32]string{
		0: "None",
		1: "Cost",
		2: "Reward",
	}
	ParcelProcessActionType_value = map[string]int32{
		"None":   0,
		"Cost":   1,
		"Reward": 2,
	}
)

func (x ParcelProcessActionType) String() string {
	return ParcelProcessActionType_name[int32(x)]
}

func (x ParcelProcessActionType) Value(sr string) ParcelProcessActionType {
	return ParcelProcessActionType(ParcelProcessActionType_value[sr])
}
