// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ParcelChangeType int32

const (
	ParcelChangeType_NoChange   ParcelChangeType = 0
	ParcelChangeType_Terminated ParcelChangeType = 1
	ParcelChangeType_MailSend   ParcelChangeType = 2
	ParcelChangeType_Converted  ParcelChangeType = 3
)

var (
	ParcelChangeType_name = map[int32]string{
		0: "NoChange",
		1: "Terminated",
		2: "MailSend",
		3: "Converted",
	}
	ParcelChangeType_value = map[string]int32{
		"NoChange":   0,
		"Terminated": 1,
		"MailSend":   2,
		"Converted":  3,
	}
)

func (x ParcelChangeType) String() string {
	return ParcelChangeType_name[int32(x)]
}

func (x ParcelChangeType) Value(sr string) ParcelChangeType {
	return ParcelChangeType(ParcelChangeType_value[sr])
}
