// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ParcelBase struct {
	Type        ParcelType
	ParcelInfos []*ParcelInfo
}

func (x *ParcelBase) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ParcelBase) SetPacket(packet mx.Message) {

}
