// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type PotentialGrowthRequestDB struct {
	Type  PotentialStatBonusRateType
	Level int32
}

func (x *PotentialGrowthRequestDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
