// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ProofTokenRequestQuestionResponse struct {
	*ResponsePacket

	Hint     int64
	Question string
}

func (x *ProofTokenRequestQuestionResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ProofTokenRequestQuestionResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
