// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ProofTokenSubmitResponse struct{
	message ProtoMessage
	ResponsePacket

    
}

func (x *ProofTokenSubmitResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ProofTokenSubmitResponse) ProtoReflect() Message {
	return x
}

func (x *ProofTokenSubmitResponse) GetProtocol() int32 {
	return mx.Protocol_ProofToken_Submit
}

func (x *ProofTokenSubmitResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

