// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type PropertyInfo struct {
	*MemberInfo

	MemberType    MemberTypes
	PropertyType  *Type
	Attributes    PropertyAttributes
	IsSpecialName bool
	CanRead       bool
	CanWrite      bool
	GetMethod     *MethodInfo
	SetMethod     *MethodInfo
}

func (x *PropertyInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *PropertyInfo) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.MemberInfo = packet.(*MemberInfo)
}
