// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type PurchaseCountDB struct {
	ShopCashId      int64
	PurchaseCount   int32
	ResetDate       mx.MxTime
	PurchaseDate    mx.MxTime
	ManualResetDate mx.MxTime
}

func (x *PurchaseCountDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
