// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type QueuingGetTicketResponse struct {
	*ResponsePacket

	WaitingTicket          string
	EnterTicket            string
	TicketSequence         int64
	AllowedSequence        int64
	RequiredSecondsPerUser float64
	Birth                  string
	ServerSeed             string
}

func (x *QueuingGetTicketResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *QueuingGetTicketResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
