// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type QueuingGetTicketRequest struct {
	*RequestPacket

	YostarUID       int64
	YostarToken     string
	MakeStandby     bool
	PassCheck       bool
	PassCheckYostar bool
	WaitingTicket   string
	ClientVersion   string
}

func (x *QueuingGetTicketRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *QueuingGetTicketRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
