// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidDamageCollection struct {
	Index            int32
	GivenGroggyPoint int64
	GivenDamage      int64
}

func (x *RaidDamageCollection) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidDamageCollection) SetPacket(packet mx.Message) {

}
