// Code generated by gucooing DO NOT EDIT.

package proto

type RaidBossResultCollection struct{
    AIPhase int64
    EndHpRateRawValue int64
    GroggyCount int32
    GroggyRateRawValue int64
    SubPartsHPs []int64
    RaidDamage *RaidDamage
}

