// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidRewardRequest struct {
	*RequestPacket

	RaidServerId int64
	IsPractice   bool
}

func (x *RaidRewardRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidRewardRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
