// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type RaidMemberDescription struct {
	AccountId        int64
	AccountName      string
	CharacterId      int64
	DamageGiven      int64
	GroggyGiven      int64
	DamageCollection []*RaidDamageCollection
}

func (x *RaidMemberDescription) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
