// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidRankingRewardRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *RaidRankingRewardRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidRankingRewardRequest) ProtoReflect() Message {
	return x
}

func (x *RaidRankingRewardRequest) GetProtocol() int32 {
	return mx.Protocol_Raid_RankingReward
}

func (x *RaidRankingRewardRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

