// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidGiveUpResponse struct {
	*ResponsePacket

	Tier           int32
	RaidGiveUpDB   *RaidGiveUpDB
	ParcelResultDB *ParcelResultDB
}

func (x *RaidGiveUpResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidGiveUpResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
