// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidListRequest struct {
	*RequestPacket

	RaidBossGroup      string
	RaidDifficulty     Difficulty
	RaidRoomSortOption RaidRoomSortOption
}

func (x *RaidListRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidListRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
