// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidLobbyResponse struct{
	message ProtoMessage
	ResponsePacket

    SeasonType RaidSeasonType
    RaidGiveUpDB *RaidGiveUpDB
    RaidLobbyInfoDB *SingleRaidLobbyInfoDB
    AccountCurrencyDB *AccountCurrencyDB
    ParcelResultDB *ParcelResultDB
}

func (x *RaidLobbyResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidLobbyResponse) ProtoReflect() Message {
	return x
}

func (x *RaidLobbyResponse) GetProtocol() int32 {
	return mx.Protocol_Raid_Lobby
}

func (x *RaidLobbyResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

