// Code generated by gucooing DO NOT EDIT.

package proto

type RaidMemberDescription struct{
    AccountId int64
    AccountName string
    CharacterId int64
    DamageGiven int64
    GroggyGiven int64
    DamageCollection []*RaidDamageCollection
}

