// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidEnterBattleResponse struct{
	message ProtoMessage
	ResponsePacket

    RaidDB *RaidDB
    RaidBattleDB *RaidBattleDB
    AccountCurrencyDB *AccountCurrencyDB
    AssistCharacterDB *AssistCharacterDB
}

func (x *RaidEnterBattleResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidEnterBattleResponse) ProtoReflect() Message {
	return x
}

func (x *RaidEnterBattleResponse) GetProtocol() int32 {
	return mx.Protocol_Raid_EnterBattle
}

func (x *RaidEnterBattleResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

