// Code generated by gucooing DO NOT EDIT.

package proto

type RaidSummary struct{
    RaidSeasonId int64
    GivenDamage int64
    TotalGroggyCount int32
    RaidBossIndex int32
    RaidBossResults []*RaidBossResultCollection
}

