// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidEndBattleRequest struct{
	message ProtoMessage
	RequestPacket

    EchelonId int32
    RaidServerId int64
    IsPractice bool
    Summary *BattleSummary
    AssistUseInfo *ClanAssistUseInfo
}

func (x *RaidEndBattleRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidEndBattleRequest) ProtoReflect() Message {
	return x
}

func (x *RaidEndBattleRequest) GetProtocol() int32 {
	return mx.Protocol_Raid_EndBattle
}

func (x *RaidEndBattleRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

