// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidRankingRewardResponse struct {
	*ResponsePacket

	ReceivedRankingRewardId int64
	ParcelResultDB          *ParcelResultDB
}

func (x *RaidRankingRewardResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidRankingRewardResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
