// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidRewardResponse struct {
	*ResponsePacket

	RankingPoint     int64
	BestRankingPoint int64
	ParcelResultDB   *ParcelResultDB
}

func (x *RaidRewardResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidRewardResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
