// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidLoginResponse struct {
	*ResponsePacket

	SeasonType              RaidSeasonType
	CanReceiveRankingReward bool
	LastSettledRanking      int64
	LastSettledTier         int32
}

func (x *RaidLoginResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidLoginResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
