// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidSeasonRankingHistoryDB struct {
	ContentType      ContentType
	AccountId        int64
	SeasonId         int64
	Ranking          int64
	BestRankingPoint int64
	Tier             int32
	ReceivedDate     mx.MxTime
}

func (x *RaidSeasonRankingHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
