// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidCreateBattleResponse struct {
	*ResponsePacket

	RaidDB            *RaidDB
	RaidBattleDB      *RaidBattleDB
	AccountCurrencyDB *AccountCurrencyDB
	AssistCharacterDB *AssistCharacterDB
}

func (x *RaidCreateBattleResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidCreateBattleResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
