// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidDamage struct {
	*ValueType

	Index            int32
	GivenDamage      int64
	GivenGroggyPoint int64
}

func (x *RaidDamage) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidDamage) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
