// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidLobbyResponse struct {
	*ResponsePacket

	SeasonType        RaidSeasonType
	RaidGiveUpDB      *RaidGiveUpDB
	RaidLobbyInfoDB   *SingleRaidLobbyInfoDB
	AccountCurrencyDB *AccountCurrencyDB
	ParcelResultDB    *ParcelResultDB
}

func (x *RaidLobbyResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidLobbyResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
