// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidUserDB struct {
	AccountId                   int64
	RepresentCharacterUniqueId  int64
	RepresentCharacterCostumeId int64
	Level                       int64
	Nickname                    string
	Tier                        int32
	Rank                        int64
	BestRankingPoint            int64
	BestRankingPointDetail      float64
	AccountAttachmentDB         *AccountAttachmentDB
}

func (x *RaidUserDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidUserDB) SetPacket(packet mx.Message) {

}
