// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidPlayerInfoDB struct {
	RaidServerId      int64
	AccountId         int64
	JoinDate          mx.MxTime
	DamageAmount      int64
	RaidEndRewardFlag int32
	RaidPlayCount     int32
	Nickname          string
	CharacterId       int64
	CostumeId         int64
	AccountLevel      int64
}

func (x *RaidPlayerInfoDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
