// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidGiveUpRequest struct{
	message ProtoMessage
	RequestPacket

    RaidServerId int64
    IsPractice bool
}

func (x *RaidGiveUpRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidGiveUpRequest) ProtoReflect() Message {
	return x
}

func (x *RaidGiveUpRequest) GetProtocol() int32 {
	return mx.Protocol_Raid_GiveUp
}

func (x *RaidGiveUpRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

