// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidSeasonRewardRequest struct {
	*RequestPacket
}

func (x *RaidSeasonRewardRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidSeasonRewardRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
