// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type RaidGiveUpDB struct {
	Ranking          int64
	RankingPoint     int64
	BestRankingPoint int64
}

func (x *RaidGiveUpDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
