// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type RaidSummary struct {
	RaidSeasonId     int64
	GivenDamage      int64
	TotalGroggyCount int32
	RaidBossIndex    int32
	RaidBossResults  []*RaidBossResultCollection
}

func (x *RaidSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
