// Code generated by gucooing DO NOT EDIT.

package proto

type RaidBattleDB struct{
    ContentType ContentType
    RaidUniqueId int64
    RaidBossIndex int32
    CurrentBossHP int64
    CurrentBossGroggy int64
    CurrentBossAIPhase int64
    BIEchelon string
    IsClear bool
    RaidMembers []*RaidMemberDescription
    SubPartsHPs []int64
}

