// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidEndBattleResponse struct{
	message ProtoMessage
	ResponsePacket

    RankingPoint int64
    BestRankingPoint int64
    ClearTimePoint int64
    HPPercentScorePoint int64
    DefaultClearPoint int64
    ParcelResultDB *ParcelResultDB
}

func (x *RaidEndBattleResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidEndBattleResponse) ProtoReflect() Message {
	return x
}

func (x *RaidEndBattleResponse) GetProtocol() int32 {
	return mx.Protocol_Raid_EndBattle
}

func (x *RaidEndBattleResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

