// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidDetailDB struct {
	RaidUniqueId int64
	EndDate      mx.MxTime
	DamageTable  []*RaidPlayerInfoDB
}

func (x *RaidDetailDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
