// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidLoginResponse struct{
	message ProtoMessage
	ResponsePacket

    SeasonType RaidSeasonType
    CanReceiveRankingReward bool
    LastSettledRanking int64
    LastSettledTier int32
}

func (x *RaidLoginResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidLoginResponse) ProtoReflect() Message {
	return x
}

func (x *RaidLoginResponse) GetProtocol() int32 {
	return mx.Protocol_Raid_Login
}

func (x *RaidLoginResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

