// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidCompleteListResponse struct {
	*ResponsePacket

	RaidDBs           []*RaidDB
	StackedDamage     int64
	ReceiveRewardId   []int64
	CurSeasonUniqueId int64
}

func (x *RaidCompleteListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidCompleteListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
