// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RaidBossResultCollection struct {
	AIPhase            int64
	EndHpRateRawValue  int64
	GroggyCount        int32
	GroggyRateRawValue int64
	SubPartsHPs        []int64
	RaidDamage         *RaidDamage
}

func (x *RaidBossResultCollection) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RaidBossResultCollection) SetPacket(packet mx.Message) {

}
