// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type RaidGiveUpResponse struct{
	message ProtoMessage
	ResponsePacket

    Tier int32
    RaidGiveUpDB *RaidGiveUpDB
    ParcelResultDB *ParcelResultDB
}

func (x *RaidGiveUpResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *RaidGiveUpResponse) ProtoReflect() Message {
	return x
}

func (x *RaidGiveUpResponse) GetProtocol() int32 {
	return mx.Protocol_Raid_GiveUp
}

func (x *RaidGiveUpResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

