// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RecipeCraftResponse struct {
	*ResponsePacket

	ParcelResultDB           *ParcelResultDB
	EquipmentConsumeResultDB *ConsumeResultDB
	ItemConsumeResultDB      *ConsumeResultDB
}

func (x *RecipeCraftResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RecipeCraftResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
