// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type RequestPacket struct {
	*BasePacket

	ClientUpTime                  int32
	Resendable                    bool
	Hash                          int64
	IsTest                        bool
	ModifiedServerTime__DebugOnly mx.MxTime
}

func (x *RequestPacket) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *RequestPacket) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.BasePacket = packet.(*BasePacket)
}
