// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ResetableContentValueDB struct {
	ResetableContentId *ResetableContentId
	ContentValue       int64
	LastUpdateTime     mx.MxTime
}

func (x *ResetableContentValueDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
