// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ResetableContentId struct {
	*ValueType

	Type   ResetContentType
	Mapped int64
}

func (x *ResetableContentId) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ResetableContentId) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
