// Code generated by gucooing DO NOT EDIT.

package proto

type ResetContentType int32

const (
	ResetContentType_None                      = 0
	ResetContentType_HardStagePlay             = 1
	ResetContentType_StarategyMapHeal          = 2
	ResetContentType_ShopRefresh               = 3
	ResetContentType_ArenaDefenseVictoryReward = 4
	ResetContentType_WeeklyMasterCoin          = 5
	ResetContentType_WorldRaidGemEnterCount    = 6
	ResetContentType_ConquestDailyErosionCheck = 7
	ResetContentType_MiniEventToken            = 8
)

var (
	ResetContentType_name = map[int32]string{
		0: "None",
		1: "HardStagePlay",
		2: "StarategyMapHeal",
		3: "ShopRefresh",
		4: "ArenaDefenseVictoryReward",
		5: "WeeklyMasterCoin",
		6: "WorldRaidGemEnterCount",
		7: "ConquestDailyErosionCheck",
		8: "MiniEventToken",
	}
	ResetContentType_value = map[string]int32{
		"None":                      0,
		"HardStagePlay":             1,
		"StarategyMapHeal":          2,
		"ShopRefresh":               3,
		"ArenaDefenseVictoryReward": 4,
		"WeeklyMasterCoin":          5,
		"WorldRaidGemEnterCount":    6,
		"ConquestDailyErosionCheck": 7,
		"MiniEventToken":            8,
	}
)

func (x ResetContentType) String() string {
	return ResetContentType_name[int32(x)]
}
