// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ResponsePacket struct {
	*BasePacket

	ServerTimeTicks            int64
	ServerNotification         ServerNotificationFlag
	MissionProgressDBs         []*MissionProgressDB
	EventMissionProgressDBDict map[int64][]*MissionProgressDB
	StaticOpenConditions       map[string]int32
}

func (x *ResponsePacket) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ResponsePacket) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.BasePacket = packet.(*BasePacket)
}
