// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioSkipRequest struct{
	message ProtoMessage
	RequestPacket

    ScriptGroupId int64
    SkipPointScriptCount int32
}

func (x *ScenarioSkipRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioSkipRequest) ProtoReflect() Message {
	return x
}

func (x *ScenarioSkipRequest) GetProtocol() int32 {
	return mx.Protocol_Scenario_Skip
}

func (x *ScenarioSkipRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

