// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioListResponse struct{
	message ProtoMessage
	ResponsePacket

    ScenarioHistoryDBs []*ScenarioHistoryDB
    ScenarioGroupHistoryDBs []*ScenarioGroupHistoryDB
    ScenarioCollectionDBs []*ScenarioCollectionDB
}

func (x *ScenarioListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioListResponse) ProtoReflect() Message {
	return x
}

func (x *ScenarioListResponse) GetProtocol() int32 {
	return mx.Protocol_Scenario_List
}

func (x *ScenarioListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

