// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioDeployEchelonResponse struct {
	*ResponsePacket

	SaveDataDB *StoryStrategyStageSaveDB
}

func (x *ScenarioDeployEchelonResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ScenarioDeployEchelonResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
