// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioListResponse struct {
	*ResponsePacket

	ScenarioHistoryDBs      []*ScenarioHistoryDB
	ScenarioGroupHistoryDBs []*ScenarioGroupHistoryDB
	ScenarioCollectionDBs   []*ScenarioCollectionDB
}

func (x *ScenarioListResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ScenarioListResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
