// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioSkipRequest struct {
	*RequestPacket

	ScriptGroupId        int64
	SkipPointScriptCount int32
}

func (x *ScenarioSkipRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ScenarioSkipRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
