// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "time"
)

type ScenarioGroupHistoryDB struct{
    AccountServerId int64
    ScenarioGroupUqniueId int64
    ScenarioType int64
    EventContentId int64
    ClearDateTime time.Time
    IsReturn bool
}

