// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioLobbyStudentChangeResponse struct{
	message ProtoMessage
	ResponsePacket

    
}

func (x *ScenarioLobbyStudentChangeResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioLobbyStudentChangeResponse) ProtoReflect() Message {
	return x
}

func (x *ScenarioLobbyStudentChangeResponse) GetProtocol() int32 {
	return mx.Protocol_Scenario_LobbyStudentChange
}

func (x *ScenarioLobbyStudentChangeResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

