// Code generated by gucooing DO NOT EDIT.

package proto

import (
    "github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioGroupHistoryDB struct{
    AccountServerId int64
    ScenarioGroupUqniueId int64
    ScenarioType int64
    EventContentId int64
    ClearDateTime mx.MxTime
    IsReturn bool
}

