// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioPortalResponse struct {
	*ResponsePacket

	StoryStrategyStageSaveDB *StoryStrategyStageSaveDB
	ScenarioIds              []int64
}

func (x *ScenarioPortalResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ScenarioPortalResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
