// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioSelectRequest struct{
	message ProtoMessage
	RequestPacket

    ScriptGroupId int64
    ScriptSelectGroup int64
}

func (x *ScenarioSelectRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioSelectRequest) ProtoReflect() Message {
	return x
}

func (x *ScenarioSelectRequest) GetProtocol() int32 {
	return mx.Protocol_Scenario_Select
}

func (x *ScenarioSelectRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

