// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioGroupHistoryUpdateResponse struct{
	message ProtoMessage
	ResponsePacket

    ScenarioGroupHistoryDB *ScenarioGroupHistoryDB
}

func (x *ScenarioGroupHistoryUpdateResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioGroupHistoryUpdateResponse) ProtoReflect() Message {
	return x
}

func (x *ScenarioGroupHistoryUpdateResponse) GetProtocol() int32 {
	return mx.Protocol_Scenario_GroupHistoryUpdate
}

func (x *ScenarioGroupHistoryUpdateResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

