// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioCollectionDB struct {
	GroupId     int64
	UniqueId    int64
	ReceiveDate mx.MxTime
}

func (x *ScenarioCollectionDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
