// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioHistoryDB struct {
	ScenarioUniqueId int64
	ClearDateTime    mx.MxTime
}

func (x *ScenarioHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
