// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ScenarioRetreatResponse struct {
	*ResponsePacket

	ReleasedEchelonNumbers []int64
	ParcelResultDB         *ParcelResultDB
}

func (x *ScenarioRetreatResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ScenarioRetreatResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
