// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ScenarioAccountStudentChangeRequest struct{
	message ProtoMessage
	RequestPacket

    AccountStudent int64
    AccountStudentBefore int64
}

func (x *ScenarioAccountStudentChangeRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ScenarioAccountStudentChangeRequest) ProtoReflect() Message {
	return x
}

func (x *ScenarioAccountStudentChangeRequest) GetProtocol() int32 {
	return mx.Protocol_Scenario_AccountStudentChange
}

func (x *ScenarioAccountStudentChangeRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

