// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type SchoolDungeonBattleResultRequest struct{
	message ProtoMessage
	RequestPacket

    StageUniqueId int64
    PassCheckCharacter bool
    Summary *BattleSummary
}

func (x *SchoolDungeonBattleResultRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *SchoolDungeonBattleResultRequest) ProtoReflect() Message {
	return x
}

func (x *SchoolDungeonBattleResultRequest) GetProtocol() int32 {
	return mx.Protocol_SchoolDungeon_BattleResult
}

func (x *SchoolDungeonBattleResultRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

