// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type SchoolDungeonListResponse struct{
	message ProtoMessage
	ResponsePacket

    SchoolDungeonStageHistoryDBList []*SchoolDungeonStageHistoryDB
}

func (x *SchoolDungeonListResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *SchoolDungeonListResponse) ProtoReflect() Message {
	return x
}

func (x *SchoolDungeonListResponse) GetProtocol() int32 {
	return mx.Protocol_SchoolDungeon_List
}

func (x *SchoolDungeonListResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

