// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type SchoolDungeonEnterBattleRequest struct{
	message ProtoMessage
	RequestPacket

    StageUniqueId int64
}

func (x *SchoolDungeonEnterBattleRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *SchoolDungeonEnterBattleRequest) ProtoReflect() Message {
	return x
}

func (x *SchoolDungeonEnterBattleRequest) GetProtocol() int32 {
	return mx.Protocol_SchoolDungeon_EnterBattle
}

func (x *SchoolDungeonEnterBattleRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

