// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type SchoolDungeonRetreatResponse struct{
	message ProtoMessage
	ResponsePacket

    ParcelResultDB *ParcelResultDB
}

func (x *SchoolDungeonRetreatResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *SchoolDungeonRetreatResponse) ProtoReflect() Message {
	return x
}

func (x *SchoolDungeonRetreatResponse) GetProtocol() int32 {
	return mx.Protocol_SchoolDungeon_Retreat
}

func (x *SchoolDungeonRetreatResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

