// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ShiftingCraftInfoDB struct {
	SlotSequence  int64
	CraftRecipeId int64
	CraftAmount   int64
	StartTime     mx.MxTime
	EndTime       mx.MxTime
}

func (x *ShiftingCraftInfoDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
