// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type ShopEligmaHistoryDB struct {
	CharacterUniqueId int64
	PurchaseCount     int64
}

func (x *ShopEligmaHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
