// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ShopBuyGacha3Request struct {
	*RequestPacket

	ShopBuyGacha2Request
	FreeRecruitId int64
	Cost          *ParcelCost
}

func (x *ShopBuyGacha3Request) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ShopBuyGacha3Request) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
