// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBuyEligmaResponse struct{
	message ProtoMessage
	ResponsePacket

    ParcelResultDB *ParcelResultDB
    ConsumeResultDB *ConsumeResultDB
    ShopProductDB *ShopProductDB
}

func (x *ShopBuyEligmaResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBuyEligmaResponse) ProtoReflect() Message {
	return x
}

func (x *ShopBuyEligmaResponse) GetProtocol() int32 {
	return mx.Protocol_Shop_BuyEligma
}

func (x *ShopBuyEligmaResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

