// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type ShopProductType int32

const (
	ShopProductType_None    ShopProductType = 0
	ShopProductType_General ShopProductType = 1
	ShopProductType_Refresh ShopProductType = 2
)

var (
	ShopProductType_name = map[int32]string{
		0: "None",
		1: "General",
		2: "Refresh",
	}
	ShopProductType_value = map[string]int32{
		"None":    0,
		"General": 1,
		"Refresh": 2,
	}
)

func (x ShopProductType) String() string {
	return ShopProductType_name[int32(x)]
}

func (x ShopProductType) Value(sr string) ShopProductType {
	return ShopProductType(ShopProductType_value[sr])
}
