// Code generated by gucooing DO NOT EDIT.

package proto

type ShopCashBlockType int32

const (
    ShopCashBlockType_All = -1;
ShopCashBlockType_AppStore = -2;
ShopCashBlockType_GooglePlay = -3;
ShopCashBlockType_None = -9999;
)

var (
    ShopCashBlockType_name = map[int32]string{
    -1: "All",
    -2: "AppStore",
    -3: "GooglePlay",
    -9999: "None",
   }
    ShopCashBlockType_value = map[string]int32{
   "All":        -1,
   "AppStore":   -2,
   "GooglePlay": -3,
   "None":       -9999,
   }
)

func (x ShopCashBlockType) String() string {
  return ShopCashBlockType_name[int32(x)]
}

