// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBeforehandGachaSaveResponse struct{
	message ProtoMessage
	ResponsePacket

    SelectGachaSnapshot *BeforehandGachaSnapshotDB
}

func (x *ShopBeforehandGachaSaveResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBeforehandGachaSaveResponse) ProtoReflect() Message {
	return x
}

func (x *ShopBeforehandGachaSaveResponse) GetProtocol() int32 {
	return mx.Protocol_Shop_BeforehandGachaSave
}


func (x *ShopBeforehandGachaSaveResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

