// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopGachaRecruitListRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ShopGachaRecruitListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopGachaRecruitListRequest) ProtoReflect() Message {
	return x
}

func (x *ShopGachaRecruitListRequest) GetProtocol() int32 {
	return mx.Protocol_Shop_GachaRecruitList
}

func (x *ShopGachaRecruitListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

