// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ShopBuyMerchandiseResponse struct {
	*ResponsePacket

	AccountCurrencyDB *AccountCurrencyDB
	ConsumeResultDB   *ConsumeResultDB
	ParcelResultDB    *ParcelResultDB
	MailDB            *MailDB
	ShopProductDB     *ShopProductDB
}

func (x *ShopBuyMerchandiseResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ShopBuyMerchandiseResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
