// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"
	"time"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBuyGacha2Response struct{
	message ProtoMessage
	ResponsePacket

    UpdateTime time.Time
    GemBonusRemain int64
    GemPaidRemain int64
    ConsumedItems []*ItemDB
    GachaResults []*GachaResult
    AcquiredItems []*ItemDB
}

func (x *ShopBuyGacha2Response) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBuyGacha2Response) ProtoReflect() Message {
	return x
}

func (x *ShopBuyGacha2Response) GetProtocol() int32 {
	return mx.Protocol_Shop_BuyGacha2
}

func (x *ShopBuyGacha2Response) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

