// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBeforehandGachaRunResponse struct{
	message ProtoMessage
	ResponsePacket

    SelectGachaSnapshot *BeforehandGachaSnapshotDB
}

func (x *ShopBeforehandGachaRunResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBeforehandGachaRunResponse) ProtoReflect() Message {
	return x
}

func (x *ShopBeforehandGachaRunResponse) GetProtocol() int32 {
	return mx.Protocol_Shop_BeforehandGachaRun
}

func (x *ShopBeforehandGachaRunResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

