// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBuyEligmaRequest struct{
	message ProtoMessage
	RequestPacket

    GoodsUniqueId int64
    ShopUniqueId int64
    CharacterUniqueId int64
    PurchaseCount int64
}

func (x *ShopBuyEligmaRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBuyEligmaRequest) ProtoReflect() Message {
	return x
}

func (x *ShopBuyEligmaRequest) GetProtocol() int32 {
	return mx.Protocol_Shop_BuyEligma
}

func (x *ShopBuyEligmaRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

