// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBeforehandGachaPickRequest struct{
	message ProtoMessage
	RequestPacket

    ShopUniqueId int64
    GoodsId int64
    TargetIndex int64
}

func (x *ShopBeforehandGachaPickRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBeforehandGachaPickRequest) ProtoReflect() Message {
	return x
}

func (x *ShopBeforehandGachaPickRequest) GetProtocol() int32 {
	return mx.Protocol_Shop_BeforehandGachaPick
}

func (x *ShopBeforehandGachaPickRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

