// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ShopBuyGacha2Response struct {
	*ResponsePacket

	UpdateTime     mx.MxTime
	GemBonusRemain int64
	GemPaidRemain  int64
	ConsumedItems  []*ItemDB
	GachaResults   []*GachaResult
	AcquiredItems  []*ItemDB
}

func (x *ShopBuyGacha2Response) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ShopBuyGacha2Response) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
