// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ShopBeforehandGachaSaveRequest struct{
	message ProtoMessage
	RequestPacket

    TargetIndex int64
}

func (x *ShopBeforehandGachaSaveRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ShopBeforehandGachaSaveRequest) ProtoReflect() Message {
	return x
}

func (x *ShopBeforehandGachaSaveRequest) GetProtocol() int32 {
	return mx.Protocol_Shop_BeforehandGachaSave
}

func (x *ShopBeforehandGachaSaveRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

