// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type SkillSlot int32

const (
	SkillSlot_None                  SkillSlot = 0
	SkillSlot_NormalAttack01        SkillSlot = 1
	SkillSlot_NormalAttack02        SkillSlot = 2
	SkillSlot_NormalAttack03        SkillSlot = 3
	SkillSlot_NormalAttack04        SkillSlot = 4
	SkillSlot_NormalAttack05        SkillSlot = 5
	SkillSlot_NormalAttack06        SkillSlot = 6
	SkillSlot_NormalAttack07        SkillSlot = 7
	SkillSlot_NormalAttack08        SkillSlot = 8
	SkillSlot_NormalAttack09        SkillSlot = 9
	SkillSlot_NormalAttack10        SkillSlot = 10
	SkillSlot_ExSkill01             SkillSlot = 11
	SkillSlot_ExSkill02             SkillSlot = 12
	SkillSlot_ExSkill03             SkillSlot = 13
	SkillSlot_ExSkill04             SkillSlot = 14
	SkillSlot_ExSkill05             SkillSlot = 15
	SkillSlot_ExSkill06             SkillSlot = 16
	SkillSlot_ExSkill07             SkillSlot = 17
	SkillSlot_ExSkill08             SkillSlot = 18
	SkillSlot_ExSkill09             SkillSlot = 19
	SkillSlot_ExSkill10             SkillSlot = 20
	SkillSlot_Passive01             SkillSlot = 21
	SkillSlot_Passive02             SkillSlot = 22
	SkillSlot_Passive03             SkillSlot = 23
	SkillSlot_Passive04             SkillSlot = 24
	SkillSlot_Passive05             SkillSlot = 25
	SkillSlot_Passive06             SkillSlot = 26
	SkillSlot_Passive07             SkillSlot = 27
	SkillSlot_Passive08             SkillSlot = 28
	SkillSlot_Passive09             SkillSlot = 29
	SkillSlot_Passive10             SkillSlot = 30
	SkillSlot_ExtraPassive01        SkillSlot = 31
	SkillSlot_ExtraPassive02        SkillSlot = 32
	SkillSlot_ExtraPassive03        SkillSlot = 33
	SkillSlot_ExtraPassive04        SkillSlot = 34
	SkillSlot_ExtraPassive05        SkillSlot = 35
	SkillSlot_ExtraPassive06        SkillSlot = 36
	SkillSlot_ExtraPassive07        SkillSlot = 37
	SkillSlot_ExtraPassive08        SkillSlot = 38
	SkillSlot_ExtraPassive09        SkillSlot = 39
	SkillSlot_ExtraPassive10        SkillSlot = 40
	SkillSlot_Support01             SkillSlot = 41
	SkillSlot_Support02             SkillSlot = 42
	SkillSlot_Support03             SkillSlot = 43
	SkillSlot_Support04             SkillSlot = 44
	SkillSlot_Support05             SkillSlot = 45
	SkillSlot_Support06             SkillSlot = 46
	SkillSlot_Support07             SkillSlot = 47
	SkillSlot_Support08             SkillSlot = 48
	SkillSlot_Support09             SkillSlot = 49
	SkillSlot_Support10             SkillSlot = 50
	SkillSlot_EnterBattleGround     SkillSlot = 51
	SkillSlot_LeaderSkill01         SkillSlot = 52
	SkillSlot_LeaderSkill02         SkillSlot = 53
	SkillSlot_LeaderSkill03         SkillSlot = 54
	SkillSlot_LeaderSkill04         SkillSlot = 55
	SkillSlot_LeaderSkill05         SkillSlot = 56
	SkillSlot_LeaderSkill06         SkillSlot = 57
	SkillSlot_LeaderSkill07         SkillSlot = 58
	SkillSlot_LeaderSkill08         SkillSlot = 59
	SkillSlot_LeaderSkill09         SkillSlot = 60
	SkillSlot_LeaderSkill10         SkillSlot = 61
	SkillSlot_Equipment01           SkillSlot = 62
	SkillSlot_Equipment02           SkillSlot = 63
	SkillSlot_Equipment03           SkillSlot = 64
	SkillSlot_Equipment04           SkillSlot = 65
	SkillSlot_Equipment05           SkillSlot = 66
	SkillSlot_Equipment06           SkillSlot = 67
	SkillSlot_Equipment07           SkillSlot = 68
	SkillSlot_Equipment08           SkillSlot = 69
	SkillSlot_Equipment09           SkillSlot = 70
	SkillSlot_Equipment10           SkillSlot = 71
	SkillSlot_PublicSkill01         SkillSlot = 72
	SkillSlot_PublicSkill02         SkillSlot = 73
	SkillSlot_PublicSkill03         SkillSlot = 74
	SkillSlot_PublicSkill04         SkillSlot = 75
	SkillSlot_PublicSkill05         SkillSlot = 76
	SkillSlot_PublicSkill06         SkillSlot = 77
	SkillSlot_PublicSkill07         SkillSlot = 78
	SkillSlot_PublicSkill08         SkillSlot = 79
	SkillSlot_PublicSkill09         SkillSlot = 80
	SkillSlot_PublicSkill10         SkillSlot = 81
	SkillSlot_GroupBuff01           SkillSlot = 82
	SkillSlot_HexaBuff01            SkillSlot = 83
	SkillSlot_EventBuff01           SkillSlot = 84
	SkillSlot_EventBuff02           SkillSlot = 85
	SkillSlot_EventBuff03           SkillSlot = 86
	SkillSlot_MoveAttack01          SkillSlot = 87
	SkillSlot_MetamorphNormalAttack SkillSlot = 88
	SkillSlot_GroundPassive01       SkillSlot = 89
	SkillSlot_GroundPassive02       SkillSlot = 90
	SkillSlot_GroundPassive03       SkillSlot = 91
	SkillSlot_GroundPassive04       SkillSlot = 92
	SkillSlot_GroundPassive05       SkillSlot = 93
	SkillSlot_GroundPassive06       SkillSlot = 94
	SkillSlot_GroundPassive07       SkillSlot = 95
	SkillSlot_GroundPassive08       SkillSlot = 96
	SkillSlot_GroundPassive09       SkillSlot = 97
	SkillSlot_GroundPassive10       SkillSlot = 98
	SkillSlot_HiddenPassive01       SkillSlot = 99
	SkillSlot_HiddenPassive02       SkillSlot = 100
	SkillSlot_HiddenPassive03       SkillSlot = 101
	SkillSlot_HiddenPassive04       SkillSlot = 102
	SkillSlot_HiddenPassive05       SkillSlot = 103
	SkillSlot_HiddenPassive06       SkillSlot = 104
	SkillSlot_HiddenPassive07       SkillSlot = 105
	SkillSlot_HiddenPassive08       SkillSlot = 106
	SkillSlot_HiddenPassive09       SkillSlot = 107
	SkillSlot_HiddenPassive10       SkillSlot = 108
	SkillSlot_Count                 SkillSlot = 109
)

var (
	SkillSlot_name = map[int32]string{
		0:   "None",
		1:   "NormalAttack01",
		2:   "NormalAttack02",
		3:   "NormalAttack03",
		4:   "NormalAttack04",
		5:   "NormalAttack05",
		6:   "NormalAttack06",
		7:   "NormalAttack07",
		8:   "NormalAttack08",
		9:   "NormalAttack09",
		10:  "NormalAttack10",
		11:  "ExSkill01",
		12:  "ExSkill02",
		13:  "ExSkill03",
		14:  "ExSkill04",
		15:  "ExSkill05",
		16:  "ExSkill06",
		17:  "ExSkill07",
		18:  "ExSkill08",
		19:  "ExSkill09",
		20:  "ExSkill10",
		21:  "Passive01",
		22:  "Passive02",
		23:  "Passive03",
		24:  "Passive04",
		25:  "Passive05",
		26:  "Passive06",
		27:  "Passive07",
		28:  "Passive08",
		29:  "Passive09",
		30:  "Passive10",
		31:  "ExtraPassive01",
		32:  "ExtraPassive02",
		33:  "ExtraPassive03",
		34:  "ExtraPassive04",
		35:  "ExtraPassive05",
		36:  "ExtraPassive06",
		37:  "ExtraPassive07",
		38:  "ExtraPassive08",
		39:  "ExtraPassive09",
		40:  "ExtraPassive10",
		41:  "Support01",
		42:  "Support02",
		43:  "Support03",
		44:  "Support04",
		45:  "Support05",
		46:  "Support06",
		47:  "Support07",
		48:  "Support08",
		49:  "Support09",
		50:  "Support10",
		51:  "EnterBattleGround",
		52:  "LeaderSkill01",
		53:  "LeaderSkill02",
		54:  "LeaderSkill03",
		55:  "LeaderSkill04",
		56:  "LeaderSkill05",
		57:  "LeaderSkill06",
		58:  "LeaderSkill07",
		59:  "LeaderSkill08",
		60:  "LeaderSkill09",
		61:  "LeaderSkill10",
		62:  "Equipment01",
		63:  "Equipment02",
		64:  "Equipment03",
		65:  "Equipment04",
		66:  "Equipment05",
		67:  "Equipment06",
		68:  "Equipment07",
		69:  "Equipment08",
		70:  "Equipment09",
		71:  "Equipment10",
		72:  "PublicSkill01",
		73:  "PublicSkill02",
		74:  "PublicSkill03",
		75:  "PublicSkill04",
		76:  "PublicSkill05",
		77:  "PublicSkill06",
		78:  "PublicSkill07",
		79:  "PublicSkill08",
		80:  "PublicSkill09",
		81:  "PublicSkill10",
		82:  "GroupBuff01",
		83:  "HexaBuff01",
		84:  "EventBuff01",
		85:  "EventBuff02",
		86:  "EventBuff03",
		87:  "MoveAttack01",
		88:  "MetamorphNormalAttack",
		89:  "GroundPassive01",
		90:  "GroundPassive02",
		91:  "GroundPassive03",
		92:  "GroundPassive04",
		93:  "GroundPassive05",
		94:  "GroundPassive06",
		95:  "GroundPassive07",
		96:  "GroundPassive08",
		97:  "GroundPassive09",
		98:  "GroundPassive10",
		99:  "HiddenPassive01",
		100: "HiddenPassive02",
		101: "HiddenPassive03",
		102: "HiddenPassive04",
		103: "HiddenPassive05",
		104: "HiddenPassive06",
		105: "HiddenPassive07",
		106: "HiddenPassive08",
		107: "HiddenPassive09",
		108: "HiddenPassive10",
		109: "Count",
	}
	SkillSlot_value = map[string]int32{
		"None":                  0,
		"NormalAttack01":        1,
		"NormalAttack02":        2,
		"NormalAttack03":        3,
		"NormalAttack04":        4,
		"NormalAttack05":        5,
		"NormalAttack06":        6,
		"NormalAttack07":        7,
		"NormalAttack08":        8,
		"NormalAttack09":        9,
		"NormalAttack10":        10,
		"ExSkill01":             11,
		"ExSkill02":             12,
		"ExSkill03":             13,
		"ExSkill04":             14,
		"ExSkill05":             15,
		"ExSkill06":             16,
		"ExSkill07":             17,
		"ExSkill08":             18,
		"ExSkill09":             19,
		"ExSkill10":             20,
		"Passive01":             21,
		"Passive02":             22,
		"Passive03":             23,
		"Passive04":             24,
		"Passive05":             25,
		"Passive06":             26,
		"Passive07":             27,
		"Passive08":             28,
		"Passive09":             29,
		"Passive10":             30,
		"ExtraPassive01":        31,
		"ExtraPassive02":        32,
		"ExtraPassive03":        33,
		"ExtraPassive04":        34,
		"ExtraPassive05":        35,
		"ExtraPassive06":        36,
		"ExtraPassive07":        37,
		"ExtraPassive08":        38,
		"ExtraPassive09":        39,
		"ExtraPassive10":        40,
		"Support01":             41,
		"Support02":             42,
		"Support03":             43,
		"Support04":             44,
		"Support05":             45,
		"Support06":             46,
		"Support07":             47,
		"Support08":             48,
		"Support09":             49,
		"Support10":             50,
		"EnterBattleGround":     51,
		"LeaderSkill01":         52,
		"LeaderSkill02":         53,
		"LeaderSkill03":         54,
		"LeaderSkill04":         55,
		"LeaderSkill05":         56,
		"LeaderSkill06":         57,
		"LeaderSkill07":         58,
		"LeaderSkill08":         59,
		"LeaderSkill09":         60,
		"LeaderSkill10":         61,
		"Equipment01":           62,
		"Equipment02":           63,
		"Equipment03":           64,
		"Equipment04":           65,
		"Equipment05":           66,
		"Equipment06":           67,
		"Equipment07":           68,
		"Equipment08":           69,
		"Equipment09":           70,
		"Equipment10":           71,
		"PublicSkill01":         72,
		"PublicSkill02":         73,
		"PublicSkill03":         74,
		"PublicSkill04":         75,
		"PublicSkill05":         76,
		"PublicSkill06":         77,
		"PublicSkill07":         78,
		"PublicSkill08":         79,
		"PublicSkill09":         80,
		"PublicSkill10":         81,
		"GroupBuff01":           82,
		"HexaBuff01":            83,
		"EventBuff01":           84,
		"EventBuff02":           85,
		"EventBuff03":           86,
		"MoveAttack01":          87,
		"MetamorphNormalAttack": 88,
		"GroundPassive01":       89,
		"GroundPassive02":       90,
		"GroundPassive03":       91,
		"GroundPassive04":       92,
		"GroundPassive05":       93,
		"GroundPassive06":       94,
		"GroundPassive07":       95,
		"GroundPassive08":       96,
		"GroundPassive09":       97,
		"GroundPassive10":       98,
		"HiddenPassive01":       99,
		"HiddenPassive02":       100,
		"HiddenPassive03":       101,
		"HiddenPassive04":       102,
		"HiddenPassive05":       103,
		"HiddenPassive06":       104,
		"HiddenPassive07":       105,
		"HiddenPassive08":       106,
		"HiddenPassive09":       107,
		"HiddenPassive10":       108,
		"Count":                 109,
	}
)

func (x SkillSlot) String() string {
	return SkillSlot_name[int32(x)]
}

func (x SkillSlot) Value(sr string) SkillSlot {
	return SkillSlot(SkillSlot_value[sr])
}
