// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type SkillCostUseSnapshot struct {
	*ValueType

	Frame  int64
	Used   float32
	CharId int64
	Level  int32
}

func (x *SkillCostUseSnapshot) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *SkillCostUseSnapshot) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ValueType = packet.(*ValueType)
}
