// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type SkillCostSummary struct {
	InitialCost           float32
	CostPerFrameSnapshots []*CostRegenSnapshotCollection
	CostAddSnapshots      []*SkillCostAddSnapshot
	CostUseSnapshots      []*SkillCostUseSnapshot
}

func (x *SkillCostSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
