// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type SkillCardHand struct {
	Cost             float32
	SkillCardsInHand []*SkillCardInfo
}

func (x *SkillCardHand) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
