// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type SkipHistoryDB struct {
	Prologue int32
	Tutorial map[int32]int32
}

func (x *SkipHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
