// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type SkipHistorySaveResponse struct {
	*ResponsePacket

	SkipHistoryDB *SkipHistoryDB
}

func (x *SkipHistorySaveResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *SkipHistorySaveResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
