// Code generated by gucooing DO NOT EDIT.

package proto

type StarGoalType string

const (
    StarGoalType_None = 0
    StarGoalType_AllAlive = 1
    StarGoalType_Clear = 2
    StarGoalType_GetBoxes = 3
    StarGoalType_ClearTimeInSec = 4
    StarGoalType_AllyBaseDamage = 5
)

var (
    StarGoalType_name = map[int32]string{
      0 : "None",
      1 : "AllAlive",
      2 : "Clear",
      3 : "GetBoxes",
      4 : "ClearTimeInSec",
      5 : "AllyBaseDamage",
   }
    StarGoalType_value = map[string]int32{
      "None" : 0,
      "AllAlive" : 1,
      "Clear" : 2,
      "GetBoxes" : 3,
      "ClearTimeInSec" : 4,
      "AllyBaseDamage" : 5,
   }
)

func (x StarGoalType) Value() int32 {
  return StarGoalType_value[string(x)]
}

