// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type StatSnapshotCollection struct {
	Stat  int64
	Start int64
	End   int64
}

func (x *StatSnapshotCollection) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *StatSnapshotCollection) SetPacket(packet mx.Message) {

}
