// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type StickerLobbyResponse struct {
	*ResponsePacket

	ReceivedStickerDBs []*StickerDB
	StickerBookDB      *StickerBookDB
}

func (x *StickerLobbyResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *StickerLobbyResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
