// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type StickerDB struct {
	*ParcelBase

	Type            ParcelType
	StickerUniqueId int64
	ParcelInfos     []*ParcelInfo
}

func (x *StickerDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *StickerDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ParcelBase = packet.(*ParcelBase)
}
