// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type StoryStrategyStageSaveDB struct {
	*CampaignMainStageSaveDB

	ContentType ContentType
}

func (x *StoryStrategyStageSaveDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *StoryStrategyStageSaveDB) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.CampaignMainStageSaveDB = packet.(*CampaignMainStageSaveDB)
}
