// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type StrategyClearRewardInfo struct {
	FirstClearReward        []*ParcelInfo
	ThreeStarReward         []*ParcelInfo
	StrategyObjectRewards   map[int64][]*ParcelInfo
	ParcelResultDB          *ParcelResultDB
	ClearReward             []*ParcelInfo
	ExpReward               []*ParcelInfo
	TotalReward             []*ParcelInfo
	EventContentReward      []*ParcelInfo
	EventContentBonusReward []*ParcelInfo
	CampaignStageHistoryDB  *CampaignStageHistoryDB
}

func (x *StrategyClearRewardInfo) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
