// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type SuddenMissionContentType int32

const (
	SuddenMissionContentType_OrdinaryState       SuddenMissionContentType = 0
	SuddenMissionContentType_CampaignNormalStage SuddenMissionContentType = 1
	SuddenMissionContentType_CampaignHardStage   SuddenMissionContentType = 2
	SuddenMissionContentType_EventStage          SuddenMissionContentType = 3
	SuddenMissionContentType_WeekDungeon         SuddenMissionContentType = 4
	SuddenMissionContentType_Chaser              SuddenMissionContentType = 5
	SuddenMissionContentType_SchoolDungeon       SuddenMissionContentType = 6
	SuddenMissionContentType_TimeAttackDungeon   SuddenMissionContentType = 7
	SuddenMissionContentType_Raid                SuddenMissionContentType = 8
)

var (
	SuddenMissionContentType_name = map[int32]string{
		0: "OrdinaryState",
		1: "CampaignNormalStage",
		2: "CampaignHardStage",
		3: "EventStage",
		4: "WeekDungeon",
		5: "Chaser",
		6: "SchoolDungeon",
		7: "TimeAttackDungeon",
		8: "Raid",
	}
	SuddenMissionContentType_value = map[string]int32{
		"OrdinaryState":       0,
		"CampaignNormalStage": 1,
		"CampaignHardStage":   2,
		"EventStage":          3,
		"WeekDungeon":         4,
		"Chaser":              5,
		"SchoolDungeon":       6,
		"TimeAttackDungeon":   7,
		"Raid":                8,
	}
)

func (x SuddenMissionContentType) String() string {
	return SuddenMissionContentType_name[int32(x)]
}

func (x SuddenMissionContentType) Value(sr string) SuddenMissionContentType {
	return SuddenMissionContentType(SuddenMissionContentType_value[sr])
}
