// Code generated by gucooing DO NOT EDIT.

package proto

type SuddenMissionContentType int32

const (
    SuddenMissionContentType_OrdinaryState = 0
    SuddenMissionContentType_CampaignNormalStage = 1
    SuddenMissionContentType_CampaignHardStage = 2
    SuddenMissionContentType_EventStage = 3
    SuddenMissionContentType_WeekDungeon = 4
    SuddenMissionContentType_Chaser = 5
    SuddenMissionContentType_SchoolDungeon = 6
    SuddenMissionContentType_TimeAttackDungeon = 7
    SuddenMissionContentType_Raid = 8
)

var (
    SuddenMissionContentType_name = map[int32]string{
      0 : "OrdinaryState",
      1 : "CampaignNormalStage",
      2 : "CampaignHardStage",
      3 : "EventStage",
      4 : "WeekDungeon",
      5 : "Chaser",
      6 : "SchoolDungeon",
      7 : "TimeAttackDungeon",
      8 : "Raid",
   }
    SuddenMissionContentType_value = map[string]int32{
      "OrdinaryState" : 0,
      "CampaignNormalStage" : 1,
      "CampaignHardStage" : 2,
      "EventStage" : 3,
      "WeekDungeon" : 4,
      "Chaser" : 5,
      "SchoolDungeon" : 6,
      "TimeAttackDungeon" : 7,
      "Raid" : 8,
   }
)

func (x SuddenMissionContentType) String() string {
  return SuddenMissionContentType_name[int32(x)]
}

