// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type SystemVersionResponse struct {
	*ResponsePacket

	CurrentVersion int64
	MinimumVersion int64
	IsDevelopment  bool
}

func (x *SystemVersionResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *SystemVersionResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
