// Code generated by gucooing DO NOT EDIT.

package proto

type TacticEntityType int32

const (
	TacticEntityType_None                   = 0
	TacticEntityType_Student                = 1
	TacticEntityType_Minion                 = 2
	TacticEntityType_Elite                  = 4
	TacticEntityType_Champion               = 8
	TacticEntityType_Boss                   = 16
	TacticEntityType_Obstacle               = 32
	TacticEntityType_Servant                = 64
	TacticEntityType_Vehicle                = 128
	TacticEntityType_Summoned               = 256
	TacticEntityType_Hallucination          = 512
	TacticEntityType_DestructibleProjectile = 1024
)

var (
	TacticEntityType_name = map[int32]string{
		0:    "None",
		1:    "Student",
		2:    "Minion",
		4:    "Elite",
		8:    "Champion",
		16:   "Boss",
		32:   "Obstacle",
		64:   "Servant",
		128:  "Vehicle",
		256:  "Summoned",
		512:  "Hallucination",
		1024: "DestructibleProjectile",
	}
	TacticEntityType_value = map[string]int32{
		"None":                   0,
		"Student":                1,
		"Minion":                 2,
		"Elite":                  4,
		"Champion":               8,
		"Boss":                   16,
		"Obstacle":               32,
		"Servant":                64,
		"Vehicle":                128,
		"Summoned":               256,
		"Hallucination":          512,
		"DestructibleProjectile": 1024,
	}
)

func (x TacticEntityType) String() string {
	return TacticEntityType_name[int32(x)]
}
