// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TacticSkipSummary struct {
	StageId           int64
	Group01HexaUnitId int64
	Group02HexaUnitId int64
}

func (x *TacticSkipSummary) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
