// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGDiceRollResult int32

const (
	TBGDiceRollResult_Failure         TBGDiceRollResult = 0
	TBGDiceRollResult_Success         TBGDiceRollResult = 1
	TBGDiceRollResult_CriticalSuccess TBGDiceRollResult = 2
)

var (
	TBGDiceRollResult_name = map[int32]string{
		0: "Failure",
		1: "Success",
		2: "CriticalSuccess",
	}
	TBGDiceRollResult_value = map[string]int32{
		"Failure":         0,
		"Success":         1,
		"CriticalSuccess": 2,
	}
)

func (x TBGDiceRollResult) String() string {
	return TBGDiceRollResult_name[int32(x)]
}

func (x TBGDiceRollResult) Value(sr string) TBGDiceRollResult {
	return TBGDiceRollResult(TBGDiceRollResult_value[sr])
}
