// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TBGEncounterDB struct {
	EncounterInfo                   *ITBGEncounterInfo
	EncounterRewardReceiveIndex     int32
	EncounterState                  TBGEncounterState
	EncounterStageCode              int32
	EncounterId                     int64
	InvokerServerId                 int64
	ObjectType                      int32
	ShouldDecreaseItemEffectCounter bool
	RewardUniqueIdByIndex           map[int32]int64
}

func (x *TBGEncounterDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
