// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TBGHexaMapData struct {
	Tiles           []*TBGHexaTileData
	Spawns          []*TBGHexaSpawnData
	TileLocationMap map[*HexLocation]*TBGHexaTileData
}

func (x *TBGHexaMapData) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
