// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGHexaObjectSpawnRule int32

const (
	TBGHexaObjectSpawnRule_Nothing    TBGHexaObjectSpawnRule = 0
	TBGHexaObjectSpawnRule_ObjectId   TBGHexaObjectSpawnRule = 1
	TBGHexaObjectSpawnRule_ObjectType TBGHexaObjectSpawnRule = 2
)

var (
	TBGHexaObjectSpawnRule_name = map[int32]string{
		0: "Nothing",
		1: "ObjectId",
		2: "ObjectType",
	}
	TBGHexaObjectSpawnRule_value = map[string]int32{
		"Nothing":    0,
		"ObjectId":   1,
		"ObjectType": 2,
	}
)

func (x TBGHexaObjectSpawnRule) String() string {
	return TBGHexaObjectSpawnRule_name[int32(x)]
}

func (x TBGHexaObjectSpawnRule) Value(sr string) TBGHexaObjectSpawnRule {
	return TBGHexaObjectSpawnRule(TBGHexaObjectSpawnRule_value[sr])
}
