// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TBGItemEffectDB struct {
	ItemInfo                *ITBGItemInfo
	IsDirty                 bool
	Activated               bool
	Stack                   int32
	ItemUniqueId            int64
	ItemType                TBGItemType
	EffectType              TBGItemEffectType
	RemainEncounterCounter  int32
	_remainEncounterCounter int32
	AddedNow                bool
}

func (x *TBGItemEffectDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
