// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGItemEffectType int32

const (
	TBGItemEffectType_None                  TBGItemEffectType = 0
	TBGItemEffectType_PermanentContinuity   TBGItemEffectType = 1
	TBGItemEffectType_TemporaryContinuation TBGItemEffectType = 2
	TBGItemEffectType_Immediately           TBGItemEffectType = 3
)

var (
	TBGItemEffectType_name = map[int32]string{
		0: "None",
		1: "PermanentContinuity",
		2: "TemporaryContinuation",
		3: "Immediately",
	}
	TBGItemEffectType_value = map[string]int32{
		"None":                  0,
		"PermanentContinuity":   1,
		"TemporaryContinuation": 2,
		"Immediately":           3,
	}
)

func (x TBGItemEffectType) String() string {
	return TBGItemEffectType_name[int32(x)]
}

func (x TBGItemEffectType) Value(sr string) TBGItemEffectType {
	return TBGItemEffectType(TBGItemEffectType_value[sr])
}
