// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGObjectInteractionType int32

const (
	TBGObjectInteractionType_None      TBGObjectInteractionType = 0
	TBGObjectInteractionType_Encounter TBGObjectInteractionType = 1
	TBGObjectInteractionType_Portal    TBGObjectInteractionType = 2
)

var (
	TBGObjectInteractionType_name = map[int32]string{
		0: "None",
		1: "Encounter",
		2: "Portal",
	}
	TBGObjectInteractionType_value = map[string]int32{
		"None":      0,
		"Encounter": 1,
		"Portal":    2,
	}
)

func (x TBGObjectInteractionType) String() string {
	return TBGObjectInteractionType_name[int32(x)]
}

func (x TBGObjectInteractionType) Value(sr string) TBGObjectInteractionType {
	return TBGObjectInteractionType(TBGObjectInteractionType_value[sr])
}
