// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGObjectType int32

const (
	TBGObjectType_None        TBGObjectType = 0
	TBGObjectType_EnemyBoss   TBGObjectType = 1
	TBGObjectType_EnemyMinion TBGObjectType = 2
	TBGObjectType_Random      TBGObjectType = 3
	TBGObjectType_Facility    TBGObjectType = 4
	TBGObjectType_TreasureBox TBGObjectType = 5
	TBGObjectType_Start       TBGObjectType = 6
	TBGObjectType_Portal      TBGObjectType = 7
)

var (
	TBGObjectType_name = map[int32]string{
		0: "None",
		1: "EnemyBoss",
		2: "EnemyMinion",
		3: "Random",
		4: "Facility",
		5: "TreasureBox",
		6: "Start",
		7: "Portal",
	}
	TBGObjectType_value = map[string]int32{
		"None":        0,
		"EnemyBoss":   1,
		"EnemyMinion": 2,
		"Random":      3,
		"Facility":    4,
		"TreasureBox": 5,
		"Start":       6,
		"Portal":      7,
	}
)

func (x TBGObjectType) String() string {
	return TBGObjectType_name[int32(x)]
}

func (x TBGObjectType) Value(sr string) TBGObjectType {
	return TBGObjectType(TBGObjectType_value[sr])
}
