// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TBGPlayerDB struct {
	SeasonInfo                         *ITBGSeasonInfo
	MaxHitPoint                        int32
	IsMaxHitPointReached               bool
	CurrentDiceInfo                    *ITBGDiceInfo
	ActivatedDefenceEffect             *TBGItemEffectDB
	ActivatedDefenceCriticalEffect     *TBGItemEffectDB
	ActivatedGuideEffect               *TBGItemEffectDB
	ActivatedDiceAddDotEffect          []*TBGItemEffectDB
	ActivatedPermanentDiceAddDotEffect []*TBGItemEffectDB
	IsMaxPermanentDiceAddDotReached    bool
	ActivatedDiceForceDotEffect        *TBGItemEffectDB
	ItemSlots                          []*TBGItemDB
	Location                           *HexLocation
	EventContentId                     int64
	HitPoint                           int32
	DiceId                             int64
	DiceProbModifyParams               map[TBGProbModifyCondition]int32
	Items                              []*TBGItemDB
	TemporaryItem                      *TBGItemDB
	HasItemsDirty                      bool
	ItemEffects                        []*TBGItemEffectDB
	HasItemEffectDirty                 bool
	IsDead                             bool
}

func (x *TBGPlayerDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
