// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TBGTileType int32

const (
	TBGTileType_None      TBGTileType = 0
	TBGTileType_Start     TBGTileType = 1
	TBGTileType_Movable   TBGTileType = 2
	TBGTileType_UnMovable TBGTileType = 3
)

var (
	TBGTileType_name = map[int32]string{
		0: "None",
		1: "Start",
		2: "Movable",
		3: "UnMovable",
	}
	TBGTileType_value = map[string]int32{
		"None":      0,
		"Start":     1,
		"Movable":   2,
		"UnMovable": 3,
	}
)

func (x TBGTileType) String() string {
	return TBGTileType_name[int32(x)]
}

func (x TBGTileType) Value(sr string) TBGTileType {
	return TBGTileType(TBGTileType_value[sr])
}
