// Code generated by gucooing DO NOT EDIT.

package proto

type TileState int32

const (
    TileState_None = 0
    TileState_PartiallyConquested = 1
    TileState_FullyConquested = 2
)

var (
    TileState_name = map[int32]string{
      0 : "None",
      1 : "PartiallyConquested",
      2 : "FullyConquested",
   }
    TileState_value = map[string]int32{
      "None" : 0,
      "PartiallyConquested" : 1,
      "FullyConquested" : 2,
   }
)

func (x TileState) String() string {
  return TileState_name[int32(x)]
}

