// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TileState int32

const (
	TileState_None                TileState = 0
	TileState_PartiallyConquested TileState = 1
	TileState_FullyConquested     TileState = 2
)

var (
	TileState_name = map[int32]string{
		0: "None",
		1: "PartiallyConquested",
		2: "FullyConquested",
	}
	TileState_value = map[string]int32{
		"None":                0,
		"PartiallyConquested": 1,
		"FullyConquested":     2,
	}
)

func (x TileState) String() string {
	return TileState_name[int32(x)]
}

func (x TileState) Value(sr string) TileState {
	return TileState(TileState_value[sr])
}
