// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type TimeAttackDungeonEnterBattleResponse struct{
	message ProtoMessage
	ResponsePacket

    AssistCharacterDB *AssistCharacterDB
}

func (x *TimeAttackDungeonEnterBattleResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *TimeAttackDungeonEnterBattleResponse) ProtoReflect() Message {
	return x
}

func (x *TimeAttackDungeonEnterBattleResponse) GetProtocol() int32 {
	return mx.Protocol_TimeAttackDungeon_EnterBattle
}

func (x *TimeAttackDungeonEnterBattleResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

