// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type TimeAttackDungeonLobbyResponse struct{
	message ProtoMessage
	ResponsePacket

    RoomDBs map[int64]*TimeAttackDungeonRoomDB
    PreviousRoomDB *TimeAttackDungeonRoomDB
    ParcelResultDB *ParcelResultDB
    AchieveSeasonBestRecord bool
    SeasonBestRecord int64
}

func (x *TimeAttackDungeonLobbyResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *TimeAttackDungeonLobbyResponse) ProtoReflect() Message {
	return x
}

func (x *TimeAttackDungeonLobbyResponse) GetProtocol() int32 {
	return mx.Protocol_TimeAttackDungeon_Lobby
}

func (x *TimeAttackDungeonLobbyResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

