// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
)

type TimeAttackDungeonBattleHistoryDB struct {
	DungeonType         TimeAttackDungeonType
	GeasId              int64
	DefaultPoint        int64
	ClearTimePoint      int64
	EndFrame            int64
	TotalPoint          int64
	MainCharacterDBs    []*TimeAttackDungeonCharacterDB
	SupportCharacterDBs []*TimeAttackDungeonCharacterDB
}

func (x *TimeAttackDungeonBattleHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
