// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type TimeAttackDungeonEndBattleResponse struct{
	message ProtoMessage
	ResponsePacket

    RoomDB *TimeAttackDungeonRoomDB
    TotalPoint int64
    DefaultPoint int64
    TimePoint int64
    ParcelResultDB *ParcelResultDB
}

func (x *TimeAttackDungeonEndBattleResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *TimeAttackDungeonEndBattleResponse) ProtoReflect() Message {
	return x
}

func (x *TimeAttackDungeonEndBattleResponse) GetProtocol() int32 {
	return mx.Protocol_TimeAttackDungeon_EndBattle
}

func (x *TimeAttackDungeonEndBattleResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

