// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type TimeAttackDungeonGiveUpResponse struct {
	*ResponsePacket

	RoomDB                  *TimeAttackDungeonRoomDB
	ParcelResultDB          *ParcelResultDB
	AchieveSeasonBestRecord bool
	SeasonBestRecord        int64
}

func (x *TimeAttackDungeonGiveUpResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *TimeAttackDungeonGiveUpResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
