// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type TimeAttackDungeonEndBattleResponse struct {
	*ResponsePacket

	RoomDB         *TimeAttackDungeonRoomDB
	TotalPoint     int64
	DefaultPoint   int64
	TimePoint      int64
	ParcelResultDB *ParcelResultDB
}

func (x *TimeAttackDungeonEndBattleResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *TimeAttackDungeonEndBattleResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
