// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type TimeAttackDungeonGiveUpResponse struct{
	message ProtoMessage
	ResponsePacket

    RoomDB *TimeAttackDungeonRoomDB
    ParcelResultDB *ParcelResultDB
    AchieveSeasonBestRecord bool
    SeasonBestRecord int64
}

func (x *TimeAttackDungeonGiveUpResponse) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *TimeAttackDungeonGiveUpResponse) ProtoReflect() Message {
	return x
}

func (x *TimeAttackDungeonGiveUpResponse) GetProtocol() int32 {
	return mx.Protocol_TimeAttackDungeon_GiveUp
}

func (x *TimeAttackDungeonGiveUpResponse) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

