// Code generated by gucooing DO NOT EDIT.

package proto

type TimeAttackDungeonBattleHistoryDB struct{
    DungeonType TimeAttackDungeonType
    GeasId int64
    DefaultPoint int64
    ClearTimePoint int64
    EndFrame int64
    MainCharacterDBs []*TimeAttackDungeonCharacterDB
    SupportCharacterDBs []*TimeAttackDungeonCharacterDB
}

