// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"encoding/json"

	"github.com/gucooing/BaPs/pkg/mx"
)

type ToastListRequest struct{
	message ProtoMessage
	RequestPacket

    
}

func (x *ToastListRequest) String() string {
	j, _ := json.Marshal(x)
	return string(j)
}

func (x *ToastListRequest) ProtoReflect() Message {
	return x
}

func (x *ToastListRequest) GetProtocol() int32 {
	return mx.Protocol_Toast_List
}

func (x *ToastListRequest) SetSessionKey(base *BasePacket) {
	if x == nil {
		return
	}
	x.BasePacket = base
}

