// Code generated by gucooing DO NOT EDIT.

package proto

import (
	"time"
)

type ToastDB struct {
	UniqueId     int64
	Text         string
	LocalizeText map[Language]string
	ToastId      string
	BeginDate    time.Time
	EndDate      time.Time
	LifeTime     int32
	Delay        int32
}
