// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type TTSGetFileResponse struct {
	*ResponsePacket

	IsFileReady  bool
	TTSFileS3Uri string
}

func (x *TTSGetFileResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *TTSGetFileResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
