// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.
package proto

type TypeAttributes int32

const (
	TypeAttributes_VisibilityMask     TypeAttributes = 7
	TypeAttributes_NotPublic          TypeAttributes = 0
	TypeAttributes_Public             TypeAttributes = 1
	TypeAttributes_NestedPublic       TypeAttributes = 2
	TypeAttributes_NestedPrivate      TypeAttributes = 3
	TypeAttributes_NestedFamily       TypeAttributes = 4
	TypeAttributes_NestedAssembly     TypeAttributes = 5
	TypeAttributes_NestedFamANDAssem  TypeAttributes = 6
	TypeAttributes_NestedFamORAssem   TypeAttributes = 7
	TypeAttributes_LayoutMask         TypeAttributes = 24
	TypeAttributes_AutoLayout         TypeAttributes = 0
	TypeAttributes_SequentialLayout   TypeAttributes = 8
	TypeAttributes_ExplicitLayout     TypeAttributes = 16
	TypeAttributes_ClassSemanticsMask TypeAttributes = 32
	TypeAttributes_Class              TypeAttributes = 0
	TypeAttributes_Interface          TypeAttributes = 32
	TypeAttributes_Abstract           TypeAttributes = 128
	TypeAttributes_Sealed             TypeAttributes = 256
	TypeAttributes_SpecialName        TypeAttributes = 1024
	TypeAttributes_Import             TypeAttributes = 4096
	TypeAttributes_Serializable       TypeAttributes = 8192
	TypeAttributes_WindowsRuntime     TypeAttributes = 16384
	TypeAttributes_StringFormatMask   TypeAttributes = 196608
	TypeAttributes_AnsiClass          TypeAttributes = 0
	TypeAttributes_UnicodeClass       TypeAttributes = 65536
	TypeAttributes_AutoClass          TypeAttributes = 131072
	TypeAttributes_CustomFormatClass  TypeAttributes = 196608
	TypeAttributes_CustomFormatMask   TypeAttributes = 12582912
	TypeAttributes_BeforeFieldInit    TypeAttributes = 1048576
	TypeAttributes_RTSpecialName      TypeAttributes = 2048
	TypeAttributes_HasSecurity        TypeAttributes = 262144
	TypeAttributes_ReservedMask       TypeAttributes = 264192
)

var (
	TypeAttributes_name = map[int32]string{
		0:        "NotPublic",
		1:        "Public",
		2:        "NestedPublic",
		3:        "NestedPrivate",
		4:        "NestedFamily",
		5:        "NestedAssembly",
		6:        "NestedFamANDAssem",
		7:        "NestedFamORAssem",
		24:       "LayoutMask",
		8:        "SequentialLayout",
		16:       "ExplicitLayout",
		32:       "ClassSemanticsMask",
		128:      "Abstract",
		256:      "Sealed",
		1024:     "SpecialName",
		4096:     "Import",
		8192:     "Serializable",
		16384:    "WindowsRuntime",
		65536:    "UnicodeClass",
		131072:   "AutoClass",
		196608:   "CustomFormatClass",
		12582912: "CustomFormatMask",
		1048576:  "BeforeFieldInit",
		2048:     "RTSpecialName",
		262144:   "HasSecurity",
		264192:   "ReservedMask",
	}
	TypeAttributes_value = map[string]int32{
		"VisibilityMask":     7,
		"NotPublic":          0,
		"Public":             1,
		"NestedPublic":       2,
		"NestedPrivate":      3,
		"NestedFamily":       4,
		"NestedAssembly":     5,
		"NestedFamANDAssem":  6,
		"NestedFamORAssem":   7,
		"LayoutMask":         24,
		"AutoLayout":         0,
		"SequentialLayout":   8,
		"ExplicitLayout":     16,
		"ClassSemanticsMask": 32,
		"Class":              0,
		"Interface":          32,
		"Abstract":           128,
		"Sealed":             256,
		"SpecialName":        1024,
		"Import":             4096,
		"Serializable":       8192,
		"WindowsRuntime":     16384,
		"StringFormatMask":   196608,
		"AnsiClass":          0,
		"UnicodeClass":       65536,
		"AutoClass":          131072,
		"CustomFormatClass":  196608,
		"CustomFormatMask":   12582912,
		"BeforeFieldInit":    1048576,
		"RTSpecialName":      2048,
		"HasSecurity":        262144,
		"ReservedMask":       264192,
	}
)

func (x TypeAttributes) String() string {
	return TypeAttributes_name[int32(x)]
}

func (x TypeAttributes) Value(sr string) TypeAttributes {
	return TypeAttributes(TypeAttributes_value[sr])
}
