// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type ValueType struct {
}

func (x *ValueType) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *ValueType) SetPacket(packet mx.Message) {

}
