// Code generated by gucooing DO NOT EDIT.

package proto

type WeekDungeonType int32

const (
	WeekDungeonType_None     = 0
	WeekDungeonType_ChaserA  = 1
	WeekDungeonType_ChaserB  = 2
	WeekDungeonType_ChaserC  = 3
	WeekDungeonType_FindGift = 4
	WeekDungeonType_Blood    = 5
)

var (
	WeekDungeonType_name = map[int32]string{
		0: "None",
		1: "ChaserA",
		2: "ChaserB",
		3: "ChaserC",
		4: "FindGift",
		5: "Blood",
	}
	WeekDungeonType_value = map[string]int32{
		"None":     0,
		"ChaserA":  1,
		"ChaserB":  2,
		"ChaserC":  3,
		"FindGift": 4,
		"Blood":    5,
	}
)

func (x WeekDungeonType) String() string {
	return WeekDungeonType_name[int32(x)]
}
