// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WeekDungeonEnterBattleResponse struct {
	*ResponsePacket

	ParcelResultDB *ParcelResultDB
	Seed           int32
	Sequence       int32
}

func (x *WeekDungeonEnterBattleResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *WeekDungeonEnterBattleResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
