// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WeekDungeonBattleResultResponse struct {
	*ResponsePacket

	WeekDungeonStageHistoryDB *WeekDungeonStageHistoryDB
	LevelUpCharacterDBs       []*CharacterDB
	ParcelResultDB            *ParcelResultDB
}

func (x *WeekDungeonBattleResultResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *WeekDungeonBattleResultResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
