// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WorldRaidClearHistoryDB struct {
	SeasonId          int64
	GroupId           int64
	RewardReceiveDate mx.MxTime
}

func (x *WorldRaidClearHistoryDB) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}
