// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WorldRaidBattleResultRequest struct {
	*RequestPacket

	SeasonId       int64
	GroupId        int64
	UniqueId       int64
	EchelonId      int64
	IsPractice     bool
	IsTicket       bool
	Summary        *BattleSummary
	AssistUseInfos []*ClanAssistUseInfo
}

func (x *WorldRaidBattleResultRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *WorldRaidBattleResultRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
