// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WorldRaidBossGroup struct {
	*ContentsValueChangeDB

	ContentsChangeType ContentsChangeType
	GroupId            int64
	BossSpawnTime      mx.MxTime
	EliminateTime      mx.MxTime
}

func (x *WorldRaidBossGroup) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *WorldRaidBossGroup) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ContentsValueChangeDB = packet.(*ContentsValueChangeDB)
}
