// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"github.com/gucooing/BaPs/protocol/mx"
)

type WorldRaidEnterBattleResponse struct {
	*ResponsePacket

	RaidBattleDB       *RaidBattleDB
	AssistCharacterDBs []*AssistCharacterDB
}

func (x *WorldRaidEnterBattleResponse) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *WorldRaidEnterBattleResponse) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.ResponsePacket = packet.(*ResponsePacket)
}
